var h;h||=typeof Module != 'undefined' ? Module : {};var ba="object"==typeof window,ca="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node;h.Se||(h.Se=0);h.Se++;
(()=>{var a="undefined"!=typeof ENVIRONMENT_IS_WASM_WORKER&&ENVIRONMENT_IS_WASM_WORKER;"undefined"!=typeof ENVIRONMENT_IS_PTHREAD&&ENVIRONMENT_IS_PTHREAD||a||function(b){function c(p,r,u,y){if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)require("fs").readFile(p,function(w,B){w?y(w):u(B.buffer)});else{var A=new XMLHttpRequest;A.open("GET",p,!0);A.responseType="arraybuffer";A.onprogress=function(w){var B=r;w.total&&(B=w.total);if(w.loaded){A.ge?
h.Ae[p].loaded=w.loaded:(A.ge=!0,h.Ae||(h.Ae={}),h.Ae[p]={loaded:w.loaded,total:B});var N=B=w=0,da;for(da in h.Ae){var aa=h.Ae[da];w+=aa.total;B+=aa.loaded;N++}w=Math.ceil(w*h.Se/N);h.setStatus?.(`Downloading data... (${B}/${w})`)}else h.Ae||h.setStatus?.("Downloading data...")};A.onerror=function(){throw Error("NetworkError for: "+p);};A.onload=function(){if(200==A.status||304==A.status||206==A.status||0==A.status&&A.response)u(A.response);else throw Error(A.statusText+" : "+A.responseURL);};A.send(null)}}
function d(p){console.error("package error:",p)}function e(p){function r(w,B,N){this.start=w;this.end=B;this.audio=N}function u(w){if(!w)throw"Loading data file failed."+Error().stack;if(w.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;w=new Uint8Array(w);r.prototype.xe=w;w=b.files;for(var B=0;B<w.length;++B)r.prototype.ge[w[B].filename].onload();p.removeRunDependency("datafile_index.data")}r.prototype={ge:{},open:function(w,B){this.name=B;this.ge[B]=this;
p.addRunDependency(`fp ${this.name}`)},send:function(){},onload:function(){this.finish(this.xe.subarray(this.start,this.end))},finish:function(w){p.FS_createDataFile(this.name,null,w,!0,!0,!0);p.removeRunDependency(`fp ${this.name}`);this.ge[this.name]=null}};for(var y=b.files,A=0;A<y.length;++A)(new r(y[A].start,y[A].end,y[A].audio||0)).open("GET",y[A].filename);p.addRunDependency("datafile_index.data");p.tf||(p.tf={});p.tf["index.data"]={fg:!1};n?(u(n),n=null):m=u}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,
window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var f=h.locateFile?h.locateFile("index.data",
""):"index.data",g=b.remote_package_size,m=null,n=h.getPreloadedPackage?h.getPreloadedPackage(f,g):null;n||c(f,g,function(p){m?(m(p),m=null):n=p},d);h.calledRun?e(h):(h.preRun||(h.preRun=[]),h.preRun.push(e))}({files:[{filename:"/data.zip",start:0,end:61405423}],remote_package_size:61405423})})();var fa=Object.assign({},h),ha=[],ia="./this.program",ja=(a,b)=>{throw b;},ka="",la,ma;
if(ea){var fs=require("fs"),na=require("path");ka=__dirname+"/";ma=a=>{a=oa(a)?new URL(a):na.normalize(a);return fs.readFileSync(a)};la=a=>{a=oa(a)?new URL(a):na.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!h.thisProgram&&1<process.argv.length&&(ia=process.argv[1].replace(/\\/g,"/"));ha=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof pa||a.context instanceof pa))throw a;
});ja=(a,b)=>{process.exitCode=a;throw b;}}else if(ba||ca)ca?ka=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ka=document.currentScript.src),ka=ka.startsWith("blob:")?"":ka.substr(0,ka.replace(/[?#].*/,"").lastIndexOf("/")+1),ca&&(ma=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),la=a=>oa(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=
()=>{(200==d.status||0==d.status&&d.response)&&c(d.response);b(d.status)};d.onerror=b;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var qa=h.print||console.log.bind(console),k=h.printErr||console.error.bind(console);Object.assign(h,fa);fa=null;h.arguments&&(ha=h.arguments);h.thisProgram&&(ia=h.thisProgram);h.quit&&(ja=h.quit);var ra;h.wasmBinary&&(ra=h.wasmBinary);
var sa,ta=!1,ua,l,q,va,wa,t,v,x,z,xa=[],ya=[],za=[],Aa=[];function Ba(){var a=h.preRun.shift();xa.unshift(a)}var Ca=0,Da=null,Ea=null;function Fa(){Ca++;h.monitorRunDependencies?.(Ca)}function Ga(){Ca--;h.monitorRunDependencies?.(Ca);if(0==Ca&&(null!==Da&&(clearInterval(Da),Da=null),Ea)){var a=Ea;Ea=null;a()}}function Ha(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);ta=!0;ua=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}
var Ia=a=>a.startsWith("data:application/octet-stream;base64,"),oa=a=>a.startsWith("file://"),Ja;function Ka(a){if(a==Ja&&ra)return new Uint8Array(ra);if(ma)return ma(a);throw"both async and sync fetching of the wasm failed";}function La(a){return ra?Promise.resolve().then(()=>Ka(a)):la(a).then(b=>new Uint8Array(b),()=>Ka(a))}function Ma(a,b,c){return La(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{k(`failed to asynchronously prepare wasm: ${d}`);Ha(d)})}
function Na(a,b){var c=Ja;ra||"function"!=typeof WebAssembly.instantiateStreaming||Ia(c)||oa(c)||ea||"function"!=typeof fetch?Ma(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){k(`wasm streaming compile failed: ${e}`);k("falling back to ArrayBuffer instantiation");return Ma(c,a,b)}))}
var C,D,Va={300200:()=>{Oa(function(a){a&&(console.warn("Error saving:",a),alert("Error saving. Check console for more information."))})},300345:a=>{a=(a?E(q,a):"")+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");return Pa(Qa(a),"i8",Ra)},300570:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,300717:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?
!0:!1,300951:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.ie||("undefined"!==typeof AudioContext?b.ie=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.ie=new webkitAudioContext),b.ie&&Sa(b.ie));return void 0===b.ie?-1:0},301444:()=>h.SDL2.ie.sampleRate,301512:(a,b,c,d)=>{function e(){}function f(m){void 0!==g.capture.Ge&&(clearTimeout(g.capture.Ge),g.capture.Ge=void 0);g.capture.Ne=g.ie.createMediaStreamSource(m);g.capture.ke=g.ie.createScriptProcessor(b,
a,1);g.capture.ke.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.Re=n.inputBuffer,Ta(c,[d]))};g.capture.Ne.connect(g.capture.ke);g.capture.ke.connect(g.ie.destination);g.capture.stream=m}var g=h.SDL2;g.capture.Pe=g.ie.createBuffer(a,b,g.ie.sampleRate);g.capture.Pe.getChannelData(0).fill(0);g.capture.Ge=setTimeout(function(){g.capture.Re=g.capture.Pe;Ta(c,[d])},b/g.ie.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?
navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},303164:(a,b,c,d)=>{var e=h.SDL2;e.audio.ke=e.ie.createScriptProcessor(b,0,a);e.audio.ke.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.cf=f.outputBuffer,Ta(c,[d]))};e.audio.ke.connect(e.ie.destination)},303574:(a,b)=>{for(var c=h.SDL2,d=c.capture.Re.numberOfChannels,e=0;e<d;++e){var f=c.capture.Re.getChannelData(e);
if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Ua(a+4*g,f[g]);else for(g=0;g<b;++g)Ua(a+4*(g*d+e),f[g])}},304179:(a,b)=>{for(var c=h.SDL2,d=c.audio.cf.numberOfChannels,e=0;e<d;++e){var f=c.audio.cf.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=x[a+(g*d+e<<2)>>2]}},
304659:a=>{var b=h.SDL2;if(a){void 0!==b.capture.Ge&&clearTimeout(b.capture.Ge);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==b.capture.ke&&(b.capture.ke.onaudioprocess=function(){},b.capture.ke.disconnect(),b.capture.ke=void 0);void 0!==b.capture.Ne&&(b.capture.Ne.disconnect(),b.capture.Ne=void 0);void 0!==b.capture.Pe&&(b.capture.Pe=void 0);b.capture=void 0}else void 0!=b.audio.ke&&
(b.audio.ke.disconnect(),b.audio.ke=void 0),b.audio=void 0;void 0!==b.ie&&void 0===b.audio&&void 0===b.capture&&(b.ie.close(),b.ie=void 0)},305831:(a,b)=>{alert((a?E(q,a):"")+"\n\n"+(b?E(q,b):""))},305888:()=>window.innerWidth,305918:()=>window.innerHeight,305949:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.xf!==h.canvas&&(d.pe=h.createContext(h.canvas,!1,!0),d.xf=h.canvas);if(d.w!==a||d.h!==b||d.If!==d.pe)d.image=d.pe.createImageData(a,b),d.w=a,d.h=b,d.If=d.pe;a=d.image.data;b=c>>2;var e=0;if("undefined"!==
typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=t[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Af!==a&&(d.zf=new Int32Array(a.buffer),d.Bf=new Uint8Array(a.buffer),d.Af=a),a=d.zf,c=a.length,a.set(t.subarray(b,b+c)),a=d.Bf,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.pe.putImageData(d.image,
0,0)},307418:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<n;){var p=t[e];b[m]=p&255;b[m+1]=p>>8&255;b[m+2]=p>>16&255;b[m+3]=p>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(t.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+
d+", auto";d=F(c.length+1);G(c,q,d,c.length+1);return d},308407:a=>{h.canvas&&(h.canvas.style.cursor=a?E(q,a):"")},308490:()=>{h.canvas&&(h.canvas.style.cursor="none")}};function pa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Wa=a=>{for(;0<a.length;)a.shift()(h)},Xa=h.noExitRuntime||!0;
function Ua(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":l[a]=b;break;case "i8":l[a]=b;break;case "i16":va[a>>1]=b;break;case "i32":t[a>>2]=b;break;case "i64":Ha("to do setValue(i64) use WASM_BIGINT");case "float":x[a>>2]=b;break;case "double":z[a>>3]=b;break;case "*":v[a>>2]=b;break;default:Ha(`invalid type for setValue: ${c}`)}}
var Ya="undefined"!=typeof TextDecoder?new TextDecoder:void 0,E=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ya)return Ya.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Za=(a,
b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},$a=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Za(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},ab=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},bb=a=>{if("/"===a)return"/";
a=$a(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},cb=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(ea)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}Ha("initRandomDevice")},db=a=>(db=cb())(a),eb=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");
if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Za(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},fb=[],gb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},G=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=
192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function Qa(a,b){var c=Array(gb(a)+1);a=G(a,c,0,c.length);b&&(c.length=a);return c}var hb=[];function ib(a,b){hb[a]={input:[],output:[],ue:b};jb(a,kb)}
var kb={open(a){var b=hb[a.node.rdev];if(!b)throw new H(43);a.tty=b;a.seekable=!1},close(a){a.tty.ue.fsync(a.tty)},fsync(a){a.tty.ue.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.ue.hf)throw new H(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.ue.hf(a.tty)}catch(m){throw new H(29);}if(void 0===g&&0===e)throw new H(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.ue.Ue)throw new H(60);try{for(var e=0;e<d;e++)a.tty.ue.Ue(a.tty,b[c+
e])}catch(f){throw new H(29);}d&&(a.node.timestamp=Date.now());return e}},lb={hf(){a:{if(!fb.length){var a=null;if(ea){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}fb=Qa(a,!0)}a=fb.shift()}return a},Ue(a,b){null===b||10===b?(qa(E(a.output,
0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(qa(E(a.output,0)),a.output=[])},Lf(){return{Zf:25856,ag:5,Yf:191,$f:35387,Xf:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Mf(){return 0},Nf(){return[24,80]}},mb={Ue(a,b){null===b||10===b?(k(E(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(k(E(a.output,0)),a.output=[])}};
function nb(a,b){var c=a.de?a.de.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.de,a.de=new Uint8Array(b),0<a.fe&&a.de.set(c.subarray(0,a.fe),0))}
var I={se:null,re(){return I.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(63);I.se||(I.se={dir:{node:{qe:I.ce.qe,le:I.ce.le,lookup:I.ce.lookup,Oe:I.ce.Oe,rename:I.ce.rename,unlink:I.ce.unlink,rmdir:I.ce.rmdir,readdir:I.ce.readdir,symlink:I.ce.symlink},stream:{ze:I.ee.ze}},file:{node:{qe:I.ce.qe,le:I.ce.le},stream:{ze:I.ee.ze,read:I.ee.read,write:I.ee.write,Ze:I.ee.Ze,Te:I.ee.Te,qf:I.ee.qf}},link:{node:{qe:I.ce.qe,le:I.ce.le,readlink:I.ce.readlink},
stream:{}},bf:{node:{qe:I.ce.qe,le:I.ce.le},stream:ob}});c=pb(a,b,c,d);J(c.mode)?(c.ce=I.se.dir.node,c.ee=I.se.dir.stream,c.de={}):32768===(c.mode&61440)?(c.ce=I.se.file.node,c.ee=I.se.file.stream,c.fe=0,c.de=null):40960===(c.mode&61440)?(c.ce=I.se.link.node,c.ee=I.se.link.stream):8192===(c.mode&61440)&&(c.ce=I.se.bf.node,c.ee=I.se.bf.stream);c.timestamp=Date.now();a&&(a.de[b]=c,a.timestamp=c.timestamp);return c},hg(a){return a.de?a.de.subarray?a.de.subarray(0,a.fe):new Uint8Array(a.de):new Uint8Array(0)},
ce:{qe(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;J(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.fe:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.wf=4096;b.blocks=Math.ceil(b.size/b.wf);return b},le(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.fe!=b))if(0==
b)a.de=null,a.fe=0;else{var c=a.de;a.de=new Uint8Array(b);c&&a.de.set(c.subarray(0,Math.min(b,a.fe)));a.fe=b}},lookup(){throw qb[44];},Oe(a,b,c,d){return I.createNode(a,b,c,d)},rename(a,b,c){if(J(a.mode)){try{var d=rb(b,c)}catch(f){}if(d)for(var e in d.de)throw new H(55);}delete a.parent.de[a.name];a.parent.timestamp=Date.now();a.name=c;b.de[c]=a;b.timestamp=a.parent.timestamp},unlink(a,b){delete a.de[b];a.timestamp=Date.now()},rmdir(a,b){var c=rb(a,b),d;for(d in c.de)throw new H(55);delete a.de[b];
a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.de))b.push(c);return b},symlink(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new H(28);return a.link}},ee:{read(a,b,c,d,e){var f=a.node.de;if(e>=a.node.fe)return 0;a=Math.min(a.node.fe-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.de||a.de.subarray)){if(f)return a.de=
b.subarray(c,c+d),a.fe=d;if(0===a.fe&&0===e)return a.de=b.slice(c,c+d),a.fe=d;if(e+d<=a.fe)return a.de.set(b.subarray(c,c+d),e),d}nb(a,e+d);if(a.de.subarray&&b.subarray)a.de.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.de[e+f]=b[c+f];a.fe=Math.max(a.fe,e+d);return d},ze(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.fe);if(0>b)throw new H(28);return b},Ze(a,b,c){nb(a.node,b+c);a.node.fe=Math.max(a.node.fe,b+c)},Te(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new H(43);
a=a.node.de;if(e&2||a.buffer!==l.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;Ha();b=void 0;if(!b)throw new H(48);l.set(a,b)}else c=!1,b=a.byteOffset;return{og:b,Vf:c}},qf(a,b,c,d){I.ee.write(a,b,0,d,c,!1);return 0}}},sb=(a,b,c)=>{var d=`al ${a}`;la(a).then(e=>{b(new Uint8Array(e));d&&Ga(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&Fa(d)},tb=h.preloadPlugins||[],wb=(a,b,c,d)=>{"undefined"!=typeof ub&&vb();var e=!1;tb.forEach(f=>
{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},yb=(a,b,c,d,e,f,g,m,n,p)=>{function r(A){function w(B){p?.();m||xb(a,b,B,d,e,n);f?.();Ga(y)}wb(A,u,w,()=>{g?.();Ga(y)})||w(A)}var u=b?eb($a(a+"/"+b)):a,y=`cp ${u}`;Fa(y);"string"==typeof c?sb(c,r,g):r(c)},zb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Ab=null,Bb={},Cb=[],Db=1,Eb=null,Fb=!0,H=class{constructor(a){this.name="ErrnoError";this.he=a}},qb={},Gb=0,Hb=class{constructor(){this.ge={};this.node=null}get flags(){return this.ge.flags}set flags(a){this.ge.flags=
a}get position(){return this.ge.position}set position(a){this.ge.position=a}},Ib=class{constructor(a,b,c,d){a||=this;this.parent=a;this.re=a.re;this.Ce=null;this.id=Db++;this.name=b;this.mode=c;this.ce={};this.ee={};this.rdev=d}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Pf(){return J(this.mode)}get Of(){return 8192===(this.mode&61440)}};
function K(a,b={}){a=eb(a);if(!a)return{path:"",node:null};b=Object.assign({ff:!0,Ve:0},b);if(8<b.Ve)throw new H(32);a=a.split("/").filter(g=>!!g);for(var c=Ab,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=rb(c,a[e]);d=$a(d+"/"+a[e]);c.Ce&&(!f||f&&b.ff)&&(c=c.Ce.root);if(!f||b.Be)for(f=0;40960===(c.mode&61440);)if(c=Jb(d),d=eb(ab(d),c),c=K(d,{Ve:b.Ve+1}).node,40<f++)throw new H(32);}return{path:d,node:c}}
function Kb(a){for(var b;;){if(a===a.parent)return a=a.re.nf,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Lb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Eb.length}function Mb(a){var b=Lb(a.parent.id,a.name);if(Eb[b]===a)Eb[b]=a.De;else for(b=Eb[b];b;){if(b.De===a){b.De=a.De;break}b=b.De}}
function rb(a,b){var c=J(a.mode)?(c=Nb(a,"x"))?c:a.ce.lookup?0:2:54;if(c)throw new H(c);for(c=Eb[Lb(a.id,b)];c;c=c.De){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ce.lookup(a,b)}function pb(a,b,c,d){a=new Ib(a,b,c,d);b=Lb(a.parent.id,a.name);a.De=Eb[b];return Eb[b]=a}function J(a){return 16384===(a&61440)}function Ob(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Nb(a,b){if(Fb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Pb(a,b){try{return rb(a,b),20}catch(c){}return Nb(a,"wx")}function Qb(a,b,c){try{var d=rb(a,b)}catch(e){return e.he}if(a=Nb(a,"wx"))return a;if(c){if(!J(d.mode))return 54;if(d===d.parent||"/"===Kb(d))return 10}else if(J(d.mode))return 31;return 0}function L(a){a=Cb[a];if(!a)throw new H(8);return a}
function Rb(a,b=-1){a=Object.assign(new Hb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!Cb[b])break a;throw new H(33);}a.fd=b;return Cb[b]=a}function Sb(a,b=-1){a=Rb(a,b);a.ee?.dg?.(a);return a}var ob={open(a){a.ee=Bb[a.node.rdev].ee;a.ee.open?.(a)},ze(){throw new H(70);}};function jb(a,b){Bb[a]={ee:b}}function Tb(){for(var a=[],b=[Ab.re];b.length;){var c=b.pop();a.push(c);b.push(...c.pf)}return a}
function Oa(a){function b(g){Gb--;return a(g)}function c(g){if(g){if(!c.Ef)return c.Ef=!0,b(g)}else++f>=e.length&&b(null)}var d=!1;"function"==typeof d&&(a=d,d=!1);Gb++;1<Gb&&k(`warning: ${Gb} FS.syncfs operations in flight at once, probably just doing extra work`);var e=Tb(),f=0;e.forEach(g=>{if(!g.type.Rf)return c(null);g.type.Rf(g,d,c)})}
function Ub(a,b){var c="/"===b;if(c&&Ab)throw new H(10);if(!c&&b){var d=K(b,{ff:!1});b=d.path;d=d.node;if(d.Ce)throw new H(10);if(!J(d.mode))throw new H(54);}b={type:a,ng:{},nf:b,pf:[]};a=a.re(b);a.re=b;b.root=a;c?Ab=a:d&&(d.Ce=b,d.re&&d.re.pf.push(b))}function Vb(a,b,c){var d=K(a,{parent:!0}).node;a=bb(a);if(!a||"."===a||".."===a)throw new H(28);var e=Pb(d,a);if(e)throw new H(e);if(!d.ce.Oe)throw new H(63);return d.ce.Oe(d,a,b,c)}function Wb(a,b){return Vb(a,(void 0!==b?b:511)&1023|16384,0)}
function Xb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Vb(a,b|8192,c)}function Yb(a,b){if(!eb(a))throw new H(44);var c=K(b,{parent:!0}).node;if(!c)throw new H(44);b=bb(b);var d=Pb(c,b);if(d)throw new H(d);if(!c.ce.symlink)throw new H(63);c.ce.symlink(c,b,a)}function Zb(a){var b=K(a,{parent:!0}).node;a=bb(a);var c=rb(b,a),d=Qb(b,a,!0);if(d)throw new H(d);if(!b.ce.rmdir)throw new H(63);if(c.Ce)throw new H(10);b.ce.rmdir(b,a);Mb(c)}
function $b(a){var b=K(a,{parent:!0}).node;if(!b)throw new H(44);a=bb(a);var c=rb(b,a),d=Qb(b,a,!1);if(d)throw new H(d);if(!b.ce.unlink)throw new H(63);if(c.Ce)throw new H(10);b.ce.unlink(b,a);Mb(c)}function Jb(a){a=K(a).node;if(!a)throw new H(44);if(!a.ce.readlink)throw new H(28);return eb(Kb(a.parent),a.ce.readlink(a))}function ac(a,b){a=K(a,{Be:!b}).node;if(!a)throw new H(44);if(!a.ce.qe)throw new H(63);return a.ce.qe(a)}function bc(a){return ac(a,!0)}
function cc(a,b){a="string"==typeof a?K(a,{Be:!0}).node:a;if(!a.ce.le)throw new H(63);a.ce.le(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function dc(a,b,c){if(""===a)throw new H(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=$a(a);try{e=K(a,{Be:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new H(20);}else e=Vb(a,c,0),d=!0;if(!e)throw new H(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!J(e.mode))throw new H(54);if(!d&&(c=
e?40960===(e.mode&61440)?32:J(e.mode)&&("r"!==Ob(b)||b&512)?31:Nb(e,Ob(b)):44))throw new H(c);if(b&512&&!d){c=e;c="string"==typeof c?K(c,{Be:!0}).node:c;if(!c.ce.le)throw new H(63);if(J(c.mode))throw new H(31);if(32768!==(c.mode&61440))throw new H(28);if(d=Nb(c,"w"))throw new H(d);c.ce.le(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Rb({node:e,path:Kb(e),flags:b,seekable:!0,position:0,ee:e.ee,Sf:[],error:!1});e.ee.open&&e.ee.open(e);!h.logReadFiles||b&1||(ec||={},a in ec||(ec[a]=1));return e}
function gc(a){if(null===a.fd)throw new H(8);a.ye&&(a.ye=null);try{a.ee.close&&a.ee.close(a)}catch(b){throw b;}finally{Cb[a.fd]=null}a.fd=null}function hc(a,b,c){if(null===a.fd)throw new H(8);if(!a.seekable||!a.ee.ze)throw new H(70);if(0!=c&&1!=c&&2!=c)throw new H(28);a.position=a.ee.ze(a,b,c);a.Sf=[];return a.position}
function ic(a,b,c,d,e,f){if(0>d||0>e)throw new H(28);if(null===a.fd)throw new H(8);if(0===(a.flags&2097155))throw new H(8);if(J(a.node.mode))throw new H(31);if(!a.ee.write)throw new H(28);a.seekable&&a.flags&1024&&hc(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new H(70);b=a.ee.write(a,b,c,d,e,f);g||(a.position+=b);return b}var jc;
function kc(a,b){a="string"==typeof a?a:Kb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=$a(a+"/"+c);try{Wb(d)}catch(e){}a=d}}return d}function lc(a,b,c,d){a=$a(("string"==typeof a?a:Kb(a))+"/"+b);c=zb(c,d);return Vb(a,(void 0!==c?c:438)&4095|32768,0)}
function xb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Kb(a),g=b?$a(a+"/"+b):a);a=zb(d,e);g=Vb(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}cc(g,a|146);b=dc(g,577);ic(b,c,0,c.length,0,f);gc(b);cc(g,a)}}
function mc(a,b,c,d){a=$a(("string"==typeof a?a:Kb(a))+"/"+b);b=zb(!!c,!!d);mc.lf||(mc.lf=64);var e=mc.lf++<<8|0;jb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,m,n){for(var p=0,r=0;r<n;r++){try{var u=c()}catch(y){throw new H(29);}if(void 0===u&&0===p)throw new H(6);if(null===u||void 0===u)break;p++;g[m+r]=u}p&&(f.node.timestamp=Date.now());return p},write(f,g,m,n){for(var p=0;p<n;p++)try{d(g[m+p])}catch(r){throw new H(29);}n&&(f.node.timestamp=Date.now());return p}});return Xb(a,
b,e)}function nc(a){if(!(a.Of||a.Pf||a.link||a.de)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.de=ma(a.url),a.fe=a.de.length}catch(b){throw new H(29);}}}
function oc(a,b,c,d,e){class f{constructor(){this.Fe=!1;this.ge=[];this.xe=void 0;this.ef=this.gf=0}get(r){if(!(r>this.length-1||0>r)){var u=r%this.chunkSize;return this.xe(r/this.chunkSize|0)[u]}}Hf(r){this.xe=r}jf(){var r=new XMLHttpRequest;r.open("HEAD",c,!1);r.send(null);if(!(200<=r.status&&300>r.status||304===r.status))throw Error("Couldn't load "+c+". Status: "+r.status);var u=Number(r.getResponseHeader("Content-length")),y,A=(y=r.getResponseHeader("Accept-Ranges"))&&"bytes"===y;r=(y=r.getResponseHeader("Content-Encoding"))&&
"gzip"===y;var w=1048576;A||(w=u);var B=this;B.Hf(N=>{var da=N*w,aa=(N+1)*w-1;aa=Math.min(aa,u-1);if("undefined"==typeof B.ge[N]){var fc=B.ge;if(da>aa)throw Error("invalid range ("+da+", "+aa+") or no bytes requested!");if(aa>u-1)throw Error("only "+u+" bytes available! programmer error!");var Q=new XMLHttpRequest;Q.open("GET",c,!1);u!==w&&Q.setRequestHeader("Range","bytes="+da+"-"+aa);Q.responseType="arraybuffer";Q.overrideMimeType&&Q.overrideMimeType("text/plain; charset=x-user-defined");Q.send(null);
if(!(200<=Q.status&&300>Q.status||304===Q.status))throw Error("Couldn't load "+c+". Status: "+Q.status);da=void 0!==Q.response?new Uint8Array(Q.response||[]):Qa(Q.responseText||"",!0);fc[N]=da}if("undefined"==typeof B.ge[N])throw Error("doXHR failed!");return B.ge[N]});if(r||!u)w=u=1,w=u=this.xe(0).length,qa("LazyFiles on gzip forces download of the whole file when length is accessed");this.gf=u;this.ef=w;this.Fe=!0}get length(){this.Fe||this.jf();return this.gf}get chunkSize(){this.Fe||this.jf();
return this.ef}}if("undefined"!=typeof XMLHttpRequest){if(!ca)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var g=new f;var m=void 0}else m=c,g=void 0;var n=lc(a,b,d,e);g?n.de=g:m&&(n.de=null,n.url=m);Object.defineProperties(n,{fe:{get:function(){return this.de.length}}});var p={};Object.keys(n.ee).forEach(r=>{var u=n.ee[r];p[r]=(...y)=>{nc(n);return u(...y)}});p.read=(r,u,y,A,w)=>{nc(n);r=r.node.de;if(w>=r.length)u=0;else{A=
Math.min(r.length-w,A);if(r.slice)for(var B=0;B<A;B++)u[y+B]=r[w+B];else for(B=0;B<A;B++)u[y+B]=r.get(w+B);u=A}return u};p.Te=()=>{nc(n);Ha();throw new H(48);};n.ee=p;return n}var M={},ec;function pc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":L(a).path;if(0==b.length){if(!c)throw new H(44);return a}return $a(a+"/"+b)}
function qc(a,b,c){a=a(b);t[c>>2]=a.dev;t[c+4>>2]=a.mode;v[c+8>>2]=a.nlink;t[c+12>>2]=a.uid;t[c+16>>2]=a.gid;t[c+20>>2]=a.rdev;D=[a.size>>>0,(C=a.size,1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];t[c+24>>2]=D[0];t[c+28>>2]=D[1];t[c+32>>2]=4096;t[c+36>>2]=a.blocks;b=a.atime.getTime();var d=a.mtime.getTime(),e=a.ctime.getTime();D=[Math.floor(b/1E3)>>>0,(C=Math.floor(b/1E3),1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>
0))/4294967296)>>>0:0)];t[c+40>>2]=D[0];t[c+44>>2]=D[1];v[c+48>>2]=b%1E3*1E3;D=[Math.floor(d/1E3)>>>0,(C=Math.floor(d/1E3),1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];t[c+56>>2]=D[0];t[c+60>>2]=D[1];v[c+64>>2]=d%1E3*1E3;D=[Math.floor(e/1E3)>>>0,(C=Math.floor(e/1E3),1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];t[c+72>>2]=D[0];t[c+76>>2]=D[1];v[c+80>>2]=e%1E3*1E3;D=[a.ino>>>0,(C=a.ino,1<=+Math.abs(C)?
0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];t[c+88>>2]=D[0];t[c+92>>2]=D[1];return 0}var rc=void 0;function sc(){var a=t[+rc>>2];rc+=4;return a}
var tc=a=>0===a%4&&(0!==a%100||0===a%400),uc=[0,31,60,91,121,152,182,213,244,274,305,335],vc=[0,31,59,90,120,151,181,212,243,273,304,334],Gc=(a,b)=>{wc=a;xc=b;if(yc)if(zc||=!0,0==a)Ac=function(){var d=Math.max(0,Bc+b-Cc())|0;setTimeout(Dc,d)};else if(1==a)Ac=function(){Ec(Dc)};else if(2==a){if("undefined"==typeof Fc)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Fc=function(d){c.push(d);
if(ca){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Fc=setImmediate;Ac=function(){Fc(Dc)}}},Cc;Cc=()=>performance.now();
var Pc=(a,b,c,d,e)=>{yc=a;Hc=d;var f=Ic;zc=!1;Dc=function(){if(!ta)if(0<Jc.length){var g=Jc.shift();g.gg(g.Wf);if(Kc){var m=Kc,n=0==m%1?m-1:Math.floor(m);Kc=g.cg?n:(8*m+(n+.5))/9}h.setStatus&&(g=h.statusMessage||"Please wait...",m=Kc,n=Lc.eg,m?m<n?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(g):h.setStatus(""));f<Ic||setTimeout(Dc,0)}else if(!(f<Ic))if(Mc=Mc+1|0,1==wc&&1<xc&&0!=Mc%xc)Ac();else{0==wc&&(Bc=Cc());if(!(ta||h.preMainLoop&&!1===h.preMainLoop())){if(!ta)try{a(),
Nc()}catch(p){Oc(p)}h.postMainLoop?.()}f<Ic||("object"==typeof SDL&&SDL.audio?.pg?.(),Ac())}};e||(b&&0<b?Gc(0,1E3/b):Gc(1,1),Ac());if(c)throw"unwind";},Oc=a=>{a instanceof pa||"unwind"==a||ja(1,a)},Qc=0,Rc=a=>{ua=a;Xa||0<Qc||(h.onExit?.(a),ta=!0);ja(a,new pa(a))},Sc=a=>{ua=a;Rc(a)},Nc=()=>{if(!(Xa||0<Qc))try{var a=ua;ua=a;Rc(a)}catch(b){Oc(b)}},Tc=a=>{setTimeout(()=>{if(!ta)try{a(),Nc()}catch(b){Oc(b)}},1E4)},zc=!1,Ac=null,Ic=0,yc=null,Hc=0,wc=0,xc=0,Mc=0,Jc=[];function Uc(){Ac=null;Ic++}
var Lc={},Bc,Dc,Kc,Vc=!1,Wc=!1,Xc=[];
function vb(){function a(){Wc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!Yc){Yc=!0;tb.push({canHandle:function(c){return!h.mg&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:Zc(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Zc(d)}));var m=URL.createObjectURL(g),n=new Image;n.onload=()=>{var p=document.createElement("canvas");
p.width=n.width;p.height=n.height;p.getContext("2d").drawImage(n,0,0);URL.revokeObjectURL(m);e?.(c)};n.onerror=()=>{k(`Image ${m} could not be decoded`);f?.()};n.src=m}});tb.push({canHandle:function(c){return!h.lg&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e?.(c))}var g=!1,m=URL.createObjectURL(new Blob([c],{type:Zc(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=function(){if(!g){k(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var p="",r=0,u=0,y=0;y<c.length;y++)for(r=r<<8|c[y],u+=8;6<=u;){var A=r>>u-6&63;u-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[A]}2==u?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&3)<<4],p+="=="):4==u&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&15)<<2],p+="=");n.src="data:audio/x-"+d.substr(-3)+";base64,"+p;f(n)}};n.src=m;Tc(()=>{f(n)})}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!Wc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var $c=!1,ad=void 0,bd=void 0;function cd(){if(!Vc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var dd=0;
function Ec(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===dd)dd=b+1E3/60;else for(;b+2>=dd;)dd+=1E3/60;setTimeout(a,Math.max(dd-b,0))}}function Zc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var ed=[];function fd(){var a=h.canvas;ed.forEach(b=>b(a.width,a.height))}
function gd(a,b,c){b&&c?(a.Uf=b,a.Gf=c):(b=a.Uf,c=a.Gf);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}bd?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var ub={},Fc,Yc,O=12288,hd=!1,jd=0,kd=0,ld=0,P={alpha:!1,depth:!1,stencil:!1,antialias:!1},md={},nd,od=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},pd=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},qd=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},rd=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},sd=1,td=[],R=[],ud=[],vd=[],wd=[],S=[],xd=[],yd=[],zd=[],Ad={},Bd=4,Cd=0,Dd=a=>{for(var b=sd++,c=a.length;c<b;c++)a[c]=null;return b},Ed=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=T[c](),g=f&&Dd(d);f?(f.name=g,d[g]=f):U||=1282;t[b+4*e>>2]=g}},Gd=(a,b)=>{a.ge||(a.ge=a.getContext,a.getContext=function(d,e){e=a.ge(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Fd(c,b):0},Fd=(a,b)=>
{var c=Dd(yd),d={handle:c,attributes:b,version:b.mf,ve:a};a.canvas&&(a.canvas.Ee=d);yd[c]=d;("undefined"==typeof b.Df||b.Df)&&Hd(d);return c},Jd=a=>{Id=yd[a];h.pe=T=Id?.ve},Hd=a=>{a||=Id;if(!a.Jf){a.Jf=!0;var b=a.ve;od(b);pd(b);qd(b);b.te=b.getExtension("EXT_disjoint_timer_query");b.kg=b.getExtension("WEBGL_multi_draw");rd(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},Kd={},U,Id,Ld=a=>{var b=gb(a)+1,c=F(b);c&&G(a,q,c,b);return c},Md=[],Nd=(a,b)=>{Md.length=
0;for(var c;c=q[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Md.push(112==c?v[b>>2]:105==c?t[b>>2]:z[b>>3]);b+=d?8:4}return Md},Od=0,Pd=[];function Qd(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var m in f)if(f[m]!=g[m])return!1;return!0}for(var e of Pd)if(e.Xe==a&&d(e.$e,c))return;Pd.push({Xe:a,sf:b,$e:c});Pd.sort((f,g)=>f.sf<g.sf)}function Rd(a){Pd=Pd.filter(b=>b.Xe!=a)}function Sd(){return navigator.userActivation?navigator.userActivation.isActive:Od&&Td.Ie}
function Ud(){if(Sd()){var a=Pd;Pd=[];for(var b of a)b.Xe(...b.$e)}}var Vd=[];function Wd(a){var b=Vd[a];b.target.removeEventListener(b.je,b.df,b.me);Vd.splice(a,1)}function Xd(a){if(!a.target)return-4;if(a.ne)a.df=function(c){++Od;Td=a;Ud();a.oe(c);Ud();--Od},a.target.addEventListener(a.je,a.df,a.me),Vd.push(a);else for(var b=0;b<Vd.length;++b)Vd[b].target==a.target&&Vd[b].je==a.je&&Wd(b--);return 0}function Yd(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
function Zd(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var $d={},Td,ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me={},ne=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],V=a=>{a=2<a?a?E(q,a):"":a;return ne[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},pe=a=>{var b=gb(a)+1,c=oe(b);G(a,q,c,b);return c},se=a=>{var b=qe(),c=oe(8),d=c+4;a=pe(a.id);if(a=V(a))t[c>>2]=a.width,t[d>>2]=a.height;c=[t[c>>2],t[d>>2]];re(b);return c},te=(a,b,c)=>{a=V(a);if(!a)return-4;a.width=b;a.height=c;return 0},ue=(a,b,c)=>{if(a.bg){var d=
qe();a=pe(a.id);te(a,b,c);re(d)}else a.width=b,a.height=c},ve=[],we,W=a=>{var b=ve[a];b||(a>=ve.length&&(ve.length=a+1),ve[a]=b=we.get(a));return b},xe=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),ue(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=
p,a.style.paddingRight=r,a.style.paddingTop=u,a.style.paddingBottom=y,a.style.marginLeft=A,a.style.marginRight=w,a.style.marginTop=B,a.style.marginBottom=N,document.body.style.margin=da,document.documentElement.style.overflow=aa,document.body.scroll=fc,a.style.we=Q,a.Ee&&a.Ee.ve.viewport(0,0,d,e),me.Je&&W(me.Je)(37,0,me.af))}var c=se(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,p=a.style.paddingLeft,r=a.style.paddingRight,u=a.style.paddingTop,
y=a.style.paddingBottom,A=a.style.marginLeft,w=a.style.marginRight,B=a.style.marginTop,N=a.style.marginBottom,da=document.body.style.margin,aa=document.documentElement.style.overflow,fc=document.body.scroll,Q=a.style.we;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},ye=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},ze=a=>0>ne.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Ae=(a,
b)=>{if(0!=b.We||0!=b.Qe){xe(a);var c=b.Qf?innerWidth:screen.width,d=b.Qf?innerHeight:screen.height,e=ze(a),f=e.width;e=e.height;var g=se(a),m=g[0];g=g[1];3==b.We?(ye(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.We&&(c*g<m*d?(f=g*c/m,ye(a,(d-f)/2,0),d=f):(f=m*d/g,ye(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Ff&&(a.style.we="optimizeSpeed",a.style.we=
"-moz-crisp-edges",a.style.we="-o-crisp-edges",a.style.we="-webkit-optimize-contrast",a.style.we="optimize-contrast",a.style.we="crisp-edges",a.style.we="pixelated");f=2==b.Qe?devicePixelRatio:1;0!=b.Qe&&(c=c*f|0,d=d*f|0,ue(a,c,d),a.Ee&&a.Ee.ve.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Zd()?-3:-1;me=b;b.Je&&W(b.Je)(37,0,b.af);return 0},Be=a=>{if(a.requestPointerLock)a.requestPointerLock();
else return document.body.requestPointerLock?-3:-1;return 0},Ce=(a,b)=>{z[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)z[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)z[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)l[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];l[a+1104]=b.connected;t[a+1108>>2]=b.index;t[a+8>>2]=b.axes.length;t[a+12>>2]=b.buttons.length;G(b.id,q,a+1112,64);G(b.mapping,q,a+1176,
64)},De=[],Ee=(a,b,c,d,e,f,g,m)=>{b=R[b];if(a=T[a](b,c))d=m&&G(a.name,q,m,d),e&&(t[e>>2]=d),f&&(t[f>>2]=a.size),g&&(t[g>>2]=a.type)},Fe=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(U||=1280);return;case 36345:d=0;break;case 34466:var e=T.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=T.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":U||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=
0;break;default:U||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:t[b+4*a>>2]=e[a];break;case 2:x[b+4*a>>2]=e[a];break;case 4:l[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){U||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:U||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:c=d;v[b>>2]=c;v[b+4>>2]=(c-v[b>>2])/4294967296;break;case 0:t[b>>2]=d;break;case 2:x[b>>2]=d;break;case 4:l[b]=d?1:0}}else U||=1281},Ge=(a,b,c)=>{if(c){a=T.te.getQueryObjectEXT(zd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d;v[c+4>>2]=(d-v[c>>2])/4294967296}else U||=1281},He=(a,b,c)=>{if(c){a=T.te.getQueryObjectEXT(zd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;t[c>>2]=d}else U||=1281};function Ie(){var a=rd(T);return a=a.concat(a.map(b=>"GL_"+b))}
var Je=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Ke=a=>{var b=a.He,c=a.vf,d;if(!b)for(a.He=b={},a.uf={},d=0;d<T.getProgramParameter(a,35718);++d){var e=T.getActiveUniform(a,d);var f=e.name;e=e.size;var g=Je(f);g=0<g?f.slice(0,g):f;var m=a.Ye;a.Ye+=e;c[g]=[e,m];for(f=0;f<e;++f)b[m]=f,a.uf[m++]=g}},X=a=>{var b=T.yf;if(b){var c=b.He[a];"number"==typeof c&&(b.He[a]=c=T.getUniformLocation(b,b.uf[a]+(0<c?`[${c}]`:"")));return c}U||=1282},Le=(a,b,c,d)=>{if(c)if(a=R[a],Ke(a),a=T.getUniform(a,X(b)),"number"==
typeof a||"boolean"==typeof a)switch(d){case 0:t[c>>2]=a;break;case 2:x[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:t[c+4*b>>2]=a[b];break;case 2:x[c+4*b>>2]=a[b]}else U||=1281},Me=(a,b,c,d)=>{if(c)if(a=T.getVertexAttrib(a,b),34975==b)t[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:t[c>>2]=a;break;case 2:x[c>>2]=a;break;case 5:t[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:t[c+4*b>>2]=a[b];break;case 2:x[c+4*b>>2]=a[b];break;case 5:t[c+
4*b>>2]=Math.fround(a[b])}else U||=1281},Ne=(a,b,c,d,e)=>{a-=5120;a=1==a?q:4==a?t:6==a?x:5==a||28922==a?v:wa;b=d*((Cd||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Bd-1&-Bd);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Oe=[],Pe=[],Qe=(a,b)=>{if(!Zd())return-1;a=V(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Sd()?Ae(a,b):b.Cf?(Qd(Ae,1,[a,b]),1):-2:-3:-4},Re=()=>{try{if(navigator.getGamepads)return(ae=navigator.getGamepads())?
0:-1}catch(a){navigator.getGamepads=null}return-1},Se=(a,b)=>{var c={target:V(2),je:"beforeunload",ne:b,oe:(d=event)=>{var e=W(b)(28,0,a);e&&=e?E(q,e):"";if(e)return d.preventDefault(),d.returnValue=e},me:!0};return Xd(c)},Te=(a,b,c,d,e,f)=>{be||=F(256);a={target:V(a),je:f,ne:d,oe:(g=event)=>{var m=g.target.id?g.target.id:"",n=be;G(Yd(g.target),q,n+0,128);G(m,q,n+128,128);W(d)(e,n,b)&&g.preventDefault()},me:c};return Xd(a)},Ue=(a,b,c,d,e)=>{de||=F(276);return Xd({target:a,je:e,ne:d,oe:(f=event)=>
{var g=de,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;l[g]=n;l[g+1]=Zd();var p=n?m:ce,r=p?.id||"";G(Yd(p),q,g+2,128);G(r,q,g+130,128);t[g+260>>2]=p?p.clientWidth:0;t[g+264>>2]=p?p.clientHeight:0;t[g+268>>2]=screen.width;t[g+272>>2]=screen.height;n&&(ce=m);W(d)(19,g,b)&&f.preventDefault()},me:c})},Ve=(a,b,c,d,e)=>{ee||=F(1240);b={target:V(2),Ie:!0,je:e,ne:c,oe:(f=event)=>{var g=ee;Ce(g,f.gamepad);W(c)(d,g,a)&&f.preventDefault()},
me:b};return Xd(b)},We=(a,b,c,d,e,f)=>{fe||=F(160);a={target:V(a),je:f,ne:d,oe:g=>{var m=fe;z[m>>3]=g.timeStamp;var n=m>>2;t[n+2]=g.location;l[m+12]=g.ctrlKey;l[m+13]=g.shiftKey;l[m+14]=g.altKey;l[m+15]=g.metaKey;l[m+16]=g.repeat;t[n+5]=g.charCode;t[n+6]=g.keyCode;t[n+7]=g.which;G(g.key||"",q,m+32,32);G(g.code||"",q,m+64,32);G(g.char||"",q,m+96,32);G(g.locale||"",q,m+128,32);W(d)(e,m,b)&&g.preventDefault()},me:c};return Xd(a)},Xe=(a,b,c)=>{z[a>>3]=b.timeStamp;var d=a>>2;t[d+2]=b.screenX;t[d+3]=b.screenY;
t[d+4]=b.clientX;t[d+5]=b.clientY;l[a+24]=b.ctrlKey;l[a+25]=b.shiftKey;l[a+26]=b.altKey;l[a+27]=b.metaKey;va[2*d+14]=b.button;va[2*d+15]=b.buttons;t[d+8]=b.movementX;t[d+9]=b.movementY;a=ze(c);t[d+10]=b.clientX-(a.left|0);t[d+11]=b.clientY-(a.top|0)},Ye=(a,b,c,d,e,f)=>{ge||=F(64);a=V(a);return Xd({target:a,Ie:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,je:f,ne:d,oe:(g=event)=>{Xe(ge,g,a);W(d)(e,ge,b)&&g.preventDefault()},me:c})},Ze=(a,b,c,d,e)=>{he||=F(257);return Xd({target:a,je:e,ne:d,oe:(f=
event)=>{var g=he,m=document.pointerLockElement||document.ge||document.Fe||document.xe;l[g]=!!m;var n=m?.id||"";G(Yd(m),q,g+1,128);G(n,q,g+129,128);W(d)(20,g,b)&&f.preventDefault()},me:c})},$e=(a,b,c,d)=>{ie||=F(36);a=V(a);return Xd({target:a,je:"resize",ne:d,oe:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=ie;t[g>>2]=0;t[g+4>>2]=f.clientWidth;t[g+8>>2]=f.clientHeight;t[g+12>>2]=innerWidth;t[g+16>>2]=innerHeight;t[g+20>>2]=outerWidth;t[g+24>>2]=outerHeight;t[g+28>>2]=pageXOffset|0;t[g+
32>>2]=pageYOffset|0;W(d)(10,g,b)&&e.preventDefault()}}},me:c})},af=(a,b,c,d,e,f)=>{je||=F(1552);a=V(a);return Xd({target:a,Ie:"touchstart"==f||"touchend"==f,je:f,ne:d,oe:g=>{var m={},n=g.touches;for(var p of n)p.kf=p.rf=0,m[p.identifier]=p;for(var r of g.changedTouches)r.kf=1,m[r.identifier]=r;for(var u of g.targetTouches)m[u.identifier].rf=1;n=je;z[n>>3]=g.timeStamp;l[n+12]=g.ctrlKey;l[n+13]=g.shiftKey;l[n+14]=g.altKey;l[n+15]=g.metaKey;p=n+16;r=ze(a);u=0;for(let y of Object.values(m))if(m=p>>2,
t[m]=y.identifier,t[m+1]=y.screenX,t[m+2]=y.screenY,t[m+3]=y.clientX,t[m+4]=y.clientY,t[m+5]=y.pageX,t[m+6]=y.pageY,l[p+28]=y.kf,l[p+29]=y.rf,t[m+8]=y.clientX-(r.left|0),t[m+9]=y.clientY-(r.top|0),p+=48,31<++u)break;t[n+8>>2]=u;W(d)(e,n,b)&&g.preventDefault()},me:c})},bf=(a,b,c)=>{var d=ne[1];ke||=F(8);return Xd({target:d,je:"visibilitychange",ne:c,oe:(e=event)=>{var f=ke,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);l[f]=document.hidden;t[f+4>>2]=g;W(c)(21,f,a)&&
e.preventDefault()},me:b})},cf=(a,b,c,d)=>{le||=F(96);return Xd({target:a,Ie:!0,je:"wheel",ne:d,oe:(e=event)=>{var f=le;Xe(f,e,a);z[f+64>>3]=e.deltaX;z[f+72>>3]=e.deltaY;z[f+80>>3]=e.deltaZ;t[f+88>>2]=e.deltaMode;W(d)(9,f,b)&&e.preventDefault()},me:c})},df={},ff=()=>{if(!ef){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ia||"./this.program"},b;for(b in df)void 0===
df[b]?delete a[b]:a[b]=df[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);ef=c}return ef},ef,gf=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Sa=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&gf(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Ta=(a,b=[])=>{if("vi".includes("j")){var c="vi".replace(/p/g,"i");(0,h["dynCall_"+c])(a,...b)}else W(a)(...b)},Ra=0,Pa=(a,b)=>{b=1==b?oe(a.length):F(a.length);a.subarray||a.slice||(a=
new Uint8Array(a));q.set(a,b);return b};[44].forEach(a=>{qb[a]=new H(a);qb[a].stack="<generic error, no stack>"});Eb=Array(4096);Ub(I,"/");Wb("/tmp");Wb("/home");Wb("/home/web_user");(function(){Wb("/dev");jb(259,{read:()=>0,write:(d,e,f,g)=>g});Xb("/dev/null",259);ib(1280,lb);ib(1536,mb);Xb("/dev/tty",1280);Xb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=db(a).byteLength);return a[--b]};mc("/dev","random",c);mc("/dev","urandom",c);Wb("/dev/shm");Wb("/dev/shm/tmp")})();
(function(){Wb("/proc");var a=Wb("/proc/self");Wb("/proc/self/fd");Ub({re(){var b=pb(a,"fd",16895,73);b.ce={lookup(c,d){var e=L(+d);c={parent:null,re:{nf:"fake"},ce:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=kc;h.FS_createDataFile=xb;h.FS_createPreloadedFile=yb;h.FS_unlink=$b;h.FS_createLazyFile=oc;h.FS_createDevice=mc;
h.requestFullscreen=function(a,b){function c(){Vc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=cd,ad&&d.requestPointerLock(),Vc=!0,bd?("undefined"!=typeof SDL&&(t[SDL.screen>>2]=v[SDL.screen>>2]|8388608),gd(h.canvas),fd()):gd(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),bd?("undefined"!=typeof SDL&&(t[SDL.screen>>2]=
v[SDL.screen>>2]&-8388609),gd(h.canvas),fd()):gd(d));h.onFullScreen?.(Vc);h.onFullscreen?.(Vc)}ad=a;bd=b;"undefined"==typeof ad&&(ad=!0);"undefined"==typeof bd&&(bd=!1);var d=h.canvas;$c||($c=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.requestAnimationFrame=Ec;h.setCanvasSize=function(a,b,c){gd(h.canvas,a,b);c||fd()};h.pauseMainLoop=Uc;h.resumeMainLoop=function(){Ic++;var a=wc,b=xc,c=yc;yc=null;Pc(c,0,!1,Hc,!0);Gc(a,b);Ac()};
h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};h.createContext=function(a,b,c,d){if(b&&h.pe&&a==h.canvas)return h.pe;var e;if(b){var f={antialias:!1,alpha:!1,mf:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof Kd&&(e=Gd(a,f)))var m=yd[e].ve}else m=a.getContext("2d");if(!m)return null;c&&(h.pe=m,b&&Jd(e),h.Tf=b,Xc.forEach(n=>n()),vb());return m};for(var T,Y=0;32>Y;++Y)De.push(Array(Y));
var hf=new Float32Array(288);for(Y=0;288>=Y;++Y)Oe[Y]=hf.subarray(0,Y);var jf=new Int32Array(288);for(Y=0;288>=Y;++Y)Pe[Y]=jf.subarray(0,Y);
var lf={a:(a,b,c,d)=>{Ha(`Assertion failed: ${a?E(q,a):""}, at: `+[b?b?E(q,b):"":"unknown filename",c,d?d?E(q,d):"":"unknown function"])},lb:function(a,b,c){try{b=b?E(q,b):"";b=pc(a,b);if(c&-8)return-28;var d=K(b,{Be:!0}).node;if(!d)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&Nb(d,a)?-2:0}catch(e){if("undefined"==typeof M||"ErrnoError"!==e.name)throw e;return-e.he}},j:function(a,b,c){rc=c;try{var d=L(a);switch(b){case 0:var e=sc();if(0>e)break;for(;Cb[e];)e++;return Sb(d,e).fd;
case 1:case 2:return 0;case 3:return d.flags;case 4:return e=sc(),d.flags|=e,0;case 12:return e=sc(),va[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof M||"ErrnoError"!==f.name)throw f;return-f.he}},gb:function(a,b){try{var c=L(a);return qc(ac,c.path,b)}catch(d){if("undefined"==typeof M||"ErrnoError"!==d.name)throw d;return-d.he}},Xa:function(a,b,c){try{var d=L(a);if(!d.ye){var e=K(d.path,{Be:!0}).node;if(!e.ce.readdir)throw new H(54);var f=e.ce.readdir(e);d.ye=f}a=
0;for(var g=hc(d,0,1),m=Math.floor(g/280);m<d.ye.length&&a+280<=c;){var n=d.ye[m];if("."===n){var p=d.node.id;var r=4}else if(".."===n)p=K(d.path,{parent:!0}).node.id,r=4;else{var u=rb(d.node,n);p=u.id;r=8192===(u.mode&61440)?2:J(u.mode)?4:40960===(u.mode&61440)?10:8}D=[p>>>0,(C=p,1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];t[b+a>>2]=D[0];t[b+a+4>>2]=D[1];D=[280*(m+1)>>>0,(C=280*(m+1),1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-
+(~~C>>>0))/4294967296)>>>0:0)];t[b+a+8>>2]=D[0];t[b+a+12>>2]=D[1];va[b+a+16>>1]=280;l[b+a+18]=r;G(n,q,b+a+19,256);a+=280;m+=1}hc(d,280*m,0);return a}catch(y){if("undefined"==typeof M||"ErrnoError"!==y.name)throw y;return-y.he}},ib:function(a,b,c){rc=c;try{var d=L(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.ue.Lf){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=sc();t[e>>2]=25856;t[e+4>>2]=5;t[e+8>>2]=191;t[e+12>>2]=35387;
for(var f=0;32>f;f++)l[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.ue.Mf)for(e=sc(),a=[],f=0;32>f;f++)a.push(l[e+f+17]);return 0;case 21519:if(!d.tty)return-59;e=sc();return t[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=sc();if(!d.ee.Kf)throw new H(59);return d.ee.Kf(d,b,e);case 21523:if(!d.tty)return-59;d.tty.ue.Nf&&(f=[24,80],e=sc(),va[e>>1]=f[0],va[e+2>>1]=f[1]);return 0;case 21524:return d.tty?
0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof M||"ErrnoError"!==g.name)throw g;return-g.he}},eb:function(a,b){try{return a=a?E(q,a):"",qc(bc,a,b)}catch(c){if("undefined"==typeof M||"ErrnoError"!==c.name)throw c;return-c.he}},Za:function(a,b,c){try{return b=b?E(q,b):"",b=pc(a,b),b=$a(b),"/"===b[b.length-1]&&(b=b.substr(0,b.length-1)),Wb(b,c),0}catch(d){if("undefined"==typeof M||"ErrnoError"!==d.name)throw d;return-d.he}},db:function(a,b,c,d){try{b=b?E(q,b):
"";var e=d&256;b=pc(a,b,d&4096);return qc(e?bc:ac,b,c)}catch(f){if("undefined"==typeof M||"ErrnoError"!==f.name)throw f;return-f.he}},N:function(a,b,c,d){rc=d;try{b=b?E(q,b):"";b=pc(a,b);var e=d?sc():0;return dc(b,c,e).fd}catch(f){if("undefined"==typeof M||"ErrnoError"!==f.name)throw f;return-f.he}},Wa:function(a,b,c,d){try{b=b?E(q,b):"";b=pc(a,b);if(0>=d)return-28;var e=Jb(b),f=Math.min(d,gb(e)),g=l[c+f];G(e,q,c,d+1);l[c+f]=g;return f}catch(m){if("undefined"==typeof M||"ErrnoError"!==m.name)throw m;
return-m.he}},Ua:function(a){try{return a=a?E(q,a):"",Zb(a),0}catch(b){if("undefined"==typeof M||"ErrnoError"!==b.name)throw b;return-b.he}},fb:function(a,b){try{return a=a?E(q,a):"",qc(ac,a,b)}catch(c){if("undefined"==typeof M||"ErrnoError"!==c.name)throw c;return-c.he}},Va:function(a,b,c){try{return b=b?E(q,b):"",b=pc(a,b),0===c?$b(b):512===c?Zb(b):Ha("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof M||"ErrnoError"!==d.name)throw d;return-d.he}},mb:()=>{Ha("")},kb:()=>1,hb:(a,
b,c)=>q.copyWithin(a,b,b+c),Pa:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN));t[c>>2]=a.getSeconds();t[c+4>>2]=a.getMinutes();t[c+8>>2]=a.getHours();t[c+12>>2]=a.getDate();t[c+16>>2]=a.getMonth();t[c+20>>2]=a.getFullYear()-1900;t[c+24>>2]=a.getDay();t[c+28>>2]=(tc(a.getFullYear())?uc:vc)[a.getMonth()]+a.getDate()-1|0;t[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();
t[c+32>>2]=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0},Qa:function(a){var b=new Date(t[a+20>>2]+1900,t[a+16>>2],t[a+12>>2],t[a+8>>2],t[a+4>>2],t[a>>2],0),c=t[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),g=Math.min(f,e);0>c?t[a+32>>2]=Number(e!=f&&g==d):0<c!=(g==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+6E4*((0<c?g:e)-d)));t[a+24>>2]=b.getDay();t[a+28>>2]=(tc(b.getFullYear())?uc:vc)[b.getMonth()]+b.getDate()-
1|0;t[a>>2]=b.getSeconds();t[a+4>>2]=b.getMinutes();t[a+8>>2]=b.getHours();t[a+12>>2]=b.getDate();t[a+16>>2]=b.getMonth();t[a+20>>2]=b.getYear();a=b.getTime();a=isNaN(a)?-1:a/1E3;kf((C=a,1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0));return a>>>0},Ya:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=new Date(e,0,1),g=new Date(e,6,1);e=f.getTimezoneOffset();var m=g.getTimezoneOffset();v[a>>2]=60*Math.max(e,m);t[b>>2]=Number(e!=m);a=n=>n.toLocaleTimeString(void 0,
{hour12:!1,timeZoneName:"short"}).split(" ")[1];f=a(f);g=a(g);m<e?(G(f,q,c,17),G(g,q,d,17)):(G(f,q,d,17),G(g,q,c,17))},La:a=>{if(12448==a)return O=12288,1;O=12300;return 0},hc:(a,b,c,d,e)=>{if(62E3!=a)O=12296,c=0;else{if(b)for(;;){a=t[b>>2];if(12321==a)P.alpha=0<t[b+4>>2];else if(12325==a)P.depth=0<t[b+4>>2];else if(12326==a)P.stencil=0<t[b+4>>2];else if(12337==a)a=t[b+4>>2],P.antialias=0<a;else if(12338==a)a=t[b+4>>2],P.antialias=1==a;else if(12544==a)P.ig=12547!=t[b+4>>2];else if(12344==a)break;
b+=8}c&&d||e?(e&&(t[e>>2]=1),c&&0<d&&(v[c>>2]=62002),O=12288,c=1):(O=12300,c=0)}return c},Mb:(a,b,c,d)=>{if(62E3!=a)return O=12296,0;for(a=1;;){b=t[d>>2];if(12440==b)a=t[d+4>>2];else if(12344==b)break;else return O=12292,0;d+=8}if(2!=a)return O=12293,0;P.mf=a-1;P.jg=0;nd=Gd(h.canvas,P);if(0!=nd)return O=12288,Jd(nd),h.Tf=!0,Xc.forEach(function(e){e()}),Jd(null),62004;O=12297;return 0},qb:(a,b)=>{if(62E3!=a)return O=12296,0;if(62002!=b)return O=12293,0;O=12288;return 62006},Bb:(a,b)=>{if(62E3!=a)return O=
12296,0;if(62004!=b)return O=12294,0;a=nd;Id===yd[a]&&(Id=null);if("object"==typeof $d)for(var c=yd[a].ve.canvas,d=0;d<Vd.length;++d)Vd[d].target!=c||Wd(d--);yd[a]&&yd[a].ve.canvas&&(yd[a].ve.canvas.Ee=void 0);yd[a]=null;O=12288;jd==b&&(jd=0);return 1},jb:(a,b)=>{if(62E3!=a)return O=12296,0;if(62006!=b)return O=12301,1;kd==b&&(kd=0);ld==b&&(ld=0);O=12288;return 1},Yb:(a,b,c,d)=>{if(62E3!=a)return O=12296,0;if(62002!=b)return O=12293,0;if(!d)return O=12300,0;O=12288;switch(c){case 12320:return t[d>>
2]=P.alpha?32:24,1;case 12321:return t[d>>2]=P.alpha?8:0,1;case 12322:return t[d>>2]=8,1;case 12323:return t[d>>2]=8,1;case 12324:return t[d>>2]=8,1;case 12325:return t[d>>2]=P.depth?24:0,1;case 12326:return t[d>>2]=P.stencil?8:0,1;case 12327:return t[d>>2]=12344,1;case 12328:return t[d>>2]=62002,1;case 12329:return t[d>>2]=0,1;case 12330:return t[d>>2]=4096,1;case 12331:return t[d>>2]=16777216,1;case 12332:return t[d>>2]=4096,1;case 12333:return t[d>>2]=0,1;case 12334:return t[d>>2]=0,1;case 12335:return t[d>>
2]=12344,1;case 12337:return t[d>>2]=P.antialias?4:0,1;case 12338:return t[d>>2]=P.antialias?1:0,1;case 12339:return t[d>>2]=4,1;case 12340:return t[d>>2]=12344,1;case 12341:case 12342:case 12343:return t[d>>2]=-1,1;case 12345:case 12346:return t[d>>2]=0,1;case 12347:return t[d>>2]=0,1;case 12348:return t[d>>2]=1;case 12349:case 12350:return t[d>>2]=0,1;case 12351:return t[d>>2]=12430,1;case 12352:return t[d>>2]=4,1;case 12354:return t[d>>2]=0,1;default:return O=12292,0}},P:a=>{O=12288;return 0!=
a&&1!=a?0:62E3},Ja:()=>O,Dc:(a,b,c)=>{if(62E3!=a)return O=12296,0;b&&(t[b>>2]=1);c&&(t[c>>2]=4);hd=!0;O=12288;return 1},bb:(a,b,c,d)=>{if(62E3!=a)return O=12296,0;if(0!=d&&62004!=d)return O=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return O=12301,0;Jd(d?nd:null);jd=d;ld=b;kd=c;O=12288;return 1},Ka:(a,b)=>{if(62E3!=a)return O=12296,0;O=12288;if(md[b])return md[b];switch(b){case 12371:a=Ld("Emscripten");break;case 12372:a=Ld("1.4 Emscripten EGL");break;case 12373:a=Ld("");break;case 12429:a=Ld("OpenGL_ES");
break;default:return O=12300,0}return md[b]=a},Sa:()=>{if(hd)if(h.pe)if(h.pe.isContextLost())O=12302;else return O=12288,1;else O=12290;else O=12289;return 0},Oa:(a,b)=>{if(62E3!=a)return O=12296,0;0==b?Gc(0,0):Gc(1,b);O=12288;return 1},sc:a=>{if(62E3!=a)return O=12296,0;ld=kd=jd=0;hd=!1;O=12288;return 1},Ma:()=>{O=12288;return 1},Na:()=>{O=12288;return 1},n:(a,b,c)=>{b=Nd(b,c);return Va[a](...b)},b:(a,b,c)=>{b=Nd(b,c);return Va[a](...b)},p:(a,b,c)=>{b=Nd(b,c);return Va[a](...b)},Ga:()=>{Uc();yc=
null},O:()=>Date.now(),Ca:()=>{if(!Zd())return-1;Rd(Ae);var a=ne[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Ha:()=>{Rd(Be);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},Fa:a=>{Xa=!1;Qc=0;ua=a;Rc(a)},e:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,c:(a,b,c)=>{a=V(a);if(!a)return-4;a=ze(a);z[b>>3]=a.width;z[c>>3]=a.height;return 0},
Q:(a,b)=>{if(0>a||a>=ae.length)return-5;if(!ae[a])return-7;Ce(b,ae[a]);return 0},k:Cc,$:()=>ae.length,Ia:(a,b)=>{t[a>>2]=screen.width;t[b>>2]=screen.height},ia:a=>T.activeTexture(a),ha:(a,b)=>{T.attachShader(R[a],S[b])},ya:(a,b)=>{T.te.beginQueryEXT(a,zd[b])},ga:(a,b,c)=>{T.bindAttribLocation(R[a],b,c?E(q,c):"")},fa:(a,b)=>{T.bindBuffer(a,td[b])},ea:(a,b)=>{T.bindFramebuffer(a,ud[b])},da:(a,b)=>{T.bindRenderbuffer(a,vd[b])},ca:(a,b)=>{T.bindTexture(a,wd[b])},qa:a=>{T.bindVertexArray(xd[a])},ba:(a,
b,c,d)=>T.blendColor(a,b,c,d),aa:a=>T.blendEquation(a),_:(a,b)=>T.blendEquationSeparate(a,b),Z:(a,b)=>T.blendFunc(a,b),Y:(a,b,c,d)=>T.blendFuncSeparate(a,b,c,d),X:(a,b,c,d)=>{T.bufferData(a,c?q.subarray(c,c+b):b,d)},W:(a,b,c,d)=>{T.bufferSubData(a,b,q.subarray(d,d+c))},V:a=>T.checkFramebufferStatus(a),U:a=>T.clear(a),T:(a,b,c,d)=>T.clearColor(a,b,c,d),S:a=>T.clearDepth(a),R:a=>T.clearStencil(a),Jd:(a,b,c,d)=>{T.colorMask(!!a,!!b,!!c,!!d)},Id:a=>{T.compileShader(S[a])},Hd:(a,b,c,d,e,f,g,m)=>{T.compressedTexImage2D(a,
b,c,d,e,f,m?q.subarray(m,m+g):null)},Gd:(a,b,c,d,e,f,g,m,n)=>{T.compressedTexSubImage2D(a,b,c,d,e,f,g,n?q.subarray(n,n+m):null)},Fd:(a,b,c,d,e,f,g,m)=>T.copyTexImage2D(a,b,c,d,e,f,g,m),Ed:(a,b,c,d,e,f,g,m)=>T.copyTexSubImage2D(a,b,c,d,e,f,g,m),Dd:()=>{var a=Dd(R),b=T.createProgram();b.name=a;b.Me=b.Ke=b.Le=0;b.Ye=1;R[a]=b;return a},Cd:a=>{var b=Dd(S);S[b]=T.createShader(a);return b},Bd:a=>T.cullFace(a),Ad:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=td[d];e&&(T.deleteBuffer(e),e.name=0,td[d]=
null)}},zd:(a,b)=>{for(var c=0;c<a;++c){var d=t[b+4*c>>2],e=ud[d];e&&(T.deleteFramebuffer(e),e.name=0,ud[d]=null)}},yd:a=>{if(a){var b=R[a];b?(T.deleteProgram(b),b.name=0,R[a]=null):U||=1281}},Aa:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=zd[d];e&&(T.te.deleteQueryEXT(e),zd[d]=null)}},xd:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=vd[d];e&&(T.deleteRenderbuffer(e),e.name=0,vd[d]=null)}},wd:a=>{if(a){var b=S[a];b?(T.deleteShader(b),S[a]=null):U||=1281}},vd:(a,b)=>{for(var c=0;c<a;c++){var d=
t[b+4*c>>2],e=wd[d];e&&(T.deleteTexture(e),e.name=0,wd[d]=null)}},pa:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2];T.deleteVertexArray(xd[d]);xd[d]=null}},ud:a=>T.depthFunc(a),td:a=>{T.depthMask(!!a)},sd:(a,b)=>T.depthRange(a,b),rd:(a,b)=>{T.detachShader(R[a],S[b])},qd:a=>T.disable(a),pd:a=>{T.disableVertexAttribArray(a)},od:(a,b,c)=>{T.drawArrays(a,b,c)},la:(a,b,c,d)=>{T.drawArraysInstanced(a,b,c,d)},ma:(a,b)=>{for(var c=De[a],d=0;d<a;d++)c[d]=t[b+4*d>>2];T.drawBuffers(c)},nd:(a,b,c,d)=>{T.drawElements(a,
b,c,d)},ka:(a,b,c,d,e)=>{T.drawElementsInstanced(a,b,c,d,e)},md:a=>T.enable(a),ld:a=>{T.enableVertexAttribArray(a)},xa:a=>{T.te.endQueryEXT(a)},kd:()=>T.finish(),jd:()=>T.flush(),id:(a,b,c,d)=>{T.framebufferRenderbuffer(a,b,c,vd[d])},hd:(a,b,c,d,e)=>{T.framebufferTexture2D(a,b,c,wd[d],e)},gd:a=>T.frontFace(a),fd:(a,b)=>{Ed(a,b,"createBuffer",td)},dd:(a,b)=>{Ed(a,b,"createFramebuffer",ud)},Ba:(a,b)=>{for(var c=0;c<a;c++){var d=T.te.createQueryEXT();if(!d){for(U||=1282;c<a;)t[b+4*c++>>2]=0;break}var e=
Dd(zd);d.name=e;zd[e]=d;t[b+4*c>>2]=e}},cd:(a,b)=>{Ed(a,b,"createRenderbuffer",vd)},bd:(a,b)=>{Ed(a,b,"createTexture",wd)},oa:(a,b)=>{Ed(a,b,"createVertexArray",xd)},ed:a=>T.generateMipmap(a),ad:(a,b,c,d,e,f,g)=>{Ee("getActiveAttrib",a,b,c,d,e,f,g)},$c:(a,b,c,d,e,f,g)=>{Ee("getActiveUniform",a,b,c,d,e,f,g)},_c:(a,b,c,d)=>{a=T.getAttachedShaders(R[a]);var e=a.length;e>b&&(e=b);t[c>>2]=e;for(b=0;b<e;++b)t[d+4*b>>2]=S.indexOf(a[b])},Zc:(a,b)=>T.getAttribLocation(R[a],b?E(q,b):""),Yc:(a,b)=>Fe(a,b,4),
Xc:(a,b,c)=>{c?t[c>>2]=T.getBufferParameter(a,b):U||=1281},Wc:()=>{var a=T.getError()||U;U=0;return a},Vc:(a,b)=>Fe(a,b,2),Uc:(a,b,c,d)=>{a=T.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;t[d>>2]=a},Tc:(a,b)=>Fe(a,b,0),Rc:(a,b,c,d)=>{a=T.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?G(a,q,d,b):0;c&&(t[c>>2]=b)},Sc:(a,b,c)=>{if(c)if(a>=sd)U||=1281;else if(a=R[a],35716==b)a=T.getProgramInfoLog(a),null===a&&(a="(unknown error)"),
t[c>>2]=a.length+1;else if(35719==b){if(!a.Me)for(b=0;b<T.getProgramParameter(a,35718);++b)a.Me=Math.max(a.Me,T.getActiveUniform(a,b).name.length+1);t[c>>2]=a.Me}else if(35722==b){if(!a.Ke)for(b=0;b<T.getProgramParameter(a,35721);++b)a.Ke=Math.max(a.Ke,T.getActiveAttrib(a,b).name.length+1);t[c>>2]=a.Ke}else if(35381==b){if(!a.Le)for(b=0;b<T.getProgramParameter(a,35382);++b)a.Le=Math.max(a.Le,T.getActiveUniformBlockName(a,b).length+1);t[c>>2]=a.Le}else t[c>>2]=T.getProgramParameter(a,b);else U||=1281},
sa:Ge,ua:He,ra:Ge,ta:He,va:(a,b,c)=>{c?t[c>>2]=T.te.getQueryEXT(a,b):U||=1281},Qc:(a,b,c)=>{c?t[c>>2]=T.getRenderbufferParameter(a,b):U||=1281},Oc:(a,b,c,d)=>{a=T.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?G(a,q,d,b):0;c&&(t[c>>2]=b)},Nc:(a,b,c,d)=>{a=T.getShaderPrecisionFormat(a,b);t[c>>2]=a.rangeMin;t[c+4>>2]=a.rangeMax;t[d>>2]=a.precision},Mc:(a,b,c,d)=>{if(a=T.getShaderSource(S[a]))b=0<b&&d?G(a,q,d,b):0,c&&(t[c>>2]=b)},Pc:(a,b,c)=>{c?35716==b?(a=T.getShaderInfoLog(S[a]),null===
a&&(a="(unknown error)"),t[c>>2]=a?a.length+1:0):35720==b?(a=T.getShaderSource(S[a]),t[c>>2]=a?a.length+1:0):t[c>>2]=T.getShaderParameter(S[a],b):U||=1281},Lc:a=>{var b=Ad[a];if(!b){switch(a){case 7939:b=Ld(Ie().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=T.getParameter(a))||(U||=1280);b=b?Ld(b):0;break;case 7938:b=Ld(`OpenGL ES 2.0 (${T.getParameter(7938)})`);break;case 35724:b=T.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&
(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Ld(b);break;default:U||=1280}Ad[a]=b}return b},Kc:(a,b,c)=>{c?x[c>>2]=T.getTexParameter(a,b):U||=1281},Jc:(a,b,c)=>{c?t[c>>2]=T.getTexParameter(a,b):U||=1281},Gc:(a,b)=>{b=b?E(q,b):"";if(a=R[a]){Ke(a);var c=a.He,d=0,e=b,f=Je(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.vf[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||T.getUniformLocation(a,b)))return d}else U||=1281;return-1},Ic:(a,b,c)=>{Le(a,b,c,2)},Hc:(a,b,c)=>{Le(a,b,c,0)},Cc:(a,b,c)=>{c?
t[c>>2]=T.getVertexAttribOffset(a,b):U||=1281},Fc:(a,b,c)=>{Me(a,b,c,2)},Ec:(a,b,c)=>{Me(a,b,c,5)},Bc:(a,b)=>T.hint(a,b),Ac:a=>(a=td[a])?T.isBuffer(a):0,zc:a=>T.isEnabled(a),yc:a=>(a=ud[a])?T.isFramebuffer(a):0,xc:a=>(a=R[a])?T.isProgram(a):0,za:a=>(a=zd[a])?T.te.isQueryEXT(a):0,wc:a=>(a=vd[a])?T.isRenderbuffer(a):0,vc:a=>(a=S[a])?T.isShader(a):0,uc:a=>(a=wd[a])?T.isTexture(a):0,na:a=>(a=xd[a])?T.isVertexArray(a):0,tc:a=>T.lineWidth(a),rc:a=>{a=R[a];T.linkProgram(a);a.He=0;a.vf={}},qc:(a,b)=>{3317==
a?Bd=b:3314==a&&(Cd=b);T.pixelStorei(a,b)},pc:(a,b)=>T.polygonOffset(a,b),wa:(a,b)=>{T.te.queryCounterEXT(zd[a],b)},oc:(a,b,c,d,e,f,g)=>{(g=Ne(f,e,c,d,g))?T.readPixels(a,b,c,d,e,f,g):U||=1280},nc:()=>{},mc:(a,b,c,d)=>T.renderbufferStorage(a,b,c,d),lc:(a,b)=>{T.sampleCoverage(a,!!b)},kc:(a,b,c,d)=>T.scissor(a,b,c,d),jc:()=>{U||=1280},ic:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=v[c+4*f>>2])?E(q,g,d?v[d+4*f>>2]:void 0):"";e+=g}T.shaderSource(S[a],e)},gc:(a,b,c)=>T.stencilFunc(a,b,c),fc:(a,b,c,
d)=>T.stencilFuncSeparate(a,b,c,d),ec:a=>T.stencilMask(a),dc:(a,b)=>T.stencilMaskSeparate(a,b),cc:(a,b,c)=>T.stencilOp(a,b,c),bc:(a,b,c,d)=>T.stencilOpSeparate(a,b,c,d),ac:(a,b,c,d,e,f,g,m,n)=>{n=n?Ne(m,g,d,e,n):null;T.texImage2D(a,b,c,d,e,f,g,m,n)},$b:(a,b,c)=>T.texParameterf(a,b,c),_b:(a,b,c)=>{T.texParameterf(a,b,x[c>>2])},Zb:(a,b,c)=>T.texParameteri(a,b,c),Xb:(a,b,c)=>{T.texParameteri(a,b,t[c>>2])},Wb:(a,b,c,d,e,f,g,m,n)=>{n=n?Ne(m,g,e,f,n):null;T.texSubImage2D(a,b,c,d,e,f,g,m,n)},Vb:(a,b)=>{T.uniform1f(X(a),
b)},Ub:(a,b,c)=>{if(288>=b)for(var d=Oe[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);T.uniform1fv(X(a),d)},Tb:(a,b)=>{T.uniform1i(X(a),b)},Sb:(a,b,c)=>{if(288>=b)for(var d=Pe[b],e=0;e<b;++e)d[e]=t[c+4*e>>2];else d=t.subarray(c>>2,c+4*b>>2);T.uniform1iv(X(a),d)},Rb:(a,b,c)=>{T.uniform2f(X(a),b,c)},Qb:(a,b,c)=>{if(144>=b)for(var d=Oe[2*b],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);T.uniform2fv(X(a),d)},Pb:(a,b,c)=>{T.uniform2i(X(a),b,
c)},Ob:(a,b,c)=>{if(144>=b)for(var d=Pe[2*b],e=0;e<2*b;e+=2)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2];else d=t.subarray(c>>2,c+8*b>>2);T.uniform2iv(X(a),d)},Lb:(a,b,c,d)=>{T.uniform3f(X(a),b,c,d)},Kb:(a,b,c)=>{if(96>=b)for(var d=Oe[3*b],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);T.uniform3fv(X(a),d)},Jb:(a,b,c,d)=>{T.uniform3i(X(a),b,c,d)},Ib:(a,b,c)=>{if(96>=b)for(var d=Pe[3*b],e=0;e<3*b;e+=3)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>
2],d[e+2]=t[c+(4*e+8)>>2];else d=t.subarray(c>>2,c+12*b>>2);T.uniform3iv(X(a),d)},Hb:(a,b,c,d,e)=>{T.uniform4f(X(a),b,c,d,e)},Gb:(a,b,c)=>{if(72>=b){var d=Oe[4*b],e=x;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=x.subarray(c>>2,c+16*b>>2);T.uniform4fv(X(a),d)},Fb:(a,b,c,d,e)=>{T.uniform4i(X(a),b,c,d,e)},Eb:(a,b,c)=>{if(72>=b)for(var d=Pe[4*b],e=0;e<4*b;e+=4)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2],d[e+3]=t[c+(4*e+12)>>2];
else d=t.subarray(c>>2,c+16*b>>2);T.uniform4iv(X(a),d)},Db:(a,b,c,d)=>{if(72>=b)for(var e=Oe[4*b],f=0;f<4*b;f+=4)e[f]=x[d+4*f>>2],e[f+1]=x[d+(4*f+4)>>2],e[f+2]=x[d+(4*f+8)>>2],e[f+3]=x[d+(4*f+12)>>2];else e=x.subarray(d>>2,d+16*b>>2);T.uniformMatrix2fv(X(a),!!c,e)},Cb:(a,b,c,d)=>{if(32>=b)for(var e=Oe[9*b],f=0;f<9*b;f+=9)e[f]=x[d+4*f>>2],e[f+1]=x[d+(4*f+4)>>2],e[f+2]=x[d+(4*f+8)>>2],e[f+3]=x[d+(4*f+12)>>2],e[f+4]=x[d+(4*f+16)>>2],e[f+5]=x[d+(4*f+20)>>2],e[f+6]=x[d+(4*f+24)>>2],e[f+7]=x[d+(4*f+28)>>
2],e[f+8]=x[d+(4*f+32)>>2];else e=x.subarray(d>>2,d+36*b>>2);T.uniformMatrix3fv(X(a),!!c,e)},Ab:(a,b,c,d)=>{if(18>=b){var e=Oe[16*b],f=x;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=x.subarray(d>>2,d+64*b>>2);T.uniformMatrix4fv(X(a),!!c,e)},zb:a=>{a=R[a];T.useProgram(a);
T.yf=a},yb:a=>{T.validateProgram(R[a])},xb:(a,b)=>T.vertexAttrib1f(a,b),wb:(a,b)=>{T.vertexAttrib1f(a,x[b>>2])},vb:(a,b,c)=>T.vertexAttrib2f(a,b,c),ub:(a,b)=>{T.vertexAttrib2f(a,x[b>>2],x[b+4>>2])},tb:(a,b,c,d)=>T.vertexAttrib3f(a,b,c,d),sb:(a,b)=>{T.vertexAttrib3f(a,x[b>>2],x[b+4>>2],x[b+8>>2])},rb:(a,b,c,d,e)=>T.vertexAttrib4f(a,b,c,d,e),pb:(a,b)=>{T.vertexAttrib4f(a,x[b>>2],x[b+4>>2],x[b+8>>2],x[b+12>>2])},ja:(a,b)=>{T.vertexAttribDivisor(a,b)},ob:(a,b,c,d,e,f)=>{T.vertexAttribPointer(a,b,c,!!d,
e,f)},nb:(a,b,c,d)=>T.viewport(a,b,c,d),m:()=>0,Da:(a,b,c)=>Qe(a,{We:t[c>>2],Qe:t[c+4>>2],Ff:t[c+8>>2],Cf:b,Je:t[c+12>>2],af:t[c+16>>2]}),K:(a,b)=>{a=V(a);return a?a.requestPointerLock?Sd()?Be(a):b?(Qd(Be,2,[a]),1):-2:-1:-4},Ta:()=>{Ha("OOM")},o:Re,q:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:Se(a,b),C:(a,b,c,d)=>Te(a,b,c,d,12,"blur"),d:te,i:(a,b,c)=>{a=V(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},D:(a,b,c,d)=>Te(a,b,c,d,13,"focus"),t:(a,b,c,d)=>{if(!Zd())return-1;
a=V(a);if(!a)return-4;Ue(a,b,c,d,"webkitfullscreenchange");return Ue(a,b,c,d,"fullscreenchange")},h:(a,b,c)=>Re()?-1:Ve(a,b,c,26,"gamepadconnected"),g:(a,b,c)=>Re()?-1:Ve(a,b,c,27,"gamepaddisconnected"),w:(a,b,c,d)=>We(a,b,c,d,2,"keydown"),u:(a,b,c,d)=>We(a,b,c,d,1,"keypress"),v:(a,b,c,d)=>We(a,b,c,d,3,"keyup"),Kd:(a,b,c)=>{a=W(a);Pc(a,b,c)},I:(a,b,c,d)=>Ye(a,b,c,d,5,"mousedown"),G:(a,b,c,d)=>Ye(a,b,c,d,33,"mouseenter"),F:(a,b,c,d)=>Ye(a,b,c,d,34,"mouseleave"),J:(a,b,c,d)=>Ye(a,b,c,d,8,"mousemove"),
H:(a,b,c,d)=>Ye(a,b,c,d,6,"mouseup"),x:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.ge||document.body.Fe||document.body.xe))return-1;a=V(a);if(!a)return-4;Ze(a,b,c,d,"mozpointerlockchange");Ze(a,b,c,d,"webkitpointerlockchange");Ze(a,b,c,d,"mspointerlockchange");return Ze(a,b,c,d,"pointerlockchange")},s:(a,b,c,d)=>$e(a,b,c,d),y:(a,b,c,d)=>af(a,b,c,d,25,"touchcancel"),A:(a,b,c,d)=>af(a,b,c,d,23,"touchend"),z:(a,b,c,d)=>af(a,b,c,d,24,"touchmove"),B:(a,b,
c,d)=>af(a,b,c,d,22,"touchstart"),r:(a,b,c)=>ne[1]?bf(a,b,c):-4,E:(a,b,c,d)=>(a=V(a))?"undefined"!=typeof a.onwheel?cf(a,b,c,d):-1:-4,Ea:a=>document.title=a?E(q,a):"",l:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},$a:(a,b)=>{var c=0;ff().forEach((d,e)=>{var f=b+c;e=v[a+4*e>>2]=f;for(f=0;f<d.length;++f)l[e++]=d.charCodeAt(f);l[e]=0;c+=d.length+1});return 0},ab:(a,b)=>{var c=ff();v[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+
1);v[b>>2]=d;return 0},Nb:Sc,f:function(a){try{var b=L(a);gc(b);return 0}catch(c){if("undefined"==typeof M||"ErrnoError"!==c.name)throw c;return c.he}},_a:function(a,b){try{var c=L(a);l[b]=c.tty?2:J(c.mode)?3:40960===(c.mode&61440)?7:4;va[b+2>>1]=0;D=[0,(C=0,1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];t[b+8>>2]=D[0];t[b+12>>2]=D[1];D=[0,(C=0,1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];t[b+16>>
2]=D[0];t[b+20>>2]=D[1];return 0}catch(d){if("undefined"==typeof M||"ErrnoError"!==d.name)throw d;return d.he}},M:function(a,b,c,d){try{a:{var e=L(a);a=b;for(var f,g=b=0;g<c;g++){var m=v[a>>2],n=v[a+4>>2];a+=8;var p=e,r=f,u=l;if(0>n||0>r)throw new H(28);if(null===p.fd)throw new H(8);if(1===(p.flags&2097155))throw new H(8);if(J(p.node.mode))throw new H(31);if(!p.ee.read)throw new H(28);var y="undefined"!=typeof r;if(!y)r=p.position;else if(!p.seekable)throw new H(70);var A=p.ee.read(p,u,m,n,r);y||
(p.position+=A);var w=A;if(0>w){var B=-1;break a}b+=w;if(w<n)break;"undefined"!=typeof f&&(f+=w)}B=b}v[d>>2]=B;return 0}catch(N){if("undefined"==typeof M||"ErrnoError"!==N.name)throw N;return N.he}},Ra:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=L(a);hc(f,b,d);D=[f.position>>>0,(C=f.position,1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];t[e>>2]=D[0];t[e+4>>2]=D[1];f.ye&&0===b&&0===d&&(f.ye=
null);return 0}catch(g){if("undefined"==typeof M||"ErrnoError"!==g.name)throw g;return g.he}},cb:function(a){try{var b=L(a);return b.ee?.fsync?b.ee.fsync(b):0}catch(c){if("undefined"==typeof M||"ErrnoError"!==c.name)throw c;return c.he}},L:function(a,b,c,d){try{a:{var e=L(a);a=b;for(var f,g=b=0;g<c;g++){var m=v[a>>2],n=v[a+4>>2];a+=8;var p=ic(e,l,m,n,f);if(0>p){var r=-1;break a}b+=p;"undefined"!=typeof f&&(f+=p)}r=b}v[d>>2]=r;return 0}catch(u){if("undefined"==typeof M||"ErrnoError"!==u.name)throw u;
return u.he}}},Z=function(){function a(c){Z=c.exports;sa=Z.Ld;c=sa.buffer;h.HEAP8=l=new Int8Array(c);h.HEAP16=va=new Int16Array(c);h.HEAPU8=q=new Uint8Array(c);h.HEAPU16=wa=new Uint16Array(c);h.HEAP32=t=new Int32Array(c);h.HEAPU32=v=new Uint32Array(c);h.HEAPF32=x=new Float32Array(c);h.HEAPF64=z=new Float64Array(c);we=Z.Pd;ya.unshift(Z.Md);Ga("wasm-instantiate");return Z}var b={a:lf};Fa("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return k(`Module.instantiateWasm callback failed with error: ${c}`),
!1}Ja||=Ia("index.wasm")?"index.wasm":h.locateFile?h.locateFile("index.wasm",ka):ka+"index.wasm";Na(b,function(c){a(c.instance)});return{}}(),mf=h._main=(a,b)=>(mf=h._main=Z.Nd)(a,b),F=a=>(F=Z.Od)(a),kf=a=>(kf=Z.Qd)(a),re=a=>(re=Z.Rd)(a),oe=a=>(oe=Z.Sd)(a),qe=()=>(qe=Z.Td)();h.dynCall_viiijji=(a,b,c,d,e,f,g,m,n)=>(h.dynCall_viiijji=Z.Ud)(a,b,c,d,e,f,g,m,n);h.dynCall_jiji=(a,b,c,d,e)=>(h.dynCall_jiji=Z.Vd)(a,b,c,d,e);h.dynCall_ji=(a,b)=>(h.dynCall_ji=Z.Wd)(a,b);
h.dynCall_iij=(a,b,c,d)=>(h.dynCall_iij=Z.Xd)(a,b,c,d);h.dynCall_ij=(a,b,c)=>(h.dynCall_ij=Z.Yd)(a,b,c);h.dynCall_jiij=(a,b,c,d,e)=>(h.dynCall_jiij=Z.Zd)(a,b,c,d,e);h.dynCall_viijii=(a,b,c,d,e,f,g)=>(h.dynCall_viijii=Z._d)(a,b,c,d,e,f,g);h.dynCall_iiiiij=(a,b,c,d,e,f,g)=>(h.dynCall_iiiiij=Z.$d)(a,b,c,d,e,f,g);h.dynCall_iiiiijj=(a,b,c,d,e,f,g,m,n)=>(h.dynCall_iiiiijj=Z.ae)(a,b,c,d,e,f,g,m,n);h.dynCall_iiiiiijj=(a,b,c,d,e,f,g,m,n,p)=>(h.dynCall_iiiiiijj=Z.be)(a,b,c,d,e,f,g,m,n,p);
h.addRunDependency=Fa;h.removeRunDependency=Ga;h.FS_createPreloadedFile=yb;h.FS_unlink=a=>$b(a);h.FS_createPath=kc;h.FS_createDevice=mc;h.FS_createDataFile=(a,b,c,d,e,f)=>{xb(a,b,c,d,e,f)};h.FS_createLazyFile=oc;h.allocate=Pa;var nf;Ea=function of(){nf||pf();nf||(Ea=of)};function qf(a=[]){var b=mf;a.unshift(ia);var c=a.length,d=oe(4*(c+1)),e=d;a.forEach(g=>{v[e>>2]=pe(g);e+=4});v[e>>2]=0;try{var f=b(c,d);Sc(f,!0)}catch(g){Oc(g)}}
function pf(){var a=ha;function b(){if(!nf&&(nf=!0,h.calledRun=!0,!ta)){h.noFSInit||jc||(jc=!0,h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?mc("/dev","stdin",h.stdin):Yb("/dev/tty","/dev/stdin"),h.stdout?mc("/dev","stdout",null,h.stdout):Yb("/dev/tty","/dev/stdout"),h.stderr?mc("/dev","stderr",null,h.stderr):Yb("/dev/tty1","/dev/stderr"),dc("/dev/stdin",0),dc("/dev/stdout",1),dc("/dev/stderr",1));Fb=!1;Wa(ya);Wa(za);h.onRuntimeInitialized?.();rf&&qf(a);if(h.postRun)for("function"==
typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();Aa.unshift(c)}Wa(Aa)}}if(!(0<Ca)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ba();Wa(xa);0<Ca||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var rf=!0;h.noInitialRun&&(rf=!1);pf();
