var h;h||=typeof Module != 'undefined' ? Module : {};h.expectedDataFileDownloads||(h.expectedDataFileDownloads=0);h.expectedDataFileDownloads++;
(()=>{var a="undefined"!=typeof ENVIRONMENT_IS_WASM_WORKER&&ENVIRONMENT_IS_WASM_WORKER;"undefined"!=typeof ENVIRONMENT_IS_PTHREAD&&ENVIRONMENT_IS_PTHREAD||a||function(b){function c(p,r,v){var t=new XMLHttpRequest;t.open("GET",p,!0);t.responseType="arraybuffer";t.onprogress=F=>{var D=r;F.total&&(D=F.total);if(F.loaded){t.Pe?h.dataFileDownloads[p].loaded=F.loaded:(t.Pe=!0,h.dataFileDownloads||(h.dataFileDownloads={}),h.dataFileDownloads[p]={loaded:F.loaded,total:D});var E=D=F=0,Z;for(Z in h.dataFileDownloads){var ia=
h.dataFileDownloads[Z];F+=ia.total;D+=ia.loaded;E++}F=Math.ceil(F*h.expectedDataFileDownloads/E);h.setStatus?.(`Downloading data... (${D}/${F})`)}else h.dataFileDownloads||h.setStatus?.("Downloading data...")};t.onerror=()=>{throw Error("NetworkError for: "+p);};t.onload=()=>{if(200==t.status||304==t.status||206==t.status||0==t.status&&t.response)v(t.response);else throw Error(t.statusText+" : "+t.responseURL);};t.send(null)}function d(p){console.error("package error:",p)}function e(p){function r(D,
E,Z){this.start=D;this.end=E;this.audio=Z}function v(D){if(!D)throw"Loading data file failed."+Error().stack;if(D.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;D=new Uint8Array(D);r.prototype.Yf=D;D=b.files;for(var E=0;E<D.length;++E)r.prototype.Pe[D[E].filename].onload();p.removeRunDependency("datafile_index.data")}p.FS_createPath("/","dgguspat",!0,!0);r.prototype={Pe:{},open:function(D,E){this.name=E;this.Pe[E]=this;p.addRunDependency(`fp ${this.name}`)},
send:function(){},onload:function(){this.finish(this.Yf.subarray(this.start,this.end))},finish:function(D){p.FS_createDataFile(this.name,null,D,!0,!0,!0);p.removeRunDependency(`fp ${this.name}`);this.Pe[this.name]=null}};for(var t=b.files,F=0;F<t.length;++F)(new r(t[F].start,t[F].end,t[F].audio||0)).open("GET",t[F].filename);p.addRunDependency("datafile_index.data");p.preloadResults||(p.preloadResults={});p.preloadResults["index.data"]={zh:!1};n?(v(n),n=null):m=v}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,
window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var f=h.locateFile?h.locateFile("index.data",
""):"index.data",g=b.remote_package_size,m=null,n=h.getPreloadedPackage?h.getPreloadedPackage(f,g):null;n||c(f,g,p=>{m?(m(p),m=null):n=p},d);h.calledRun?e(h):(h.preRun||(h.preRun=[]),h.preRun.push(e))}({files:[{filename:"/dgguspat/acbass.pat",start:0,end:10829},{filename:"/dgguspat/accordn.pat",start:10829,end:30452},{filename:"/dgguspat/acguitar.pat",start:30452,end:83033},{filename:"/dgguspat/acpiano.pat",start:83033,end:148292},{filename:"/dgguspat/agogo.pat",start:148292,end:176019},{filename:"/dgguspat/agogohi.pat",
start:176019,end:183302},{filename:"/dgguspat/agogolo.pat",start:183302,end:190585},{filename:"/dgguspat/altosax.pat",start:190585,end:202296},{filename:"/dgguspat/applause.pat",start:202296,end:262745},{filename:"/dgguspat/atmosphr.pat",start:262745,end:325780},{filename:"/dgguspat/aurora.pat",start:325780,end:388283},{filename:"/dgguspat/bagpipes.pat",start:388283,end:404340},{filename:"/dgguspat/banjo.pat",start:404340,end:468863},{filename:"/dgguspat/barisax.pat",start:468863,end:490602},{filename:"/dgguspat/basslead.pat",
start:490602,end:543991},{filename:"/dgguspat/bassoon.pat",start:543991,end:560714},{filename:"/dgguspat/belltree.pat",start:560714,end:624817},{filename:"/dgguspat/blank.pat",start:624817,end:628184},{filename:"/dgguspat/bongohi.pat",start:628184,end:635417},{filename:"/dgguspat/bongolo.pat",start:635417,end:644618},{filename:"/dgguspat/bottle.pat",start:644618,end:669681},{filename:"/dgguspat/bowglass.pat",start:669681,end:719372},{filename:"/dgguspat/britepno.pat",start:719372,end:792111},{filename:"/dgguspat/c550kc_1.pat",
start:792111,end:803488},{filename:"/dgguspat/c550sn10.pat",start:803488,end:819456},{filename:"/dgguspat/c550sn_6.pat",start:819456,end:836778},{filename:"/dgguspat/c550vibs.pat",start:836778,end:867814},{filename:"/dgguspat/cabasa.pat",start:867814,end:885017},{filename:"/dgguspat/calliope.pat",start:885017,end:931320},{filename:"/dgguspat/carillon.pat",start:931320,end:943409},{filename:"/dgguspat/castinet.pat",start:943409,end:955758},{filename:"/dgguspat/celeste.pat",start:955758,end:975965},
{filename:"/dgguspat/cello.pat",start:975965,end:994706},{filename:"/dgguspat/charang.pat",start:994706,end:1085367},{filename:"/dgguspat/chiflead.pat",start:1085367,end:1148748},{filename:"/dgguspat/choir.pat",start:1148748,end:1194101},{filename:"/dgguspat/church.pat",start:1194101,end:1198710},{filename:"/dgguspat/claps.pat",start:1198710,end:1210429},{filename:"/dgguspat/clarinet.pat",start:1210429,end:1229590},{filename:"/dgguspat/clave.pat",start:1229590,end:1234625},{filename:"/dgguspat/clavinet.pat",
start:1234625,end:1238068},{filename:"/dgguspat/cleangtr.pat",start:1238068,end:1284095},{filename:"/dgguspat/concrtna.pat",start:1284095,end:1302076},{filename:"/dgguspat/congahi1.pat",start:1302076,end:1310829},{filename:"/dgguspat/congahi2.pat",start:1310829,end:1320542},{filename:"/dgguspat/congalo.pat",start:1320542,end:1330255},{filename:"/dgguspat/contraba.pat",start:1330255,end:1339978},{filename:"/dgguspat/cowbell.pat",start:1339978,end:1346623},{filename:"/dgguspat/crystal.pat",start:1346623,
end:1407406},{filename:"/dgguspat/cuica1.pat",start:1407406,end:1426401},{filename:"/dgguspat/cuica2.pat",start:1426401,end:1452418},{filename:"/dgguspat/cymbell.pat",start:1452418,end:1487233},{filename:"/dgguspat/cymchina.pat",start:1487233,end:1535778},{filename:"/dgguspat/cymcrsh1.pat",start:1535778,end:1599131},{filename:"/dgguspat/cymcrsh2.pat",start:1599131,end:1661542},{filename:"/dgguspat/cymride1.pat",start:1661542,end:1697197},{filename:"/dgguspat/cymride2.pat",start:1697197,end:1732852},
{filename:"/dgguspat/cymsplsh.pat",start:1732852,end:1796205},{filename:"/dgguspat/dgguspat.txt",start:1796205,end:1799310},{filename:"/dgguspat/distgtr.pat",start:1799310,end:1837559},{filename:"/dgguspat/dmx2timid.py",start:1837559,end:1838417},{filename:"/dgguspat/doo.pat",start:1838417,end:1855750},{filename:"/dgguspat/echovox.pat",start:1855750,end:1886037},{filename:"/dgguspat/englhorn.pat",start:1886037,end:1910712},{filename:"/dgguspat/epiano1.pat",start:1910712,end:1925717},{filename:"/dgguspat/epiano2.pat",
start:1925717,end:1969908},{filename:"/dgguspat/fantasia.pat",start:1969908,end:2017137},{filename:"/dgguspat/fiddle.pat",start:2017137,end:2029446},{filename:"/dgguspat/flute.pat",start:2029446,end:2041829},{filename:"/dgguspat/fngrbass.pat",start:2041829,end:2061626},{filename:"/dgguspat/frenchrn.pat",start:2061626,end:2090261},{filename:"/dgguspat/freshair.pat",start:2090261,end:2148568},{filename:"/dgguspat/fretless.pat",start:2148568,end:2154173},{filename:"/dgguspat/fx-blow.pat",start:2154173,
end:2211866},{filename:"/dgguspat/fx-fret.pat",start:2211866,end:2239497},{filename:"/dgguspat/ghostie.pat",start:2239497,end:2302798},{filename:"/dgguspat/glocken.pat",start:2302798,end:2313493},{filename:"/dgguspat/gtrharm.pat",start:2313493,end:2323666},{filename:"/dgguspat/guiro1.pat",start:2323666,end:2332227},{filename:"/dgguspat/guiro2.pat",start:2332227,end:2351048},{filename:"/dgguspat/halopad.pat",start:2351048,end:2411339},{filename:"/dgguspat/harmonca.pat",start:2411339,end:2426640},{filename:"/dgguspat/harp.pat",
start:2426640,end:2450567},{filename:"/dgguspat/helicptr.pat",start:2450567,end:2500894},{filename:"/dgguspat/highq.pat",start:2500894,end:2504839},{filename:"/dgguspat/hihatcl.pat",start:2504839,end:2514292},{filename:"/dgguspat/hihatop.pat",start:2514292,end:2554709},{filename:"/dgguspat/hihatpd.pat",start:2554709,end:2558634},{filename:"/dgguspat/hitbrass.pat",start:2558634,end:2622003},{filename:"/dgguspat/homeorg.pat",start:2622003,end:2624304},{filename:"/dgguspat/honky.pat",start:2624304,end:2756209},
{filename:"/dgguspat/hrpschrd.pat",start:2756209,end:2763918},{filename:"/dgguspat/jazzgtr.pat",start:2763918,end:2819841},{filename:"/dgguspat/jingles.pat",start:2819841,end:2854060},{filename:"/dgguspat/jungle.pat",start:2854060,end:2881601},{filename:"/dgguspat/kalimba.pat",start:2881601,end:2886340},{filename:"/dgguspat/kick1.pat",start:2886340,end:2895751},{filename:"/dgguspat/kick2.pat",start:2895751,end:2906128},{filename:"/dgguspat/koto.pat",start:2906128,end:2948207},{filename:"/dgguspat/lead5th.pat",
start:2948207,end:2961440},{filename:"/dgguspat/maracas.pat",start:2961440,end:2970873},{filename:"/dgguspat/marcato.pat",start:2970873,end:3093754},{filename:"/dgguspat/marimba.pat",start:3093754,end:3098201},{filename:"/dgguspat/metalpad.pat",start:3098201,end:3159106},{filename:"/dgguspat/metbell.pat",start:3159106,end:3159645},{filename:"/dgguspat/metclick.pat",start:3159645,end:3160184},{filename:"/dgguspat/musicbox.pat",start:3160184,end:3191131},{filename:"/dgguspat/mutegtr.pat",start:3191131,
end:3225708},{filename:"/dgguspat/mutetrum.pat",start:3225708,end:3244727},{filename:"/dgguspat/nyguitar.pat",start:3244727,end:3283938},{filename:"/dgguspat/oboe.pat",start:3283938,end:3293207},{filename:"/dgguspat/ocarina.pat",start:3293207,end:3296744},{filename:"/dgguspat/odguitar.pat",start:3296744,end:3322589},{filename:"/dgguspat/orchhit.pat",start:3322589,end:3351340},{filename:"/dgguspat/percorg.pat",start:3351340,end:3366775},{filename:"/dgguspat/piccolo.pat",start:3366775,end:3375720},
{filename:"/dgguspat/pickbass.pat",start:3375720,end:3408933},{filename:"/dgguspat/pistol.pat",start:3408933,end:3445528},{filename:"/dgguspat/pizzcato.pat",start:3445528,end:3485701},{filename:"/dgguspat/polysyn.pat",start:3485701,end:3546460},{filename:"/dgguspat/recorder.pat",start:3546460,end:3552107},{filename:"/dgguspat/reedorg.pat",start:3552107,end:3555578},{filename:"/dgguspat/revcym.pat",start:3555578,end:3582969},{filename:"/dgguspat/ringwhsl.pat",start:3582969,end:3641460},{filename:"/dgguspat/rockorg.pat",
start:3641460,end:3702347},{filename:"/dgguspat/santur.pat",start:3702347,end:3746180},{filename:"/dgguspat/sawwave.pat",start:3746180,end:3800665},{filename:"/dgguspat/scratch1.pat",start:3800665,end:3809756},{filename:"/dgguspat/scratch2.pat",start:3809756,end:3814639},{filename:"/dgguspat/seashore.pat",start:3814639,end:3877046},{filename:"/dgguspat/shakazul.pat",start:3877046,end:3939635},{filename:"/dgguspat/shaker.pat",start:3939635,end:3946162},{filename:"/dgguspat/shamisen.pat",start:3946162,
end:3972829},{filename:"/dgguspat/shannai.pat",start:3972829,end:3992980},{filename:"/dgguspat/sitar.pat",start:3992980,end:4029959},{filename:"/dgguspat/slap.pat",start:4029959,end:4041990},{filename:"/dgguspat/slapbas1.pat",start:4041990,end:4098123},{filename:"/dgguspat/slapbas2.pat",start:4098123,end:4139704},{filename:"/dgguspat/slowstr.pat",start:4139704,end:4176421},{filename:"/dgguspat/snare1.pat",start:4176421,end:4193838},{filename:"/dgguspat/snare2.pat",start:4193838,end:4202341},{filename:"/dgguspat/soundtrk.pat",
start:4202341,end:4242432},{filename:"/dgguspat/sprnosax.pat",start:4242432,end:4257145},{filename:"/dgguspat/sqrclick.pat",start:4257145,end:4257684},{filename:"/dgguspat/sqrwave.pat",start:4257684,end:4288123},{filename:"/dgguspat/startrak.pat",start:4288123,end:4343208},{filename:"/dgguspat/steeldrm.pat",start:4343208,end:4367437},{filename:"/dgguspat/stickrim.pat",start:4367437,end:4373442},{filename:"/dgguspat/sticks.pat",start:4373442,end:4382199},{filename:"/dgguspat/surdo1.pat",start:4382199,
end:4401726},{filename:"/dgguspat/surdo2.pat",start:4401726,end:4421253},{filename:"/dgguspat/sweeper.pat",start:4421253,end:4483998},{filename:"/dgguspat/synbass1.pat",start:4483998,end:4496625},{filename:"/dgguspat/synbass2.pat",start:4496625,end:4502816},{filename:"/dgguspat/synbras1.pat",start:4502816,end:4564551},{filename:"/dgguspat/synbras2.pat",start:4564551,end:4625192},{filename:"/dgguspat/synpiano.pat",start:4625192,end:4636735},{filename:"/dgguspat/synstr1.pat",start:4636735,end:4699498},
{filename:"/dgguspat/synstr2.pat",start:4699498,end:4732663},{filename:"/dgguspat/syntom.pat",start:4732663,end:4793994},{filename:"/dgguspat/taiko.pat",start:4793994,end:4831665},{filename:"/dgguspat/tamborin.pat",start:4831665,end:4849884},{filename:"/dgguspat/telephon.pat",start:4849884,end:4859041},{filename:"/dgguspat/tenorsax.pat",start:4859041,end:4876408},{filename:"/dgguspat/timbaleh.pat",start:4876408,end:4887247},{filename:"/dgguspat/timbalel.pat",start:4887247,end:4907034},{filename:"/dgguspat/timpani.pat",
start:4907034,end:4921507},{filename:"/dgguspat/tomhi1.pat",start:4921507,end:4934974},{filename:"/dgguspat/tomhi2.pat",start:4934974,end:4948429},{filename:"/dgguspat/tomlo1.pat",start:4948429,end:4961884},{filename:"/dgguspat/tomlo2.pat",start:4961884,end:4981411},{filename:"/dgguspat/tommid1.pat",start:4981411,end:4994866},{filename:"/dgguspat/tommid2.pat",start:4994866,end:5008321},{filename:"/dgguspat/toms.pat",start:5008321,end:5021788},{filename:"/dgguspat/tremstr.pat",start:5021788,end:5144669},
{filename:"/dgguspat/triangl1.pat",start:5144669,end:5149450},{filename:"/dgguspat/triangl2.pat",start:5149450,end:5181351},{filename:"/dgguspat/trombone.pat",start:5181351,end:5207538},{filename:"/dgguspat/trumpet.pat",start:5207538,end:5221159},{filename:"/dgguspat/tuba.pat",start:5221159,end:5233006},{filename:"/dgguspat/tubebell.pat",start:5233006,end:5251643},{filename:"/dgguspat/ultramid.ini",start:5251643,end:5257952},{filename:"/dgguspat/unicorn.pat",start:5257952,end:5318457},{filename:"/dgguspat/vibes.pat",
start:5318457,end:5340054},{filename:"/dgguspat/vibslap.pat",start:5340054,end:5359301},{filename:"/dgguspat/viola.pat",start:5359301,end:5415766},{filename:"/dgguspat/violin.pat",start:5415766,end:5440827},{filename:"/dgguspat/voices.pat",start:5440827,end:5471114},{filename:"/dgguspat/voxlead.pat",start:5471114,end:5501403},{filename:"/dgguspat/warmpad.pat",start:5501403,end:5537894},{filename:"/dgguspat/whistle.pat",start:5537894,end:5549947},{filename:"/dgguspat/whistle1.pat",start:5549947,end:5554262},
{filename:"/dgguspat/whistle2.pat",start:5554262,end:5556435},{filename:"/dgguspat/woodblk.pat",start:5556435,end:5564120},{filename:"/dgguspat/woodblk1.pat",start:5564120,end:5569155},{filename:"/dgguspat/woodblk2.pat",start:5569155,end:5576840},{filename:"/dgguspat/woodflut.pat",start:5576840,end:5581031},{filename:"/dgguspat/xylophon.pat",start:5581031,end:5600116},{filename:"/sw.cfg",start:5600116,end:5606521},{filename:"/sw.grp",start:5606521,end:31663290},{filename:"/sw.rts",start:31663290,
end:31930916},{filename:"/timidity.cfg",start:31930916,end:31933462},{filename:"/user_profiles_disabled",start:31933462,end:31933462}],remote_package_size:31933462})})();var aa=Object.assign({},h),ba=[],ca="./this.program",da="",ea;"undefined"!=typeof document&&document.currentScript&&(da=document.currentScript.src);da=da.startsWith("blob:")?"":da.substr(0,da.replace(/[?#].*/,"").lastIndexOf("/")+1);
ea=a=>fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var fa=h.print||console.log.bind(console),k=h.printErr||console.error.bind(console);Object.assign(h,aa);aa=null;h.arguments&&(ba=h.arguments);h.thisProgram&&(ca=h.thisProgram);var ha=h.wasmBinary,ja,ka=!1,la,l,q,ma,na,u,w,x,y,oa=[],pa=[],qa=[],ra=[];function sa(){var a=h.preRun.shift();oa.unshift(a)}var ta=0,ua=null,va=null;function wa(){ta++;h.monitorRunDependencies?.(ta)}
function xa(){ta--;h.monitorRunDependencies?.(ta);if(0==ta&&(null!==ua&&(clearInterval(ua),ua=null),va)){var a=va;va=null;a()}}function z(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);ka=!0;la=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ya=a=>a.startsWith("data:application/octet-stream;base64,"),za;function Aa(a){if(a==za&&ha)return new Uint8Array(ha);throw"both async and sync fetching of the wasm failed";}
function Ba(a){return ha?Promise.resolve().then(()=>Aa(a)):ea(a).then(b=>new Uint8Array(b),()=>Aa(a))}function Ca(a,b,c){return Ba(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{k(`failed to asynchronously prepare wasm: ${d}`);z(d)})}
function Da(a,b){var c=za;ha||"function"!=typeof WebAssembly.instantiateStreaming||ya(c)||"function"!=typeof fetch?Ca(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){k(`wasm streaming compile failed: ${e}`);k("falling back to ArrayBuffer instantiation");return Ca(c,a,b)}))}
var A,B,Ha={534541:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,534688:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,534922:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.Oe||("undefined"!==typeof AudioContext?b.Oe=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.Oe=new webkitAudioContext),b.Oe&&
Ea(b.Oe));return void 0===b.Oe?-1:0},535415:()=>h.SDL2.Oe.sampleRate,535483:(a,b,c,d)=>{function e(){}function f(m){void 0!==g.capture.Cf&&(clearTimeout(g.capture.Cf),g.capture.Cf=void 0);g.capture.Pf=g.Oe.createMediaStreamSource(m);g.capture.Te=g.Oe.createScriptProcessor(b,a,1);g.capture.Te.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.bg=n.inputBuffer,Fa(c,[d]))};g.capture.Pf.connect(g.capture.Te);g.capture.Te.connect(g.Oe.destination);
g.capture.stream=m}var g=h.SDL2;g.capture.Uf=g.Oe.createBuffer(a,b,g.Oe.sampleRate);g.capture.Uf.getChannelData(0).fill(0);g.capture.Cf=setTimeout(function(){g.capture.bg=g.capture.Uf;Fa(c,[d])},b/g.Oe.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},537135:(a,b,c,d)=>{var e=h.SDL2;e.audio.Te=
e.Oe.createScriptProcessor(b,0,a);e.audio.Te.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.pg=f.outputBuffer,Fa(c,[d]))};e.audio.Te.connect(e.Oe.destination)},537545:(a,b)=>{for(var c=h.SDL2,d=c.capture.bg.numberOfChannels,e=0;e<d;++e){var f=c.capture.bg.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Ga(a+4*g,f[g]);else for(g=0;g<b;++g)Ga(a+4*(g*d+e),
f[g])}},538150:(a,b)=>{for(var c=h.SDL2,d=c.audio.pg.numberOfChannels,e=0;e<d;++e){var f=c.audio.pg.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=x[a+(g*d+e<<2)>>2]}},538630:a=>{var b=h.SDL2;if(a){void 0!==b.capture.Cf&&clearTimeout(b.capture.Cf);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.Te&&(b.capture.Te.onaudioprocess=function(){},b.capture.Te.disconnect(),b.capture.Te=void 0);void 0!==b.capture.Pf&&(b.capture.Pf.disconnect(),b.capture.Pf=void 0);void 0!==b.capture.Uf&&(b.capture.Uf=void 0);b.capture=void 0}else void 0!=b.audio.Te&&(b.audio.Te.disconnect(),b.audio.Te=void 0),b.audio=void 0;void 0!==b.Oe&&void 0===b.audio&&void 0===b.capture&&(b.Oe.close(),b.Oe=void 0)},539802:(a,b)=>{alert((a?C(q,a):"")+"\n\n"+(b?C(q,b):""))},539859:()=>
window.innerWidth,539889:()=>window.innerHeight,539920:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Qg!==h.canvas&&(d.Ye=h.createContext(h.canvas,!1,!0),d.Qg=h.canvas);if(d.w!==a||d.h!==b||d.ah!==d.Ye)d.image=d.Ye.createImageData(a,b),d.w=a,d.h=b,d.ah=d.Ye;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=u[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Tg!==a&&(d.Sg=new Int32Array(a.buffer),
d.Ug=new Uint8Array(a.buffer),d.Tg=a),a=d.Sg,c=a.length,a.set(u.subarray(b,b+c)),a=d.Ug,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Ye.putImageData(d.image,0,0)},541389:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&
b instanceof CanvasPixelArray)for(n=b.length;m<n;){var p=u[e];b[m]=p&255;b[m+1]=p>>8&255;b[m+2]=p>>16&255;b[m+3]=p>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(u.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=G(c.length+1);H(c,q,d,c.length+1);return d},542378:a=>{h.canvas&&(h.canvas.style.cursor=a?C(q,a):"")},542461:()=>{h.canvas&&(h.canvas.style.cursor="none")}};
function Ia(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Ja=a=>{for(;0<a.length;)a.shift()(h)},Ka=h.noExitRuntime||!0;
function Ga(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":l[a]=b;break;case "i8":l[a]=b;break;case "i16":ma[a>>1]=b;break;case "i32":u[a>>2]=b;break;case "i64":z("to do setValue(i64) use WASM_BIGINT");case "float":x[a>>2]=b;break;case "double":y[a>>3]=b;break;case "*":w[a>>2]=b;break;default:z(`invalid type for setValue: ${c}`)}}
var La="undefined"!=typeof TextDecoder?new TextDecoder:void 0,C=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&La)return La.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ma=()=>
{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>crypto.getRandomValues(a);z("initRandomDevice")},Na=a=>(Na=Ma())(a),Oa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Pa=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Oa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Qa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},Ra=a=>{if("/"===a)return"/";a=Pa(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Ta=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:Sa;if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Oa(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ua=[],Va=a=>{for(var b=0,c=0;c<a.length;++c){var d=
a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},H=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-
e},Wa=[];function Xa(a,b){Wa[a]={input:[],Se:[],ff:b};Ya(a,Za)}
var Za={open(a){var b=Wa[a.node.Af];if(!b)throw new I(43);a.Me=b;a.seekable=!1},close(a){a.Me.ff.Kf(a.Me)},Kf(a){a.Me.ff.Kf(a.Me)},read(a,b,c,d){if(!a.Me||!a.Me.ff.sg)throw new I(60);for(var e=0,f=0;f<d;f++){try{var g=a.Me.ff.sg(a.Me)}catch(m){throw new I(29);}if(void 0===g&&0===e)throw new I(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.Me||!a.Me.ff.dg)throw new I(60);try{for(var e=0;e<d;e++)a.Me.ff.dg(a.Me,b[c+e])}catch(f){throw new I(29);
}d&&(a.node.timestamp=Date.now());return e}},$a={sg(){a:{if(!Ua.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array(Va(a)+1);a=H(a,b,0,b.length);b.length=a;Ua=b}b=Ua.shift()}return b},dg(a,b){null===b||10===b?(fa(C(a.Se,0)),a.Se=[]):0!=b&&a.Se.push(b)},Kf(a){a.Se&&0<a.Se.length&&(fa(C(a.Se,0)),a.Se=[])},dh(){return{sh:25856,uh:5,rh:191,th:35387,qh:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,
22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},eh(){return 0},fh(){return[24,80]}},ab={dg(a,b){null===b||10===b?(k(C(a.Se,0)),a.Se=[]):0!=b&&a.Se.push(b)},Kf(a){a.Se&&0<a.Se.length&&(k(C(a.Se,0)),a.Se=[])}};function bb(a,b){var c=a.Sd?a.Sd.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Sd,a.Sd=new Uint8Array(b),0<a.Ne&&a.Sd.set(c.subarray(0,a.Ne),0))}
var J={af:null,$e(){return J.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new I(63);J.af||(J.af={dir:{node:{Ze:J.Ie.Ze,Ue:J.Ie.Ue,yf:J.Ie.yf,Qf:J.Ie.Qf,Fg:J.Ie.Fg,Xf:J.Ie.Xf,Gg:J.Ie.Gg,Tf:J.Ie.Tf,Vf:J.Ie.Vf},stream:{pf:J.Je.pf}},file:{node:{Ze:J.Ie.Ze,Ue:J.Ie.Ue},stream:{pf:J.Je.pf,read:J.Je.read,write:J.Je.write,lg:J.Je.lg,cg:J.Je.cg,Ag:J.Je.Ag}},link:{node:{Ze:J.Ie.Ze,Ue:J.Ie.Ue,Bf:J.Ie.Bf},stream:{}},og:{node:{Ze:J.Ie.Ze,Ue:J.Ie.Ue},stream:cb}});
c=db(a,b,c,d);K(c.mode)?(c.Ie=J.af.dir.node,c.Je=J.af.dir.stream,c.Sd={}):32768===(c.mode&61440)?(c.Ie=J.af.file.node,c.Je=J.af.file.stream,c.Ne=0,c.Sd=null):40960===(c.mode&61440)?(c.Ie=J.af.link.node,c.Je=J.af.link.stream):8192===(c.mode&61440)&&(c.Ie=J.af.og.node,c.Je=J.af.og.stream);c.timestamp=Date.now();a&&(a.Sd[b]=c,a.timestamp=c.timestamp);return c},Bh(a){return a.Sd?a.Sd.subarray?a.Sd.subarray(0,a.Ne):new Uint8Array(a.Sd):new Uint8Array(0)},Ie:{Ze(a){var b={};b.Wg=8192===(a.mode&61440)?a.id:
1;b.tg=a.id;b.mode=a.mode;b.jh=1;b.uid=0;b.Zg=0;b.Af=a.Af;K(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Ne:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Mg=new Date(a.timestamp);b.ih=new Date(a.timestamp);b.Pg=new Date(a.timestamp);b.Ng=4096;b.Og=Math.ceil(b.size/b.Ng);return b},Ue(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.Ne!=b))if(0==b)a.Sd=null,a.Ne=0;else{var c=a.Sd;a.Sd=new Uint8Array(b);c&&a.Sd.set(c.subarray(0,
Math.min(b,a.Ne)));a.Ne=b}},yf(){throw eb[44];},Qf(a,b,c,d){return J.createNode(a,b,c,d)},Fg(a,b,c){if(K(a.mode)){try{var d=fb(b,c)}catch(f){}if(d)for(var e in d.Sd)throw new I(55);}delete a.parent.Sd[a.name];a.parent.timestamp=Date.now();a.name=c;b.Sd[c]=a;b.timestamp=a.parent.timestamp},Xf(a,b){delete a.Sd[b];a.timestamp=Date.now()},Gg(a,b){var c=fb(a,b),d;for(d in c.Sd)throw new I(55);delete a.Sd[b];a.timestamp=Date.now()},Tf(a){var b=[".",".."],c;for(c of Object.keys(a.Sd))b.push(c);return b},
Vf(a,b,c){a=J.createNode(a,b,41471,0);a.link=c;return a},Bf(a){if(40960!==(a.mode&61440))throw new I(28);return a.link}},Je:{read(a,b,c,d,e){var f=a.node.Sd;if(e>=a.node.Ne)return 0;a=Math.min(a.node.Ne-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Sd||a.Sd.subarray)){if(f)return a.Sd=b.subarray(c,c+d),a.Ne=d;if(0===a.Ne&&0===e)return a.Sd=b.slice(c,c+d),a.Ne=d;if(e+
d<=a.Ne)return a.Sd.set(b.subarray(c,c+d),e),d}bb(a,e+d);if(a.Sd.subarray&&b.subarray)a.Sd.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Sd[e+f]=b[c+f];a.Ne=Math.max(a.Ne,e+d);return d},pf(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ne);if(0>b)throw new I(28);return b},lg(a,b,c){bb(a.node,b+c);a.node.Ne=Math.max(a.node.Ne,b+c)},cg(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new I(43);a=a.node.Sd;if(e&2||!a||a.buffer!==l.buffer){d=!0;z();e=void 0;if(!e)throw new I(48);
if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);l.set(a,e)}}else d=!1,e=a.byteOffset;return{Sf:e,oh:d}},Ag(a,b,c,d){J.Je.write(a,b,0,d,c,!1);return 0}}},gb=(a,b,c)=>{var d=`al ${a}`;ea(a).then(e=>{b(new Uint8Array(e));d&&xa(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&wa(d)},hb=h.preloadPlugins||[],kb=(a,b,c,d)=>{"undefined"!=typeof ib&&jb();var e=!1;hb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},mb=(a,
b,c,d,e,f,g,m,n,p)=>{function r(F){function D(E){p?.();m||lb(a,b,E,d,e,n);f?.();xa(t)}kb(F,v,D,()=>{g?.();xa(t)})||D(F)}var v=b?Ta(Pa(a+"/"+b)):a,t=`cp ${v}`;wa(t);"string"==typeof c?gb(c,r,g):r(c)},nb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},ob=null,pb={},qb=[],rb=1,sb=null,Sa="/",tb=!1,ub=!0,I=class{constructor(a){this.name="ErrnoError";this.Le=a}},eb={},vb=class{constructor(){this.Pe={};this.node=null}get flags(){return this.Pe.flags}set flags(a){this.Pe.flags=a}get position(){return this.Pe.position}set position(a){this.Pe.position=
a}},wb=class{constructor(a,b,c,d){a||=this;this.parent=a;this.$e=a.$e;this.zf=null;this.id=rb++;this.name=b;this.mode=c;this.Ie={};this.Je={};this.Af=d}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get gh(){return K(this.mode)}get vg(){return 8192===(this.mode&61440)}};
function L(a,b={}){a=Ta(a);if(!a)return{path:"",node:null};b=Object.assign({rg:!0,eg:0},b);if(8<b.eg)throw new I(32);a=a.split("/").filter(g=>!!g);for(var c=ob,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=fb(c,a[e]);d=Pa(d+"/"+a[e]);c.zf&&(!f||f&&b.rg)&&(c=c.zf.root);if(!f||b.mf)for(f=0;40960===(c.mode&61440);)if(c=xb(d),d=Ta(Qa(d),c),c=L(d,{eg:b.eg+1}).node,40<f++)throw new I(32);}return{path:d,node:c}}
function yb(a){for(var b;;){if(a===a.parent)return a=a.$e.zg,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function zb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%sb.length}function fb(a,b){var c=K(a.mode)?(c=Ab(a,"x"))?c:a.Ie.yf?0:2:54;if(c)throw new I(c);for(c=sb[zb(a.id,b)];c;c=c.qf){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ie.yf(a,b)}
function db(a,b,c,d){a=new wb(a,b,c,d);b=zb(a.parent.id,a.name);a.qf=sb[b];return sb[b]=a}function K(a){return 16384===(a&61440)}function Bb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Ab(a,b){if(ub)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Cb(a,b){try{return fb(a,b),20}catch(c){}return Ab(a,"wx")}function Db(a){a=qb[a];if(!a)throw new I(8);return a}
function Eb(a,b=-1){a=Object.assign(new vb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!qb[b])break a;throw new I(33);}a.fd=b;return qb[b]=a}function Fb(a,b=-1){a=Eb(a,b);a.Je?.xh?.(a);return a}var cb={open(a){a.Je=pb[a.node.Af].Je;a.Je.open?.(a)},pf(){throw new I(70);}};function Ya(a,b){pb[a]={Je:b}}
function Gb(a,b){var c="/"===b;if(c&&ob)throw new I(10);if(!c&&b){var d=L(b,{rg:!1});b=d.path;d=d.node;if(d.zf)throw new I(10);if(!K(d.mode))throw new I(54);}b={type:a,Gh:{},zg:b,hh:[]};a=a.$e(b);a.$e=b;b.root=a;c?ob=a:d&&(d.zf=b,d.$e&&d.$e.hh.push(b));return a}function Hb(a,b,c){var d=L(a,{parent:!0}).node;a=Ra(a);if(!a||"."===a||".."===a)throw new I(28);var e=Cb(d,a);if(e)throw new I(e);if(!d.Ie.Qf)throw new I(63);return d.Ie.Qf(d,a,b,c)}
function Ib(a,b){return Hb(a,(void 0!==b?b:511)&1023|16384,0)}function Jb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Hb(a,b|8192,c)}function Kb(a,b){if(!Ta(a))throw new I(44);var c=L(b,{parent:!0}).node;if(!c)throw new I(44);b=Ra(b);var d=Cb(c,b);if(d)throw new I(d);if(!c.Ie.Vf)throw new I(63);c.Ie.Vf(c,b,a)}
function Lb(a){var b=L(a,{parent:!0}).node;if(!b)throw new I(44);var c=Ra(a);a=fb(b,c);a:{try{var d=fb(b,c)}catch(f){d=f.Le;break a}var e=Ab(b,"wx");d=e?e:K(d.mode)?31:0}if(d)throw new I(d);if(!b.Ie.Xf)throw new I(63);if(a.zf)throw new I(10);b.Ie.Xf(b,c);b=zb(a.parent.id,a.name);if(sb[b]===a)sb[b]=a.qf;else for(b=sb[b];b;){if(b.qf===a){b.qf=a.qf;break}b=b.qf}}function xb(a){a=L(a).node;if(!a)throw new I(44);if(!a.Ie.Bf)throw new I(28);return Ta(yb(a.parent),a.Ie.Bf(a))}
function Mb(a,b){a=L(a,{mf:!b}).node;if(!a)throw new I(44);if(!a.Ie.Ze)throw new I(63);return a.Ie.Ze(a)}function Nb(a){return Mb(a,!0)}function Ob(a,b){a="string"==typeof a?L(a,{mf:!0}).node:a;if(!a.Ie.Ue)throw new I(63);a.Ie.Ue(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Pb(a,b,c){if(""===a)throw new I(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Pa(a);try{e=L(a,{mf:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new I(20);}else e=Hb(a,c,0),d=!0;if(!e)throw new I(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!K(e.mode))throw new I(54);if(!d&&(c=
e?40960===(e.mode&61440)?32:K(e.mode)&&("r"!==Bb(b)||b&512)?31:Ab(e,Bb(b)):44))throw new I(c);if(b&512&&!d){c=e;c="string"==typeof c?L(c,{mf:!0}).node:c;if(!c.Ie.Ue)throw new I(63);if(K(c.mode))throw new I(31);if(32768!==(c.mode&61440))throw new I(28);if(d=Ab(c,"w"))throw new I(d);c.Ie.Ue(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Eb({node:e,path:yb(e),flags:b,seekable:!0,position:0,Je:e.Je,lh:[],error:!1});e.Je.open&&e.Je.open(e);!h.logReadFiles||b&1||(Qb||={},a in Qb||(Qb[a]=1));return e}
function Rb(a){if(null===a.fd)throw new I(8);a.nf&&(a.nf=null);try{a.Je.close&&a.Je.close(a)}catch(b){throw b;}finally{qb[a.fd]=null}a.fd=null}function Sb(a,b,c){if(null===a.fd)throw new I(8);if(!a.seekable||!a.Je.pf)throw new I(70);if(0!=c&&1!=c&&2!=c)throw new I(28);a.position=a.Je.pf(a,b,c);a.lh=[];return a.position}
function Tb(a,b,c,d,e,f){if(0>d||0>e)throw new I(28);if(null===a.fd)throw new I(8);if(0===(a.flags&2097155))throw new I(8);if(K(a.node.mode))throw new I(31);if(!a.Je.write)throw new I(28);a.seekable&&a.flags&1024&&Sb(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new I(70);b=a.Je.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function Ub(a,b){a="string"==typeof a?a:yb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Pa(a+"/"+c);try{Ib(d)}catch(e){}a=d}}return d}function Vb(a,b,c,d){a=Pa(("string"==typeof a?a:yb(a))+"/"+b);c=nb(c,d);return Hb(a,(void 0!==c?c:438)&4095|32768,0)}
function lb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:yb(a),g=b?Pa(a+"/"+b):a);a=nb(d,e);g=Hb(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Ob(g,a|146);b=Pb(g,577);Tb(b,c,0,c.length,0,f);Rb(b);Ob(g,a)}}
function Wb(a,b,c,d){a=Pa(("string"==typeof a?a:yb(a))+"/"+b);b=nb(!!c,!!d);Wb.wg||(Wb.wg=64);var e=Wb.wg++<<8|0;Ya(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,m,n){for(var p=0,r=0;r<n;r++){try{var v=c()}catch(t){throw new I(29);}if(void 0===v&&0===p)throw new I(6);if(null===v||void 0===v)break;p++;g[m+r]=v}p&&(f.node.timestamp=Date.now());return p},write(f,g,m,n){for(var p=0;p<n;p++)try{d(g[m+p])}catch(r){throw new I(29);}n&&(f.node.timestamp=Date.now());return p}});return Jb(a,
b,e)}function Xb(a){if(!(a.vg||a.gh||a.link||a.Sd)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.Sd=(void 0)(a.url),a.Ne=a.Sd.length}catch(b){throw new I(29);}}}
function Yb(a,b,c,d,e){if("undefined"!=typeof XMLHttpRequest)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";c={vg:!1,url:c};var f=Vb(a,b,d,e);c.Sd?f.Sd=c.Sd:c.url&&(f.Sd=null,f.url=c.url);Object.defineProperties(f,{Ne:{get:function(){return this.Sd.length}}});var g={};Object.keys(f.Je).forEach(m=>{var n=f.Je[m];g[m]=(...p)=>{Xb(f);return n(...p)}});g.read=(m,n,p,r,v)=>{Xb(f);m=m.node.Sd;if(v>=m.length)n=0;else{r=Math.min(m.length-
v,r);if(m.slice)for(var t=0;t<r;t++)n[p+t]=m[v+t];else for(t=0;t<r;t++)n[p+t]=m.get(v+t);n=r}return n};g.cg=()=>{Xb(f);z();throw new I(48);};f.Je=g;return f}var M={},Qb;
function Zb(a,b){if(1===a.type&&a.cf)throw new I(53);var c=a.rf.shift();if(!c){if(1===a.type){a=a.bf[a.gf+":"+a.hf];if(!a)throw new I(53);if(a.Ke.readyState===a.Ke.CLOSING||a.Ke.readyState===a.Ke.CLOSED)return null}throw new I(6);}var d=c.data.byteLength||c.data.length,e=c.data.byteOffset||0,f=c.data.buffer||c.data;b=Math.min(b,d);var g={buffer:new Uint8Array(f,e,b),Qe:c.Qe,port:c.port};1===a.type&&b<d&&(c.data=new Uint8Array(f,e+b,d-b),a.rf.unshift(c));return g}
function $b(a,b,c,d,e,f){if(2===a.type){if(void 0===e||void 0===f)e=a.gf,f=a.hf;if(void 0===e||void 0===f)throw new I(17);}else e=a.gf,f=a.hf;var g=a.bf[e+":"+f];if(1===a.type){if(!g||g.Ke.readyState===g.Ke.CLOSING||g.Ke.readyState===g.Ke.CLOSED)throw new I(53);if(g.Ke.readyState===g.Ke.CONNECTING)throw new I(6);}ArrayBuffer.isView(b)&&(c+=b.byteOffset,b=b.buffer);b=b.slice(c,c+d);if(2===a.type&&(!g||g.Ke.readyState!==g.Ke.OPEN))return g&&g.Ke.readyState!==g.Ke.CLOSING&&g.Ke.readyState!==g.Ke.CLOSED||
(g=ac(a,e,f)),g.If.push(b),d;try{return g.Ke.send(b),d}catch(m){throw new I(28);}}
function bc(a,b){var c=!0;b.Ke.onopen=function(){h.websocket.Jf("open",a.stream.fd);try{for(var d=b.If.shift();d;)b.Ke.send(d),d=b.If.shift()}catch(e){b.Ke.close()}};b.Ke.onclose=function(){h.websocket.Jf("close",a.stream.fd)};b.Ke.onmessage=function(d){a:{d=d.data;if("string"==typeof d)d=(new TextEncoder).encode(d);else{void 0!==d.byteLength||z();if(0==d.byteLength)break a;d=new Uint8Array(d)}var e=c;c=!1;e&&10===d.length&&255===d[0]&&255===d[1]&&255===d[2]&&255===d[3]&&112===d[4]&&111===d[5]&&114===
d[6]&&116===d[7]?(d=d[8]<<8|d[9],delete a.bf[b.Qe+":"+b.port],b.port=d,a.bf[b.Qe+":"+b.port]=b):(a.rf.push({Qe:b.Qe,port:b.port,data:d}),h.websocket.Jf("message",a.stream.fd))}};b.Ke.onerror=function(){a.error=14;h.websocket.Jf("error",[a.stream.fd,a.error,"ECONNREFUSED: Connection refused"])}}
function ac(a,b,c){if("object"==typeof b){var d=b;c=b=null}if(d)if(d.kg)b=d.kg.Ih,c=d.kg.Jh;else{c=/ws[s]?:\/\/([^:]+):(\d+)/.exec(d.url);if(!c)throw Error("WebSocket URL must be in the format ws(s)://address:port");b=c[1];c=parseInt(c[2],10)}else try{var e=h.websocket&&"object"===typeof h.websocket,f="ws://";e&&"string"===typeof h.websocket.url&&(f=h.websocket.url);if("ws://"===f||"wss://"===f){var g=b.split("/");f=f+g[0]+":"+c+"/"+g.slice(1).join("/")}g="binary";e&&"string"===typeof h.websocket.subprotocol&&
(g=h.websocket.subprotocol);var m=void 0;"null"!==g&&(m=g=g.replace(/^ +| +$/g,"").split(/ *, */));e&&null===h.websocket.subprotocol&&(m=void 0);d=new WebSocket(f,m);d.binaryType="arraybuffer"}catch(n){throw new I(23);}b={Qe:b,port:c,Ke:d,If:[]};a.bf[b.Qe+":"+b.port]=b;bc(a,b);2===a.type&&"undefined"!=typeof a.Df&&b.If.push(new Uint8Array([255,255,255,255,112,111,114,116,(a.Df&65280)>>8,a.Df&255]));return b}
var cc={$e(){h.websocket=h.websocket&&"object"===typeof h.websocket?h.websocket:{};h.websocket.Zf={};h.websocket.on=function(a,b){"function"===typeof b&&(this.Zf[a]=b);return this};h.websocket.Jf=function(a,b){"function"===typeof this.Zf[a]&&this.Zf[a].call(this,b)};return db(null,"/",16895,0)},Je:{Dg(a){a=a.node.sf;return a.gg.Dg(a)},Lf(a,b,c){a=a.node.sf;return a.gg.Lf(a,b,c)},read(a,b,c,d){a=Zb(a.node.sf,d);if(!a)return 0;b.set(a.buffer,c);return a.buffer.length},write(a,b,c,d){return $b(a.node.sf,
b,c,d)},close(a){a=a.node.sf;a.gg.close(a)}},Rf(){cc.Rf.current||(cc.Rf.current=0);return"socket["+cc.Rf.current++ +"]"},mh:{Dg(a){if(1===a.type&&a.cf)return a.pending.length?65:0;var b=0,c=1===a.type?a.bf[a.gf+":"+a.hf]:null;if(a.rf.length||!c||c&&c.Ke.readyState===c.Ke.CLOSING||c&&c.Ke.readyState===c.Ke.CLOSED)b|=65;if(!c||c&&c.Ke.readyState===c.Ke.OPEN)b|=4;if(c&&c.Ke.readyState===c.Ke.CLOSING||c&&c.Ke.readyState===c.Ke.CLOSED)b|=16;return b},Lf(a,b,c){switch(b){case 21531:return b=0,a.rf.length&&
(b=a.rf[0].data.length),u[c>>2]=b,0;default:return 28}},close(a){if(a.cf){try{a.cf.close()}catch(e){}a.cf=null}for(var b=Object.keys(a.bf),c=0;c<b.length;c++){var d=a.bf[b[c]];try{d.Ke.close()}catch(e){}delete a.bf[d.Qe+":"+d.port]}return 0},bind(a,b,c){if("undefined"!=typeof a.Hg||"undefined"!=typeof a.Df)throw new I(28);a.Hg=b;a.Df=c;if(2===a.type){a.cf&&(a.cf.close(),a.cf=null);try{throw new I(138);}catch(d){if("ErrnoError"!==d.name)throw d;if(138!==d.Le)throw d;}}},connect(a,b,c){if(a.cf)throw new I(138);
if("undefined"!=typeof a.gf&&"undefined"!=typeof a.hf){var d=a.bf[a.gf+":"+a.hf];if(d){if(d.Ke.readyState===d.Ke.CONNECTING)throw new I(7);throw new I(30);}}b=ac(a,b,c);a.gf=b.Qe;a.hf=b.port;throw new I(26);},accept(a){if(!a.cf||!a.pending.length)throw new I(28);var b=a.pending.shift();b.stream.flags=a.stream.flags;return b},Ch(a,b){if(b){if(void 0===a.gf||void 0===a.hf)throw new I(53);b=a.gf;a=a.hf}else b=a.Hg||0,a=a.Df||0;return{Qe:b,port:a}}}},dc=a=>{a=(a=qb[a])&&49152===(a.node.mode&49152)?a.node.sf:
null;if(!a)throw new I(8);return a},ec=a=>(a&255)+"."+(a>>8&255)+"."+(a>>16&255)+"."+(a>>24&255),gc=a=>{var b="",c,d=0,e=0,f=0,g=0;a=[a[0]&65535,a[0]>>16,a[1]&65535,a[1]>>16,a[2]&65535,a[2]>>16,a[3]&65535,a[3]>>16];var m=!0;for(c=0;5>c;c++)if(0!==a[c]){m=!1;break}if(m){c=ec(a[6]|a[7]<<16);if(-1===a[5])return"::ffff:"+c;if(0===a[5])return"0.0.0.0"===c&&(c=""),"0.0.0.1"===c&&(c="1"),"::"+c}for(c=0;8>c;c++)0===a[c]&&(1<c-e&&(g=0),e=c,g++),g>d&&(d=g,f=c-d+1);for(c=0;8>c;c++)1<d&&0===a[c]&&c>=f&&c<f+d?
c===f&&(b+=":",0===f&&(b+=":")):(b+=Number(fc(a[c]&65535)).toString(16),b+=7>c?":":"");return b},hc=(a,b)=>{var c=ma[a>>1],d=fc(na[a+2>>1]);switch(c){case 2:if(16!==b)return{Le:28};a=u[a+4>>2];a=ec(a);break;case 10:if(28!==b)return{Le:28};a=[u[a+8>>2],u[a+12>>2],u[a+16>>2],u[a+20>>2]];a=gc(a);break;default:return{Le:5}}return{family:c,Qe:a,port:d}},ic=a=>{a=a.split(".");for(var b=0;4>b;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0},kc=a=>{var b,
c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;if("::"===a)return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");0<a.indexOf(".")?(a=a.replace(RegExp("[.]","g"),":"),a=a.split(":"),a[a.length-4]=parseInt(a[a.length-4])+256*parseInt(a[a.length-3]),a[a.length-3]=parseInt(a[a.length-2])+256*parseInt(a[a.length-1]),a=a.slice(0,
a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if("string"==typeof a[b])if("Z"===a[b]){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=jc(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]},lc=1,mc={},nc={};function oc(a){var b=ic(a);if(null!==b)return a;b=kc(a);if(null!==b)return a;mc[a]?b=mc[a]:(b=lc++,65535>b||z("exceeded max address mappings of 65535"),b="172.29."+(b&255)+"."+(b&65280),nc[b]=a,mc[a]=b);return b}
function pc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?Sa:Db(a).path;if(0==b.length){if(!c)throw new I(44);return a}return Pa(a+"/"+b)}
function qc(a,b,c){a=a(b);u[c>>2]=a.Wg;u[c+4>>2]=a.mode;w[c+8>>2]=a.jh;u[c+12>>2]=a.uid;u[c+16>>2]=a.Zg;u[c+20>>2]=a.Af;B=[a.size>>>0,(A=a.size,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];u[c+24>>2]=B[0];u[c+28>>2]=B[1];u[c+32>>2]=4096;u[c+36>>2]=a.Og;b=a.Mg.getTime();var d=a.ih.getTime(),e=a.Pg.getTime();B=[Math.floor(b/1E3)>>>0,(A=Math.floor(b/1E3),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:
0)];u[c+40>>2]=B[0];u[c+44>>2]=B[1];w[c+48>>2]=b%1E3*1E3;B=[Math.floor(d/1E3)>>>0,(A=Math.floor(d/1E3),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];u[c+56>>2]=B[0];u[c+60>>2]=B[1];w[c+64>>2]=d%1E3*1E3;B=[Math.floor(e/1E3)>>>0,(A=Math.floor(e/1E3),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];u[c+72>>2]=B[0];u[c+76>>2]=B[1];w[c+80>>2]=e%1E3*1E3;B=[a.tg>>>0,(A=a.tg,1<=+Math.abs(A)?0<A?+Math.floor(A/
4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];u[c+88>>2]=B[0];u[c+92>>2]=B[1];return 0}var rc=void 0;function sc(){var a=u[+rc>>2];rc+=4;return a}
var tc=(a,b,c,d)=>{switch(b){case 2:c=ic(c);q.fill(0,a,a+16);ma[a>>1]=b;u[a+4>>2]=c;ma[a+2>>1]=jc(d);break;case 10:c=kc(c);q.fill(0,a,a+28);u[a>>2]=b;u[a+8>>2]=c[0];u[a+12>>2]=c[1];u[a+16>>2]=c[2];u[a+20>>2]=c[3];ma[a+2>>1]=jc(d);break;default:return 5}return 0},uc={},vc=a=>{if(!(a instanceof Ia||"unwind"==a))throw a;},wc=0,xc=a=>{la=a;Ka||0<wc||(h.onExit?.(a),ka=!0);throw new Ia(a);},yc=a=>{la=a;xc(a)},zc=a=>{if(!ka)try{if(a(),!(Ka||0<wc))try{la=a=la,xc(a)}catch(b){vc(b)}}catch(b){vc(b)}},Ac;
Ac=()=>performance.now();
var Kc=(a,b)=>{Bc=a;Cc=b;if(Dc)if(Ec||=!0,0==a)Fc=function(){var d=Math.max(0,Gc+b-Ac())|0;setTimeout(Hc,d)};else if(1==a)Fc=function(){Ic(Hc)};else if(2==a){if("undefined"==typeof Jc)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Jc=function(d){c.push(d);postMessage("setimmediate","*")}}else Jc=setImmediate;Fc=function(){Jc(Hc)}}},Qc=a=>{Dc=a;var b=Lc;Ec=!1;Hc=function(){if(!ka)if(0<
Mc.length){var c=Mc.shift();c.Ah(c.ph);if(Nc){var d=Nc,e=0==d%1?d-1:Math.floor(d);Nc=c.wh?e:(8*d+(e+.5))/9}h.setStatus&&(c=h.statusMessage||"Please wait...",d=Nc,e=Oc.yh,d?d<e?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(c):h.setStatus(""));b<Lc||setTimeout(Hc,0)}else if(!(b<Lc))if(Pc=Pc+1|0,1==Bc&&1<Cc&&0!=Pc%Cc)Fc();else{0==Bc&&(Gc=Ac());if(N)for(c=N.uf,N.uf=N.Ef,N.Ef=c,c=N.kf,N.kf=N.Wf,N.Wf=c,c=0;21>=c;++c)N.kf[c]=0;ka||h.preMainLoop&&!1===h.preMainLoop()||(zc(a),h.postMainLoop?.());
b<Lc||("object"==typeof SDL&&SDL.audio?.Hh?.(),Fc())}}},Rc=(a,b)=>setTimeout(()=>{zc(a)},b),Ec=!1,Fc=null,Lc=0,Dc=null,Bc=0,Cc=0,Pc=0,Mc=[];function Sc(){Fc=null;Lc++}function Tc(){Lc++;var a=Bc,b=Cc,c=Dc;Dc=null;Qc(c);Kc(a,b);Fc()}var Oc={},Gc,Hc,Nc,Uc=!1,Vc=!1,Wc=[];
function jb(){function a(){Vc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!Xc){Xc=!0;hb.push({canHandle:function(c){return!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:Yc(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Yc(d)}));var m=URL.createObjectURL(g),n=new Image;n.onload=()=>{var p=
document.createElement("canvas");p.width=n.width;p.height=n.height;p.getContext("2d").drawImage(n,0,0);URL.revokeObjectURL(m);e?.(c)};n.onerror=()=>{k(`Image ${m} could not be decoded`);f?.()};n.src=m}});hb.push({canHandle:function(c){return!h.noAudioDecoding&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e?.(c))}var g=!1,m=URL.createObjectURL(new Blob([c],{type:Yc(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=function(){if(!g){k(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var p="",r=0,v=0,t=0;t<c.length;t++)for(r=r<<8|c[t],v+=8;6<=v;){var F=r>>v-6&63;v-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[F]}2==v?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&3)<<4],p+="=="):4==v&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&15)<<2],p+="=");n.src="data:audio/x-"+d.substr(-3)+";base64,"+p;f(n)}};n.src=m;Rc(()=>{f(n)},1E4)}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!Vc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Zc=!1,$c=void 0,ad=void 0;function bd(){if(!Uc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var cd=0;
function Ic(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===cd)cd=b+1E3/60;else for(;b+2>=cd;)cd+=1E3/60;setTimeout(a,Math.max(cd-b,0))}}function Yc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var dd=[];function ed(){var a=h.canvas;dd.forEach(b=>b(a.width,a.height))}
function fd(a,b,c){b&&c?(a.nh=b,a.$g=c):(b=a.nh,c=a.$g);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}ad?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var ib={},Jc,Xc,O=12288,gd=!1,hd=0,jd=0,kd=0,P={alpha:!1,depth:!1,stencil:!1,antialias:!1},ld={},md,Q,nd=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},od=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},pd=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},qd=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},rd=1,sd=[],R=[],td=[],ud=[],vd=[],S=[],wd=[],xd=[],yd=[],zd=[1,1,2,2,4,4,4,2,3,4,8],Ad={},Bd=4,Cd=0,Dd=a=>{for(var b=rd++,c=a.length;c<b;c++)a[c]=null;return b},Ed=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=Q[c](),g=f&&Dd(d);f?(f.name=g,d[g]=f):T||=1282;u[b+4*e>>2]=g}},Gd=a=>{Fd=!1;for(var b=0;b<N.yg;++b){var c=N.lf[b];if(c.ag&&c.enabled){Fd=!0;var d=c.hg;d=0<d?a*d:c.size*zd[c.type-5120]*a;var e=32-Math.clz32(0===d?0:d-1);var f=N.uf[e],
g=N.kf[e];N.kf[e]=N.kf[e]+1&63;var m=f[g];m?e=m:(m=Q.getParameter(34964),f[g]=Q.createBuffer(),Q.bindBuffer(34962,f[g]),Q.bufferData(34962,1<<e,35048),Q.bindBuffer(34962,m),e=f[g]);Q.bindBuffer(34962,e);Q.bufferSubData(34962,0,q.subarray(c.Sf,c.Sf+d));c.Kg.call(Q,b,c.size,c.type,c.Bg,c.hg,0)}}},Id=(a,b)=>{a.Pe||(a.Pe=a.getContext,a.getContext=function(d,e){e=a.Pe(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Hd(c,b):0},Hd=(a,b)=>{var c=Dd(xd),
d={handle:c,attributes:b,version:b.xg,df:a};a.canvas&&(a.canvas.vf=d);xd[c]=d;("undefined"==typeof b.Xg||b.Xg)&&Jd(d);d.yg=d.df.getParameter(34921);d.lf=[];for(a=0;a<d.yg;a++)d.lf[a]={enabled:!1,ag:!1,size:0,type:0,Bg:0,hg:0,Sf:0,Kg:null};d.kf=[];d.Wf=[];d.kf.length=d.Wf.length=22;d.uf=[];d.Ef=[];d.uf.length=d.Ef.length=22;d.tf=[];d.tf.length=22;for(a=0;21>=a;++a){d.tf[a]=null;d.kf[a]=d.Wf[a]=0;d.uf[a]=[];d.Ef[a]=[];b=d.uf[a];var e=d.Ef[a];b.length=e.length=64;for(var f=0;64>f;++f)b[f]=e[f]=null}return c},
Kd=a=>{N=xd[a];h.Ye=Q=N?.df},Jd=a=>{a||=N;if(!a.bh){a.bh=!0;var b=a.df;nd(b);od(b);pd(b);b.ef=b.getExtension("EXT_disjoint_timer_query");b.Fh=b.getExtension("WEBGL_multi_draw");qd(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},Ld={},T,N,Fd,Md=a=>{var b=Va(a)+1,c=G(b);c&&H(a,q,c,b);return c},Nd=[],Od=(a,b)=>{Nd.length=0;for(var c;c=q[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Nd.push(112==c?w[b>>2]:105==c?u[b>>2]:y[b>>3]);b+=d?8:4}return Nd},Pd=0,Qd=[];
function Rd(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var m in f)if(f[m]!=g[m])return!1;return!0}for(var e of Qd)if(e.ig==a&&d(e.mg,c))return;Qd.push({ig:a,Eg:b,mg:c});Qd.sort((f,g)=>f.Eg<g.Eg)}function Sd(a){Qd=Qd.filter(b=>b.ig!=a)}function Td(){return navigator.userActivation?navigator.userActivation.isActive:Pd&&Ud.Gf}function Vd(){if(Td()){var a=Qd;Qd=[];for(var b of a)b.ig(...b.mg)}}var Wd=[];
function Xd(a){var b=Wd[a];b.target.removeEventListener(b.Re,b.qg,b.Ve);Wd.splice(a,1)}function Yd(a){if(!a.target)return-4;if(a.We)a.qg=function(c){++Pd;Ud=a;Vd();a.Xe(c);Vd();--Pd},a.target.addEventListener(a.Re,a.qg,a.Ve),Wd.push(a);else for(var b=0;b<Wd.length;++b)Wd[b].target==a.target&&Wd[b].Re==a.Re&&Xd(b--);return 0}function Zd(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}function $d(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var ae={},Ud,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne={},oe=[0,document,window],U=a=>{a=2<a?a?C(q,a):"":a;return oe[a]||document.querySelector(a)},qe=a=>{var b=Va(a)+1,c=pe(b);H(a,q,c,b);return c},te=a=>{var b=re(),c=pe(8),d=c+4;a=qe(a.id);if(a=U(a))u[c>>2]=a.width,u[d>>2]=a.height;c=[u[c>>2],u[d>>2]];se(b);return c},ue=(a,b,c)=>{a=U(a);if(!a)return-4;a.width=b;a.height=c;return 0},ve=(a,b,c)=>{if(a.vh){var d=re();a=qe(a.id);ue(a,b,c);se(d)}else a.width=b,a.height=c},we=a=>{function b(){document.fullscreenElement||
document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),ve(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=p,a.style.paddingRight=r,a.style.paddingTop=v,a.style.paddingBottom=t,a.style.marginLeft=F,a.style.marginRight=D,a.style.marginTop=E,a.style.marginBottom=Z,document.body.style.margin=
ia,document.documentElement.style.overflow=sf,document.body.scroll=tf,a.style.jf=uf,a.vf&&a.vf.df.viewport(0,0,d,e),ne.Hf&&V(ne.Hf,37,0,ne.ng))}var c=te(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,p=a.style.paddingLeft,r=a.style.paddingRight,v=a.style.paddingTop,t=a.style.paddingBottom,F=a.style.marginLeft,D=a.style.marginRight,E=a.style.marginTop,Z=a.style.marginBottom,ia=document.body.style.margin,sf=document.documentElement.style.overflow,
tf=document.body.scroll,uf=a.style.jf;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},xe=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},ye=a=>0>oe.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},ze=(a,b)=>{if(0!=b.fg||0!=b.$f){we(a);var c=b.kh?innerWidth:screen.width,d=b.kh?innerHeight:screen.height,e=ye(a),f=e.width;e=e.height;var g=te(a),m=g[0];g=g[1];3==b.fg?(xe(a,(d-e)/2,(c-f)/
2),c=f,d=e):2==b.fg&&(c*g<m*d?(f=g*c/m,xe(a,(d-f)/2,0),d=f):(f=m*d/g,xe(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Yg&&(a.style.jf="optimizeSpeed",a.style.jf="-moz-crisp-edges",a.style.jf="-o-crisp-edges",a.style.jf="-webkit-optimize-contrast",a.style.jf="optimize-contrast",a.style.jf="crisp-edges",a.style.jf="pixelated");f=2==b.$f?devicePixelRatio:
1;0!=b.$f&&(c=c*f|0,d=d*f|0,ve(a,c,d),a.vf&&a.vf.df.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return $d()?-3:-1;ne=b;b.Hf&&V(b.Hf,37,0,b.ng);return 0},Ae=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},Be=(a,b)=>{y[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)y[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)y[a+
8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)l[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];l[a+1104]=b.connected;u[a+1108>>2]=b.index;u[a+8>>2]=b.axes.length;u[a+12>>2]=b.buttons.length;H(b.id,q,a+1112,64);H(b.mapping,q,a+1176,64)},Ce=[],De=(a,b,c,d,e,f,g,m)=>{b=R[b];if(a=Q[a](b,c))d=m&&H(a.name,q,m,d),e&&(u[e>>2]=d),f&&(u[f>>2]=a.size),g&&(u[g>>2]=a.type)},Ee=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=
1;break;case 36344:0!=c&&1!=c&&(T||=1280);return;case 36345:d=0;break;case 34466:var e=Q.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=Q.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":T||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:T||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||
e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:u[b+4*a>>2]=e[a];break;case 2:x[b+4*a>>2]=e[a];break;case 4:l[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){T||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:T||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=d;w[b>>2]=c;w[b+4>>2]=(c-w[b>>2])/4294967296;break;
case 0:u[b>>2]=d;break;case 2:x[b>>2]=d;break;case 4:l[b]=d?1:0}}else T||=1281},Fe=(a,b,c)=>{if(c){a=Q.ef.getQueryObjectEXT(yd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d;w[c+4>>2]=(d-w[c>>2])/4294967296}else T||=1281},Ge=(a,b,c)=>{if(c){a=Q.ef.getQueryObjectEXT(yd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else T||=1281};function He(){var a=qd(Q);return a=a.concat(a.map(b=>"GL_"+b))}
var Ie=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Je=a=>{var b=a.Ff,c=a.Jg,d;if(!b)for(a.Ff=b={},a.Ig={},d=0;d<Q.getProgramParameter(a,35718);++d){var e=Q.getActiveUniform(a,d);var f=e.name;e=e.size;var g=Ie(f);g=0<g?f.slice(0,g):f;var m=a.jg;a.jg+=e;c[g]=[e,m];for(f=0;f<e;++f)b[m]=f,a.Ig[m++]=g}},W=a=>{var b=Q.Rg;if(b){var c=b.Ff[a];"number"==typeof c&&(b.Ff[a]=c=Q.getUniformLocation(b,b.Ig[a]+(0<c?`[${c}]`:"")));return c}T||=1282},Ke=(a,b,c,d)=>{if(c)if(a=R[a],Je(a),a=Q.getUniform(a,W(b)),"number"==
typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:x[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:x[c+4*b>>2]=a[b]}else T||=1281},Le=(a,b,c,d)=>{if(c)if(N.lf[a].enabled&&k("glGetVertexAttrib*v on client-side array: not supported, bad data returned"),a=Q.getVertexAttrib(a,b),34975==b)u[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:x[c>>2]=a;break;case 5:u[c>>2]=Math.fround(a)}else for(b=
0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:x[c+4*b>>2]=a[b];break;case 5:u[c+4*b>>2]=Math.fround(a[b])}else T||=1281},Me=(a,b,c,d,e)=>{a-=5120;a=1==a?q:4==a?u:6==a?x:5==a||28922==a?w:na;b=d*((Cd||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Bd-1&-Bd);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Ne=[],Oe=[],Pe=(a,b)=>{if(!$d())return-1;a=U(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Td()?
ze(a,b):b.Vg?(Rd(ze,1,[a,b]),1):-2:-3:-4},Qe=()=>{try{if(navigator.getGamepads)return(be=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},Re=(a,b)=>{var c={target:U(2),Re:"beforeunload",We:b,Xe:(d=event)=>{var e=V(b,28,0,a);e&&=e?C(q,e):"";if(e)return d.preventDefault(),d.returnValue=e},Ve:!0};return Yd(c)},Se=(a,b,c,d,e,f)=>{ce||=G(256);a={target:U(a),Re:f,We:d,Xe:(g=event)=>{var m=g.target.id?g.target.id:"",n=ce;H(Zd(g.target),q,n+0,128);H(m,q,n+128,128);V(d,e,n,b)&&g.preventDefault()},
Ve:c};return Yd(a)},Te=(a,b,c,d,e)=>{ee||=G(276);return Yd({target:a,Re:e,We:d,Xe:(f=event)=>{var g=ee,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;l[g]=n;l[g+1]=$d();var p=n?m:de,r=p?.id||"";H(Zd(p),q,g+2,128);H(r,q,g+130,128);u[g+260>>2]=p?p.clientWidth:0;u[g+264>>2]=p?p.clientHeight:0;u[g+268>>2]=screen.width;u[g+272>>2]=screen.height;n&&(de=m);V(d,19,g,b)&&f.preventDefault()},Ve:c})},Ue=(a,b,c,d,e)=>{fe||=G(1240);
b={target:U(2),Gf:!0,Re:e,We:c,Xe:(f=event)=>{var g=fe;Be(g,f.gamepad);V(c,d,g,a)&&f.preventDefault()},Ve:b};return Yd(b)},Ve=(a,b,c,d,e,f)=>{ge||=G(160);a={target:U(a),Re:f,We:d,Xe:g=>{var m=ge;y[m>>3]=g.timeStamp;var n=m>>2;u[n+2]=g.location;l[m+12]=g.ctrlKey;l[m+13]=g.shiftKey;l[m+14]=g.altKey;l[m+15]=g.metaKey;l[m+16]=g.repeat;u[n+5]=g.charCode;u[n+6]=g.keyCode;u[n+7]=g.which;H(g.key||"",q,m+32,32);H(g.code||"",q,m+64,32);H(g.char||"",q,m+96,32);H(g.locale||"",q,m+128,32);V(d,e,m,b)&&g.preventDefault()},
Ve:c};return Yd(a)},We=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;l[a+24]=b.ctrlKey;l[a+25]=b.shiftKey;l[a+26]=b.altKey;l[a+27]=b.metaKey;ma[2*d+14]=b.button;ma[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=ye(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},Xe=(a,b,c,d,e,f)=>{he||=G(64);a=U(a);return Yd({target:a,Gf:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Re:f,We:d,Xe:(g=event)=>{We(he,g,a);V(d,e,he,
b)&&g.preventDefault()},Ve:c})},Ye=(a,b,c,d,e)=>{ie||=G(257);return Yd({target:a,Re:e,We:d,Xe:(f=event)=>{var g=ie,m=document.pointerLockElement||document.Pe||document.Lg||document.Yf;l[g]=!!m;var n=m?.id||"";H(Zd(m),q,g+1,128);H(n,q,g+129,128);V(d,20,g,b)&&f.preventDefault()},Ve:c})},Ze=(a,b,c,d)=>{je||=G(36);a=U(a);return Yd({target:a,Re:"resize",We:d,Xe:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=je;u[g>>2]=0;u[g+4>>2]=f.clientWidth;u[g+8>>2]=f.clientHeight;u[g+12>>2]=innerWidth;
u[g+16>>2]=innerHeight;u[g+20>>2]=outerWidth;u[g+24>>2]=outerHeight;u[g+28>>2]=pageXOffset|0;u[g+32>>2]=pageYOffset|0;V(d,10,g,b)&&e.preventDefault()}}},Ve:c})},$e=(a,b,c,d,e,f)=>{ke||=G(1552);a=U(a);return Yd({target:a,Gf:"touchstart"==f||"touchend"==f,Re:f,We:d,Xe:g=>{var m={},n=g.touches;for(var p of n)p.ug=p.Cg=0,m[p.identifier]=p;for(var r of g.changedTouches)r.ug=1,m[r.identifier]=r;for(var v of g.targetTouches)m[v.identifier].Cg=1;n=ke;y[n>>3]=g.timeStamp;l[n+12]=g.ctrlKey;l[n+13]=g.shiftKey;
l[n+14]=g.altKey;l[n+15]=g.metaKey;p=n+16;r=ye(a);v=0;for(let t of Object.values(m))if(m=p>>2,u[m]=t.identifier,u[m+1]=t.screenX,u[m+2]=t.screenY,u[m+3]=t.clientX,u[m+4]=t.clientY,u[m+5]=t.pageX,u[m+6]=t.pageY,l[p+28]=t.ug,l[p+29]=t.Cg,u[m+8]=t.clientX-(r.left|0),u[m+9]=t.clientY-(r.top|0),p+=48,31<++v)break;u[n+8>>2]=v;V(d,e,n,b)&&g.preventDefault()},Ve:c})},af=(a,b,c)=>{var d=oe[1];le||=G(8);return Yd({target:d,Re:"visibilitychange",We:c,Xe:(e=event)=>{var f=le,g=["hidden","visible","prerender",
"unloaded"].indexOf(document.visibilityState);l[f]=document.hidden;u[f+4>>2]=g;V(c,21,f,a)&&e.preventDefault()},Ve:b})},bf=(a,b,c,d)=>{me||=G(96);return Yd({target:a,Gf:!0,Re:"wheel",We:d,Xe:(e=event)=>{var f=me;We(f,e,a);y[f+64>>3]=e.deltaX;y[f+72>>3]=e.deltaY;y[f+80>>3]=e.deltaZ;u[f+88>>2]=e.deltaMode;V(d,9,f,b)&&e.preventDefault()},Ve:c})},cf={},ef=()=>{if(!df){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&
navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in cf)void 0===cf[b]?delete a[b]:a[b]=cf[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);df=c}return df},df,ff=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Ea=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&ff(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Fa=(a,b=[])=>{var c="vi".replace(/p/g,"i");(0,h["dynCall_"+c])(a,...b)},gf=a=>{try{a()}catch(b){z(b)}};
function hf(){var a=X,b={};for(let [c,d]of Object.entries(a))b[c]="function"==typeof d?(...e)=>{jf.push(c);try{return d(...e)}finally{ka||(jf.pop(),kf&&1===lf&&0===jf.length&&(lf=0,gf(mf),"undefined"!=typeof Fibers&&Fibers.Lh()))}}:d;return b}var lf=0,kf=null,nf=0,jf=[],of={},pf={},qf=0,rf=null,vf=[];function wf(){var a=G(4108),b=a+12;w[a>>2]=b;w[a+4>>2]=b+4096;b=jf[0];var c=of[b];void 0===c&&(c=qf++,of[b]=c,pf[c]=b);u[a+8>>2]=c;return a}
function xf(a){if(!ka){if(0===lf){var b=!1,c=!1;a((d=0)=>{if(!ka&&(nf=d,b=!0,c)){lf=2;gf(()=>yf(kf));"undefined"!=typeof ib&&Dc&&Tc();d=!1;try{var e=(0,X[pf[u[kf+8>>2]]])()}catch(m){e=m,d=!0}var f=!1;if(!kf){var g=rf;g&&(rf=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(lf=1,kf=wf(),"undefined"!=typeof ib&&Dc&&Sc(),gf(()=>zf(kf)))}else 2===lf?(lf=0,gf(Af),Bf(kf),kf=null,vf.forEach(zc)):z(`invalid state: ${lf}`);return nf}}[44].forEach(a=>{eb[a]=new I(a);eb[a].stack="<generic error, no stack>"});
sb=Array(4096);Gb(J,"/");Ib("/tmp");Ib("/home");Ib("/home/web_user");(function(){Ib("/dev");Ya(259,{read:()=>0,write:(d,e,f,g)=>g});Jb("/dev/null",259);Xa(1280,$a);Xa(1536,ab);Jb("/dev/tty",1280);Jb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Na(a).byteLength);return a[--b]};Wb("/dev","random",c);Wb("/dev","urandom",c);Ib("/dev/shm");Ib("/dev/shm/tmp")})();
(function(){Ib("/proc");var a=Ib("/proc/self");Ib("/proc/self/fd");Gb({$e(){var b=db(a,"fd",16895,73);b.Ie={yf(c,d){var e=Db(+d);c={parent:null,$e:{zg:"fake"},Ie:{Bf:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=Ub;h.FS_createDataFile=lb;h.FS_createPreloadedFile=mb;h.FS_unlink=Lb;h.FS_createLazyFile=Yb;h.FS_createDevice=Wb;
h.requestFullscreen=function(a,b){function c(){Uc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=bd,$c&&d.requestPointerLock(),Uc=!0,ad?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=w[SDL.screen>>2]|8388608),fd(h.canvas),ed()):fd(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),ad?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=
w[SDL.screen>>2]&-8388609),fd(h.canvas),ed()):fd(d));h.onFullScreen?.(Uc);h.onFullscreen?.(Uc)}$c=a;ad=b;"undefined"==typeof $c&&($c=!0);"undefined"==typeof ad&&(ad=!1);var d=h.canvas;Zc||(Zc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.requestAnimationFrame=Ic;h.setCanvasSize=function(a,b,c){fd(h.canvas,a,b);c||ed()};h.pauseMainLoop=Sc;h.resumeMainLoop=Tc;
h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};h.createContext=function(a,b,c,d){if(b&&h.Ye&&a==h.canvas)return h.Ye;var e;if(b){var f={antialias:!1,alpha:!1,xg:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof Ld&&(e=Id(a,f)))var m=xd[e].df}else m=a.getContext("2d");if(!m)return null;c&&(h.Ye=m,b&&Kd(e),Wc.forEach(n=>n()),jb());return m};for(var Y=0;32>Y;++Y)Ce.push(Array(Y));var Cf=new Float32Array(288);
for(Y=0;288>=Y;++Y)Ne[Y]=Cf.subarray(0,Y);var Df=new Int32Array(288);for(Y=0;288>=Y;++Y)Oe[Y]=Df.subarray(0,Y);
var Gf={c:(a,b,c,d)=>{z(`Assertion failed: ${a?C(q,a):""}, at: `+[b?b?C(q,b):"":"unknown filename",c,d?d?C(q,d):"":"unknown function"])},rb:(a,b)=>dynCall_vi(a,b),Qb:function(a){try{a=a?C(q,a):"";var b=L(a,{mf:!0});if(null===b.node)throw new I(44);if(!K(b.node.mode))throw new I(54);var c=Ab(b.node,"x");if(c)throw new I(c);Sa=b.path;return 0}catch(d){if("undefined"==typeof M||"ErrnoError"!==d.name)throw d;return-d.Le}},Rb:function(a,b,c){try{b=b?C(q,b):"";b=pc(a,b);if(c&-8)return-28;var d=L(b,{mf:!0}).node;
if(!d)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&Ab(d,a)?-2:0}catch(e){if("undefined"==typeof M||"ErrnoError"!==e.name)throw e;return-e.Le}},r:function(a,b,c){rc=c;try{var d=Db(a);switch(b){case 0:var e=sc();if(0>e)break;for(;qb[e];)e++;return Fb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=sc(),d.flags|=e,0;case 12:return e=sc(),ma[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof M||"ErrnoError"!==f.name)throw f;return-f.Le}},
Lb:function(a,b){try{var c=Db(a);return qc(Mb,c.path,b)}catch(d){if("undefined"==typeof M||"ErrnoError"!==d.name)throw d;return-d.Le}},Hb:function(a,b){try{if(0===b)return-28;var c=Sa,d=Va(c)+1;if(b<d)return-68;H(c,q,a,b);return d}catch(e){if("undefined"==typeof M||"ErrnoError"!==e.name)throw e;return-e.Le}},Cb:function(a,b,c){try{var d=Db(a);if(!d.nf){var e=L(d.path,{mf:!0}).node;if(!e.Ie.Tf)throw new I(54);var f=e.Ie.Tf(e);d.nf=f}a=0;for(var g=Sb(d,0,1),m=Math.floor(g/280);m<d.nf.length&&a+280<=
c;){var n=d.nf[m];if("."===n){var p=d.node.id;var r=4}else if(".."===n)p=L(d.path,{parent:!0}).node.id,r=4;else{var v=fb(d.node,n);p=v.id;r=8192===(v.mode&61440)?2:K(v.mode)?4:40960===(v.mode&61440)?10:8}B=[p>>>0,(A=p,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];u[b+a>>2]=B[0];u[b+a+4>>2]=B[1];B=[280*(m+1)>>>0,(A=280*(m+1),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];u[b+a+8>>2]=B[0];u[b+a+12>>
2]=B[1];ma[b+a+16>>1]=280;l[b+a+18]=r;H(n,q,b+a+19,256);a+=280;m+=1}Sb(d,280*m,0);return a}catch(t){if("undefined"==typeof M||"ErrnoError"!==t.name)throw t;return-t.Le}},k:function(a,b,c){rc=c;try{var d=Db(a);switch(b){case 21509:return d.Me?0:-59;case 21505:if(!d.Me)return-59;if(d.Me.ff.dh){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=sc();u[e>>2]=25856;u[e+4>>2]=5;u[e+8>>2]=191;u[e+12>>2]=35387;for(var f=0;32>f;f++)l[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.Me?
0:-59;case 21506:case 21507:case 21508:if(!d.Me)return-59;if(d.Me.ff.eh)for(e=sc(),a=[],f=0;32>f;f++)a.push(l[e+f+17]);return 0;case 21519:if(!d.Me)return-59;e=sc();return u[e>>2]=0;case 21520:return d.Me?-28:-59;case 21531:e=sc();if(!d.Je.Lf)throw new I(59);return d.Je.Lf(d,b,e);case 21523:if(!d.Me)return-59;d.Me.ff.fh&&(f=[24,80],e=sc(),ma[e>>1]=f[0],ma[e+2>>1]=f[1]);return 0;case 21524:return d.Me?0:-59;case 21515:return d.Me?0:-59;default:return-28}}catch(g){if("undefined"==typeof M||"ErrnoError"!==
g.name)throw g;return-g.Le}},Jb:function(a,b){try{return a=a?C(q,a):"",qc(Nb,a,b)}catch(c){if("undefined"==typeof M||"ErrnoError"!==c.name)throw c;return-c.Le}},Db:function(a,b,c){try{return b=b?C(q,b):"",b=pc(a,b),b=Pa(b),"/"===b[b.length-1]&&(b=b.substr(0,b.length-1)),Ib(b,c),0}catch(d){if("undefined"==typeof M||"ErrnoError"!==d.name)throw d;return-d.Le}},Ib:function(a,b,c,d){try{b=b?C(q,b):"";var e=d&256;b=pc(a,b,d&4096);return qc(e?Nb:Mb,b,c)}catch(f){if("undefined"==typeof M||"ErrnoError"!==
f.name)throw f;return-f.Le}},o:function(a,b,c,d){rc=d;try{b=b?C(q,b):"";b=pc(a,b);var e=d?sc():0;return Pb(b,c,e).fd}catch(f){if("undefined"==typeof M||"ErrnoError"!==f.name)throw f;return-f.Le}},yb:function(a,b){try{var c=dc(a),d=w[b+8>>2],e=u[b+12>>2],f=0;for(a=0;a<e;a++)f+=u[d+(8*a+4)>>2];var g=Zb(c,f);if(!g)return 0;var m=w[b>>2];m&&tc(m,c.family,oc(g.Qe),g.port);b=0;var n=g.buffer.byteLength;for(a=0;0<n&&a<e;a++){var p=u[d+(8*a+4)>>2];if(p){var r=Math.min(p,n);q.set(g.buffer.subarray(b,b+r),
w[d+8*a>>2]+b);b+=r;n-=r}}return b}catch(v){if("undefined"==typeof M||"ErrnoError"!==v.name)throw v;return-v.Le}},xb:function(a,b){try{var c=dc(a),d=w[b+8>>2],e=u[b+12>>2],f=w[b>>2],g=u[b+4>>2];if(f){var m=hc(f,g);if(m.Le)return-m.Le;var n=m.port;var p=m.Qe;var r=(nc[p]?nc[p]:null)||m.Qe}for(b=a=0;b<e;b++)a+=u[d+(8*b+4)>>2];var v=new Uint8Array(a);for(b=f=0;b<e;b++){var t=w[d+8*b>>2],F=u[d+(8*b+4)>>2];for(g=0;g<F;g++)v[f++]=l[t+g]}return $b(c,v,0,a,r,n)}catch(D){if("undefined"==typeof M||"ErrnoError"!==
D.name)throw D;return-D.Le}},wb:function(a,b,c){try{b&=-526337;if(1==b&&c&&6!=c)throw new I(66);var d={family:a,type:b,protocol:c,cf:null,error:null,bf:{},pending:[],rf:[],gg:cc.mh},e=cc.Rf(),f=db(cc.root,e,49152,0);f.sf=d;var g=Eb({path:e,node:f,flags:2,seekable:!1,Je:cc.Je});d.stream=g;return d.stream.fd}catch(m){if("undefined"==typeof M||"ErrnoError"!==m.name)throw m;return-m.Le}},Kb:function(a,b){try{return a=a?C(q,a):"",qc(Mb,a,b)}catch(c){if("undefined"==typeof M||"ErrnoError"!==c.name)throw c;
return-c.Le}},zb:()=>{z("")},Ob:()=>1,Mb:(a,b,c)=>q.copyWithin(a,b,b+c),ub:()=>{Ka=!1;wc=0},vb:(a,b)=>{uc[a]&&(clearTimeout(uc[a].id),delete uc[a]);if(!b)return 0;var c=setTimeout(()=>{delete uc[a];zc(()=>Ef(a,Ac()))},b);uc[a]={id:c,Kh:b};return 0},cc:a=>{if(12448==a)return O=12288,1;O=12300;return 0},oc:(a,b,c,d,e)=>{if(62E3!=a)O=12296,c=0;else{if(b)for(;;){a=u[b>>2];if(12321==a)P.alpha=0<u[b+4>>2];else if(12325==a)P.depth=0<u[b+4>>2];else if(12326==a)P.stencil=0<u[b+4>>2];else if(12337==a)a=u[b+
4>>2],P.antialias=0<a;else if(12338==a)a=u[b+4>>2],P.antialias=1==a;else if(12544==a)P.Dh=12547!=u[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(u[e>>2]=1),c&&0<d&&(w[c>>2]=62002),O=12288,c=1):(O=12300,c=0)}return c},mc:(a,b,c,d)=>{if(62E3!=a)return O=12296,0;for(a=1;;){b=u[d>>2];if(12440==b)a=u[d+4>>2];else if(12344==b)break;else return O=12292,0;d+=8}if(2!=a)return O=12293,0;P.xg=a-1;P.Eh=0;md=Id(h.canvas,P);if(0!=md)return O=12288,Kd(md),Wc.forEach(function(e){e()}),Kd(null),62004;O=12297;return 0},
jc:(a,b)=>{if(62E3!=a)return O=12296,0;if(62002!=b)return O=12293,0;O=12288;return 62006},kc:(a,b)=>{if(62E3!=a)return O=12296,0;if(62004!=b)return O=12294,0;a=md;N===xd[a]&&(N=null);if("object"==typeof ae)for(var c=xd[a].df.canvas,d=0;d<Wd.length;++d)Wd[d].target!=c||Xd(d--);xd[a]&&xd[a].df.canvas&&(xd[a].df.canvas.vf=void 0);xd[a]=null;O=12288;hd==b&&(hd=0);return 1},ic:(a,b)=>{if(62E3!=a)return O=12296,0;if(62006!=b)return O=12301,1;jd==b&&(jd=0);kd==b&&(kd=0);O=12288;return 1},nc:(a,b,c,d)=>{if(62E3!=
a)return O=12296,0;if(62002!=b)return O=12293,0;if(!d)return O=12300,0;O=12288;switch(c){case 12320:return u[d>>2]=P.alpha?32:24,1;case 12321:return u[d>>2]=P.alpha?8:0,1;case 12322:return u[d>>2]=8,1;case 12323:return u[d>>2]=8,1;case 12324:return u[d>>2]=8,1;case 12325:return u[d>>2]=P.depth?24:0,1;case 12326:return u[d>>2]=P.stencil?8:0,1;case 12327:return u[d>>2]=12344,1;case 12328:return u[d>>2]=62002,1;case 12329:return u[d>>2]=0,1;case 12330:return u[d>>2]=4096,1;case 12331:return u[d>>2]=
16777216,1;case 12332:return u[d>>2]=4096,1;case 12333:return u[d>>2]=0,1;case 12334:return u[d>>2]=0,1;case 12335:return u[d>>2]=12344,1;case 12337:return u[d>>2]=P.antialias?4:0,1;case 12338:return u[d>>2]=P.antialias?1:0,1;case 12339:return u[d>>2]=4,1;case 12340:return u[d>>2]=12344,1;case 12341:case 12342:case 12343:return u[d>>2]=-1,1;case 12345:case 12346:return u[d>>2]=0,1;case 12347:return u[d>>2]=0,1;case 12348:return u[d>>2]=1;case 12349:case 12350:return u[d>>2]=0,1;case 12351:return u[d>>
2]=12430,1;case 12352:return u[d>>2]=4,1;case 12354:return u[d>>2]=0,1;default:return O=12292,0}},N:a=>{O=12288;return 0!=a&&1!=a?0:62E3},$b:()=>O,qc:(a,b,c)=>{if(62E3!=a)return O=12296,0;b&&(u[b>>2]=1);c&&(u[c>>2]=4);gd=!0;O=12288;return 1},hc:(a,b,c,d)=>{if(62E3!=a)return O=12296,0;if(0!=d&&62004!=d)return O=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return O=12301,0;Kd(d?md:null);hd=d;kd=b;jd=c;O=12288;return 1},bc:(a,b)=>{if(62E3!=a)return O=12296,0;O=12288;if(ld[b])return ld[b];switch(b){case 12371:a=
Md("Emscripten");break;case 12372:a=Md("1.4 Emscripten EGL");break;case 12373:a=Md("");break;case 12429:a=Md("OpenGL_ES");break;default:return O=12300,0}return ld[b]=a},gc:()=>{if(gd)if(h.Ye)if(h.Ye.isContextLost())O=12302;else return O=12288,1;else O=12290;else O=12289;return 0},fc:(a,b)=>{if(62E3!=a)return O=12296,0;0==b?Kc(0,0):Kc(1,b);O=12288;return 1},pc:a=>{if(62E3!=a)return O=12296,0;kd=jd=hd=0;gd=!1;O=12288;return 1},dc:()=>{O=12288;return 1},ec:()=>{O=12288;return 1},Q:(a,b,c)=>{b=Od(b,c);
return Ha[a](...b)},b:(a,b,c)=>{b=Od(b,c);return Ha[a](...b)},tc:(a,b,c)=>{b=Od(b,c);return Ha[a](...b)},Pb:()=>Date.now(),Sb:()=>{if(!$d())return-1;Sd(ze);var a=oe[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Zb:()=>{Sd(Ae);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},f:()=>devicePixelRatio,d:(a,b,c)=>{a=U(a);if(!a)return-4;a=ye(a);y[b>>3]=
a.width;y[c>>3]=a.height;return 0},O:(a,b)=>{if(0>a||a>=be.length)return-5;if(!be[a])return-7;Be(b,be[a]);return 0},Bb:()=>q.length,g:Ac,sc:()=>be.length,_b:(a,b)=>{u[a>>2]=screen.width;u[b>>2]=screen.height},Tb:a=>Q.activeTexture(a),Nb:(a,b)=>{Q.attachShader(R[a],S[b])},Ga:(a,b)=>{Q.ef.beginQueryEXT(a,yd[b])},Eb:(a,b,c)=>{Q.bindAttribLocation(R[a],b,c?C(q,c):"")},tb:(a,b)=>{34962==a?Q.wf=b:34963==a&&(Q.xf=b);Q.bindBuffer(a,sd[b])},pb:(a,b)=>{Q.bindFramebuffer(a,td[b])},ob:(a,b)=>{Q.bindRenderbuffer(a,
ud[b])},nb:(a,b)=>{Q.bindTexture(a,vd[b])},Uc:a=>{Q.bindVertexArray(wd[a]);a=Q.getParameter(34965);Q.xf=a?a.name|0:0},mb:(a,b,c,d)=>Q.blendColor(a,b,c,d),kb:a=>Q.blendEquation(a),jb:(a,b)=>Q.blendEquationSeparate(a,b),ib:(a,b)=>Q.blendFunc(a,b),hb:(a,b,c,d)=>Q.blendFuncSeparate(a,b,c,d),gb:(a,b,c,d)=>{Q.bufferData(a,c?q.subarray(c,c+b):b,d)},fb:(a,b,c,d)=>{Q.bufferSubData(a,b,q.subarray(d,d+c))},eb:a=>Q.checkFramebufferStatus(a),db:a=>Q.clear(a),cb:(a,b,c,d)=>Q.clearColor(a,b,c,d),bb:a=>Q.clearDepth(a),
$a:a=>Q.clearStencil(a),_a:(a,b,c,d)=>{Q.colorMask(!!a,!!b,!!c,!!d)},Za:a=>{Q.compileShader(S[a])},Ya:(a,b,c,d,e,f,g,m)=>{Q.compressedTexImage2D(a,b,c,d,e,f,m?q.subarray(m,m+g):null)},Xa:(a,b,c,d,e,f,g,m,n)=>{Q.compressedTexSubImage2D(a,b,c,d,e,f,g,n?q.subarray(n,n+m):null)},Wa:(a,b,c,d,e,f,g,m)=>Q.copyTexImage2D(a,b,c,d,e,f,g,m),Va:(a,b,c,d,e,f,g,m)=>Q.copyTexSubImage2D(a,b,c,d,e,f,g,m),Ua:()=>{var a=Dd(R),b=Q.createProgram();b.name=a;b.Of=b.Mf=b.Nf=0;b.jg=1;R[a]=b;return a},Ta:a=>{var b=Dd(S);S[b]=
Q.createShader(a);return b},Sa:a=>Q.cullFace(a),Qa:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=sd[d];e&&(Q.deleteBuffer(e),e.name=0,sd[d]=null,d==Q.wf&&(Q.wf=0),d==Q.xf&&(Q.xf=0))}},Pa:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=td[d];e&&(Q.deleteFramebuffer(e),e.name=0,td[d]=null)}},Oa:a=>{if(a){var b=R[a];b?(Q.deleteProgram(b),b.name=0,R[a]=null):T||=1281}},ab:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=yd[d];e&&(Q.ef.deleteQueryEXT(e),yd[d]=null)}},Na:(a,b)=>{for(var c=0;c<a;c++){var d=
u[b+4*c>>2],e=ud[d];e&&(Q.deleteRenderbuffer(e),e.name=0,ud[d]=null)}},Ma:a=>{if(a){var b=S[a];b?(Q.deleteShader(b),S[a]=null):T||=1281}},La:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=vd[d];e&&(Q.deleteTexture(e),e.name=0,vd[d]=null)}},Jc:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];Q.deleteVertexArray(wd[d]);wd[d]=null}},Ka:a=>Q.depthFunc(a),Ja:a=>{Q.depthMask(!!a)},Ia:(a,b)=>Q.depthRange(a,b),Ha:(a,b)=>{Q.detachShader(R[a],S[b])},Fa:a=>Q.disable(a),Ea:a=>{N.lf[a].enabled=!1;Q.disableVertexAttribArray(a)},
Da:(a,b,c)=>{Gd(b+c);Q.drawArrays(a,b,c);Fd&&Q.bindBuffer(34962,sd[Q.wf])},ac:(a,b,c,d)=>{Q.drawArraysInstanced(a,b,c,d)},lc:(a,b)=>{for(var c=Ce[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];Q.drawBuffers(c)},Ca:(a,b,c,d)=>{if(!Q.xf){var e=1*zd[c-5120]*b;var f=32-Math.clz32(0===e?0:e-1);var g=N.tf[f];g?f=g:(g=Q.getParameter(34965),N.tf[f]=Q.createBuffer(),Q.bindBuffer(34963,N.tf[f]),Q.bufferData(34963,1<<f,35048),Q.bindBuffer(34963,g),f=N.tf[f]);Q.bindBuffer(34963,f);Q.bufferSubData(34963,0,q.subarray(d,d+e));
d=0}Gd(b);Q.drawElements(a,b,c,d);Fd&&Q.bindBuffer(34962,sd[Q.wf]);Q.xf||Q.bindBuffer(34963,null)},Xb:(a,b,c,d,e)=>{Q.drawElementsInstanced(a,b,c,d,e)},Ba:a=>Q.enable(a),Aa:a=>{N.lf[a].enabled=!0;Q.enableVertexAttribArray(a)},va:a=>{Q.ef.endQueryEXT(a)},za:()=>Q.finish(),ya:()=>Q.flush(),xa:(a,b,c,d)=>{Q.framebufferRenderbuffer(a,b,c,ud[d])},wa:(a,b,c,d,e)=>{Q.framebufferTexture2D(a,b,c,vd[d],e)},ua:a=>Q.frontFace(a),ta:(a,b)=>{Ed(a,b,"createBuffer",sd)},ra:(a,b)=>{Ed(a,b,"createFramebuffer",td)},
lb:(a,b)=>{for(var c=0;c<a;c++){var d=Q.ef.createQueryEXT();if(!d){for(T||=1282;c<a;)u[b+4*c++>>2]=0;break}var e=Dd(yd);d.name=e;yd[e]=d;u[b+4*c>>2]=e}},qa:(a,b)=>{Ed(a,b,"createRenderbuffer",ud)},pa:(a,b)=>{Ed(a,b,"createTexture",vd)},yc:(a,b)=>{Ed(a,b,"createVertexArray",wd)},sa:a=>Q.generateMipmap(a),oa:(a,b,c,d,e,f,g)=>{De("getActiveAttrib",a,b,c,d,e,f,g)},na:(a,b,c,d,e,f,g)=>{De("getActiveUniform",a,b,c,d,e,f,g)},ma:(a,b,c,d)=>{a=Q.getAttachedShaders(R[a]);var e=a.length;e>b&&(e=b);u[c>>2]=e;
for(b=0;b<e;++b)u[d+4*b>>2]=S.indexOf(a[b])},la:(a,b)=>Q.getAttribLocation(R[a],b?C(q,b):""),ja:(a,b)=>Ee(a,b,4),ia:(a,b,c)=>{c?u[c>>2]=Q.getBufferParameter(a,b):T||=1281},ha:()=>{var a=Q.getError()||T;T=0;return a},ga:(a,b)=>Ee(a,b,2),fa:(a,b,c,d)=>{a=Q.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;u[d>>2]=a},ea:(a,b)=>Ee(a,b,0),ca:(a,b,c,d)=>{a=Q.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?H(a,q,d,b):0;c&&(u[c>>
2]=b)},da:(a,b,c)=>{if(c)if(a>=rd)T||=1281;else if(a=R[a],35716==b)a=Q.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.Of)for(b=0;b<Q.getProgramParameter(a,35718);++b)a.Of=Math.max(a.Of,Q.getActiveUniform(a,b).name.length+1);u[c>>2]=a.Of}else if(35722==b){if(!a.Mf)for(b=0;b<Q.getProgramParameter(a,35721);++b)a.Mf=Math.max(a.Mf,Q.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.Mf}else if(35381==b){if(!a.Nf)for(b=0;b<Q.getProgramParameter(a,35382);++b)a.Nf=
Math.max(a.Nf,Q.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.Nf}else u[c>>2]=Q.getProgramParameter(a,b);else T||=1281},od:Fe,Kd:Ge,dd:Fe,zd:Ge,$:(a,b,c)=>{c?u[c>>2]=Q.ef.getQueryEXT(a,b):T||=1281},ba:(a,b,c)=>{c?u[c>>2]=Q.getRenderbufferParameter(a,b):T||=1281},_:(a,b,c,d)=>{a=Q.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?H(a,q,d,b):0;c&&(u[c>>2]=b)},Z:(a,b,c,d)=>{a=Q.getShaderPrecisionFormat(a,b);u[c>>2]=a.rangeMin;u[c+4>>2]=a.rangeMax;u[d>>2]=a.precision},Y:(a,b,c,d)=>
{if(a=Q.getShaderSource(S[a]))b=0<b&&d?H(a,q,d,b):0,c&&(u[c>>2]=b)},aa:(a,b,c)=>{c?35716==b?(a=Q.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=Q.getShaderSource(S[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=Q.getShaderParameter(S[a],b):T||=1281},X:a=>{var b=Ad[a];if(!b){switch(a){case 7939:b=Md(He().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Q.getParameter(a))||(T||=1280);b=b?Md(b):0;break;case 7938:b=Md(`OpenGL ES 2.0 (${Q.getParameter(7938)})`);
break;case 35724:b=Q.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Md(b);break;default:T||=1280}Ad[a]=b}return b},W:(a,b,c)=>{c?x[c>>2]=Q.getTexParameter(a,b):T||=1281},V:(a,b,c)=>{c?u[c>>2]=Q.getTexParameter(a,b):T||=1281},S:(a,b)=>{b=b?C(q,b):"";if(a=R[a]){Je(a);var c=a.Ff,d=0,e=b,f=Ie(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Jg[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||
Q.getUniformLocation(a,b)))return d}else T||=1281;return-1},U:(a,b,c)=>{Ke(a,b,c,2)},T:(a,b,c)=>{Ke(a,b,c,0)},Id:(a,b,c)=>{c?(N.lf[a].enabled&&k("glGetVertexAttribPointer on client-side array: not supported, bad data returned"),u[c>>2]=Q.getVertexAttribOffset(a,b)):T||=1281},R:(a,b,c)=>{Le(a,b,c,2)},Jd:(a,b,c)=>{Le(a,b,c,5)},Hd:(a,b)=>Q.hint(a,b),Gd:a=>(a=sd[a])?Q.isBuffer(a):0,Fd:a=>Q.isEnabled(a),Ed:a=>(a=td[a])?Q.isFramebuffer(a):0,Dd:a=>(a=R[a])?Q.isProgram(a):0,Ra:a=>(a=yd[a])?Q.ef.isQueryEXT(a):
0,Cd:a=>(a=ud[a])?Q.isRenderbuffer(a):0,Bd:a=>(a=S[a])?Q.isShader(a):0,Ad:a=>(a=vd[a])?Q.isTexture(a):0,rc:a=>(a=wd[a])?Q.isVertexArray(a):0,yd:a=>Q.lineWidth(a),xd:a=>{a=R[a];Q.linkProgram(a);a.Ff=0;a.Jg={}},wd:(a,b)=>{3317==a?Bd=b:3314==a&&(Cd=b);Q.pixelStorei(a,b)},vd:(a,b)=>Q.polygonOffset(a,b),ka:(a,b)=>{Q.ef.queryCounterEXT(yd[a],b)},ud:(a,b,c,d,e,f,g)=>{(g=Me(f,e,c,d,g))?Q.readPixels(a,b,c,d,e,f,g):T||=1280},td:()=>{},sd:(a,b,c,d)=>Q.renderbufferStorage(a,b,c,d),rd:(a,b)=>{Q.sampleCoverage(a,
!!b)},qd:(a,b,c,d)=>Q.scissor(a,b,c,d),pd:()=>{T||=1280},nd:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=w[c+4*f>>2])?C(q,g,d?w[d+4*f>>2]:void 0):"";e+=g}Q.shaderSource(S[a],e)},md:(a,b,c)=>Q.stencilFunc(a,b,c),ld:(a,b,c,d)=>Q.stencilFuncSeparate(a,b,c,d),kd:a=>Q.stencilMask(a),jd:(a,b)=>Q.stencilMaskSeparate(a,b),id:(a,b,c)=>Q.stencilOp(a,b,c),hd:(a,b,c,d)=>Q.stencilOpSeparate(a,b,c,d),gd:(a,b,c,d,e,f,g,m,n)=>{n=n?Me(m,g,d,e,n):null;Q.texImage2D(a,b,c,d,e,f,g,m,n)},fd:(a,b,c)=>Q.texParameterf(a,
b,c),ed:(a,b,c)=>{Q.texParameterf(a,b,x[c>>2])},cd:(a,b,c)=>Q.texParameteri(a,b,c),bd:(a,b,c)=>{Q.texParameteri(a,b,u[c>>2])},ad:(a,b,c,d,e,f,g,m,n)=>{n=n?Me(m,g,e,f,n):null;Q.texSubImage2D(a,b,c,d,e,f,g,m,n)},$c:(a,b)=>{Q.uniform1f(W(a),b)},_c:(a,b,c)=>{if(288>=b)for(var d=Ne[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);Q.uniform1fv(W(a),d)},Zc:(a,b)=>{Q.uniform1i(W(a),b)},Yc:(a,b,c)=>{if(288>=b)for(var d=Oe[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);Q.uniform1iv(W(a),
d)},Xc:(a,b,c)=>{Q.uniform2f(W(a),b,c)},Wc:(a,b,c)=>{if(144>=b)for(var d=Ne[2*b],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);Q.uniform2fv(W(a),d)},Vc:(a,b,c)=>{Q.uniform2i(W(a),b,c)},Tc:(a,b,c)=>{if(144>=b)for(var d=Oe[2*b],e=0;e<2*b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2];else d=u.subarray(c>>2,c+8*b>>2);Q.uniform2iv(W(a),d)},Sc:(a,b,c,d)=>{Q.uniform3f(W(a),b,c,d)},Rc:(a,b,c)=>{if(96>=b)for(var d=Ne[3*b],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+
(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);Q.uniform3fv(W(a),d)},Qc:(a,b,c,d)=>{Q.uniform3i(W(a),b,c,d)},Pc:(a,b,c)=>{if(96>=b)for(var d=Oe[3*b],e=0;e<3*b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2];else d=u.subarray(c>>2,c+12*b>>2);Q.uniform3iv(W(a),d)},Oc:(a,b,c,d,e)=>{Q.uniform4f(W(a),b,c,d,e)},Nc:(a,b,c)=>{if(72>=b){var d=Ne[4*b],e=x;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=x.subarray(c>>
2,c+16*b>>2);Q.uniform4fv(W(a),d)},Mc:(a,b,c,d,e)=>{Q.uniform4i(W(a),b,c,d,e)},Lc:(a,b,c)=>{if(72>=b)for(var d=Oe[4*b],e=0;e<4*b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2];else d=u.subarray(c>>2,c+16*b>>2);Q.uniform4iv(W(a),d)},Kc:(a,b,c,d)=>{if(72>=b)for(var e=Ne[4*b],f=0;f<4*b;f+=4)e[f]=x[d+4*f>>2],e[f+1]=x[d+(4*f+4)>>2],e[f+2]=x[d+(4*f+8)>>2],e[f+3]=x[d+(4*f+12)>>2];else e=x.subarray(d>>2,d+16*b>>2);Q.uniformMatrix2fv(W(a),!!c,e)},Ic:(a,b,c,d)=>
{if(32>=b)for(var e=Ne[9*b],f=0;f<9*b;f+=9)e[f]=x[d+4*f>>2],e[f+1]=x[d+(4*f+4)>>2],e[f+2]=x[d+(4*f+8)>>2],e[f+3]=x[d+(4*f+12)>>2],e[f+4]=x[d+(4*f+16)>>2],e[f+5]=x[d+(4*f+20)>>2],e[f+6]=x[d+(4*f+24)>>2],e[f+7]=x[d+(4*f+28)>>2],e[f+8]=x[d+(4*f+32)>>2];else e=x.subarray(d>>2,d+36*b>>2);Q.uniformMatrix3fv(W(a),!!c,e)},Hc:(a,b,c,d)=>{if(18>=b){var e=Ne[16*b],f=x;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=
f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=x.subarray(d>>2,d+64*b>>2);Q.uniformMatrix4fv(W(a),!!c,e)},Gc:a=>{a=R[a];Q.useProgram(a);Q.Rg=a},Fc:a=>{Q.validateProgram(R[a])},Ec:(a,b)=>Q.vertexAttrib1f(a,b),Dc:(a,b)=>{Q.vertexAttrib1f(a,x[b>>2])},Cc:(a,b,c)=>Q.vertexAttrib2f(a,b,c),Bc:(a,b)=>{Q.vertexAttrib2f(a,x[b>>2],x[b+4>>2])},Ac:(a,b,c,d)=>Q.vertexAttrib3f(a,b,c,d),zc:(a,b)=>{Q.vertexAttrib3f(a,x[b>>
2],x[b+4>>2],x[b+8>>2])},xc:(a,b,c,d,e)=>Q.vertexAttrib4f(a,b,c,d,e),wc:(a,b)=>{Q.vertexAttrib4f(a,x[b>>2],x[b+4>>2],x[b+8>>2],x[b+12>>2])},Wb:(a,b)=>{Q.vertexAttribDivisor(a,b)},vc:(a,b,c,d,e,f)=>{var g=N.lf[a];Q.wf?(g.ag=!1,Q.vertexAttribPointer(a,b,c,!!d,e,f)):(g.size=b,g.type=c,g.Bg=d,g.hg=e,g.Sf=f,g.ag=!0,g.Kg=function(m,n,p,r,v,t){this.vertexAttribPointer(m,n,p,r,v,t)})},uc:(a,b,c,d)=>Q.viewport(a,b,c,d),n:()=>1,Ub:(a,b,c)=>Pe(a,{fg:u[c>>2],$f:u[c+4>>2],Yg:u[c+8>>2],Vg:b,Hf:u[c+12>>2],ng:u[c+
16>>2]}),M:(a,b)=>{a=U(a);return a?a.requestPointerLock?Td()?Ae(a):b?(Rd(Ae,2,[a]),1):-2:-1:-4},Ab:()=>{z("OOM")},P:Qe,s:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:Re(a,b),E:(a,b,c,d)=>Se(a,b,c,d,12,"blur"),e:ue,l:(a,b,c)=>{a=U(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},F:(a,b,c,d)=>Se(a,b,c,d,13,"focus"),v:(a,b,c,d)=>{if(!$d())return-1;a=U(a);if(!a)return-4;Te(a,b,c,d,"webkitfullscreenchange");return Te(a,b,c,d,"fullscreenchange")},j:(a,b,c)=>Qe()?-1:Ue(a,
b,c,26,"gamepadconnected"),i:(a,b,c)=>Qe()?-1:Ue(a,b,c,27,"gamepaddisconnected"),y:(a,b,c,d)=>Ve(a,b,c,d,2,"keydown"),w:(a,b,c,d)=>Ve(a,b,c,d,1,"keypress"),x:(a,b,c,d)=>Ve(a,b,c,d,3,"keyup"),K:(a,b,c,d)=>Xe(a,b,c,d,5,"mousedown"),I:(a,b,c,d)=>Xe(a,b,c,d,33,"mouseenter"),H:(a,b,c,d)=>Xe(a,b,c,d,34,"mouseleave"),L:(a,b,c,d)=>Xe(a,b,c,d,8,"mousemove"),J:(a,b,c,d)=>Xe(a,b,c,d,6,"mouseup"),z:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.Pe||document.body.Lg||
document.body.Yf))return-1;a=U(a);if(!a)return-4;Ye(a,b,c,d,"mozpointerlockchange");Ye(a,b,c,d,"webkitpointerlockchange");Ye(a,b,c,d,"mspointerlockchange");return Ye(a,b,c,d,"pointerlockchange")},u:(a,b,c,d)=>Ze(a,b,c,d),A:(a,b,c,d)=>$e(a,b,c,d,25,"touchcancel"),C:(a,b,c,d)=>$e(a,b,c,d,23,"touchend"),B:(a,b,c,d)=>$e(a,b,c,d,24,"touchmove"),D:(a,b,c,d)=>$e(a,b,c,d,22,"touchstart"),t:(a,b,c)=>af(a,b,c),G:(a,b,c,d)=>(a=U(a))?"undefined"!=typeof a.onwheel?bf(a,b,c,d):-1:-4,Vb:a=>document.title=a?C(q,
a):"",m:a=>xf(b=>Rc(b,a)),Fb:(a,b)=>{var c=0;ef().forEach((d,e)=>{var f=b+c;e=w[a+4*e>>2]=f;for(f=0;f<d.length;++f)l[e++]=d.charCodeAt(f);l[e]=0;c+=d.length+1});return 0},Gb:(a,b)=>{var c=ef();w[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);w[b>>2]=d;return 0},a:yc,h:function(a){try{var b=Db(a);Rb(b);return 0}catch(c){if("undefined"==typeof M||"ErrnoError"!==c.name)throw c;return c.Le}},q:function(a,b,c,d){try{a:{var e=Db(a);a=b;for(var f,g=b=0;g<c;g++){var m=w[a>>2],n=w[a+4>>2];a+=8;var p=e,
r=f,v=l;if(0>n||0>r)throw new I(28);if(null===p.fd)throw new I(8);if(1===(p.flags&2097155))throw new I(8);if(K(p.node.mode))throw new I(31);if(!p.Je.read)throw new I(28);var t="undefined"!=typeof r;if(!t)r=p.position;else if(!p.seekable)throw new I(70);var F=p.Je.read(p,v,m,n,r);t||(p.position+=F);var D=F;if(0>D){var E=-1;break a}b+=D;if(D<n)break;"undefined"!=typeof f&&(f+=D)}E=b}w[d>>2]=E;return 0}catch(Z){if("undefined"==typeof M||"ErrnoError"!==Z.name)throw Z;return Z.Le}},qb:function(a,b,c,d,
e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=Db(a);Sb(f,b,d);B=[f.position>>>0,(A=f.position,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];u[e>>2]=B[0];u[e+4>>2]=B[1];f.nf&&0===b&&0===d&&(f.nf=null);return 0}catch(g){if("undefined"==typeof M||"ErrnoError"!==g.name)throw g;return g.Le}},p:function(a,b,c,d){try{a:{var e=Db(a);a=b;for(var f,g=b=0;g<c;g++){var m=w[a>>2],n=w[a+4>>2];a+=8;var p=Tb(e,l,m,n,f);
if(0>p){var r=-1;break a}b+=p;if(p<n)break;"undefined"!=typeof f&&(f+=p)}r=b}w[d>>2]=r;return 0}catch(v){if("undefined"==typeof M||"ErrnoError"!==v.name)throw v;return v.Le}},Yb:(a,b,c,d)=>{function e(v,t,F,D,E,Z){var ia=10===v?28:16;E=10===v?gc(E):ec(E);ia=G(ia);!tc(ia,v,E,Z)||z();E=G(32);u[E+4>>2]=v;u[E+8>>2]=t;u[E+12>>2]=F;w[E+24>>2]=D;w[E+20>>2]=ia;u[E+16>>2]=10===v?28:16;u[E+28>>2]=0;return E}var f=0,g=0,m=0,n=0,p=0,r=0;c&&(m=u[c>>2],n=u[c+4>>2],p=u[c+8>>2],r=u[c+12>>2]);p&&!r&&(r=2===p?17:6);
!p&&r&&(p=17===r?2:1);0===r&&(r=6);0===p&&(p=1);if(!a&&!b)return-2;if(m&-1088||0!==c&&u[c>>2]&2&&!a)return-1;if(m&32)return-2;if(0!==p&&1!==p&&2!==p)return-7;if(0!==n&&2!==n&&10!==n)return-6;if(b&&(b=b?C(q,b):"",g=parseInt(b,10),isNaN(g)))return m&1024?-2:-8;if(!a)return 0===n&&(n=2),0===(m&1)&&(2===n?f=Ff(2130706433):f=[0,0,0,1]),a=e(n,p,r,null,f,g),w[d>>2]=a,0;a=a?C(q,a):"";f=ic(a);if(null!==f)if(0===n||2===n)n=2;else if(10===n&&m&8)f=[0,0,Ff(65535),f],n=10;else return-2;else if(f=kc(a),null!==
f)if(0===n||10===n)n=10;else return-2;if(null!=f)return a=e(n,p,r,a,f,g),w[d>>2]=a,0;if(m&4)return-2;a=oc(a);f=ic(a);0===n?n=2:10===n&&(f=[0,0,Ff(65535),f]);a=e(n,p,r,null,f,g);w[d>>2]=a;return 0},sb:xc},X=function(){function a(c){X=c.exports;X=hf();ja=X.Ld;c=ja.buffer;h.HEAP8=l=new Int8Array(c);h.HEAP16=ma=new Int16Array(c);h.HEAPU8=q=new Uint8Array(c);h.HEAPU16=na=new Uint16Array(c);h.HEAP32=u=new Int32Array(c);h.HEAPU32=w=new Uint32Array(c);h.HEAPF32=x=new Float32Array(c);h.HEAPF64=y=new Float64Array(c);
pa.unshift(X.Md);xa("wasm-instantiate");return X}var b={a:Gf};wa("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return k(`Module.instantiateWasm callback failed with error: ${c}`),!1}za||=ya("index.wasm")?"index.wasm":h.locateFile?h.locateFile("index.wasm",da):da+"index.wasm";Da(b,function(c){a(c.instance)});return{}}(),G=a=>(G=X.Nd)(a),Bf=a=>(Bf=X.Od)(a),jc=a=>(jc=X.Pd)(a),fc=a=>(fc=X.Qd)(a),Hf=h._main=(a,b)=>(Hf=h._main=X.Rd)(a,b),Ff=a=>(Ff=X.Td)(a),Ef=(a,b)=>
(Ef=X.Ud)(a,b),se=a=>(se=X.Vd)(a),pe=a=>(pe=X.Wd)(a),re=()=>(re=X.Xd)();h.dynCall_ii=(a,b)=>(h.dynCall_ii=X.Yd)(a,b);var dynCall_vi=h.dynCall_vi=(a,b)=>(dynCall_vi=h.dynCall_vi=X.Zd)(a,b);h.dynCall_viiiii=(a,b,c,d,e,f)=>(h.dynCall_viiiii=X._d)(a,b,c,d,e,f);h.dynCall_iiiii=(a,b,c,d,e)=>(h.dynCall_iiiii=X.$d)(a,b,c,d,e);h.dynCall_jiji=(a,b,c,d,e)=>(h.dynCall_jiji=X.ae)(a,b,c,d,e);h.dynCall_ji=(a,b)=>(h.dynCall_ji=X.be)(a,b);
var dynCall_iii=h.dynCall_iii=(a,b,c)=>(dynCall_iii=h.dynCall_iii=X.ce)(a,b,c);h.dynCall_viiii=(a,b,c,d,e)=>(h.dynCall_viiii=X.de)(a,b,c,d,e);var dynCall_v=h.dynCall_v=a=>(dynCall_v=h.dynCall_v=X.ee)(a),V=h.dynCall_iiii=(a,b,c,d)=>(V=h.dynCall_iiii=X.fe)(a,b,c,d),dynCall_vii=h.dynCall_vii=(a,b,c)=>(dynCall_vii=h.dynCall_vii=X.ge)(a,b,c);h.dynCall_viiiiii=(a,b,c,d,e,f,g)=>(h.dynCall_viiiiii=X.he)(a,b,c,d,e,f,g);h.dynCall_i=a=>(h.dynCall_i=X.ie)(a);
h.dynCall_iidiiii=(a,b,c,d,e,f,g)=>(h.dynCall_iidiiii=X.je)(a,b,c,d,e,f,g);h.dynCall_iiiiii=(a,b,c,d,e,f)=>(h.dynCall_iiiiii=X.ke)(a,b,c,d,e,f);h.dynCall_viiiiiiiiii=(a,b,c,d,e,f,g,m,n,p,r)=>(h.dynCall_viiiiiiiiii=X.le)(a,b,c,d,e,f,g,m,n,p,r);h.dynCall_viii=(a,b,c,d)=>(h.dynCall_viii=X.me)(a,b,c,d);h.dynCall_vffff=(a,b,c,d,e)=>(h.dynCall_vffff=X.ne)(a,b,c,d,e);h.dynCall_vf=(a,b)=>(h.dynCall_vf=X.oe)(a,b);h.dynCall_viiiiiiii=(a,b,c,d,e,f,g,m,n)=>(h.dynCall_viiiiiiii=X.pe)(a,b,c,d,e,f,g,m,n);
h.dynCall_viiiiiiiii=(a,b,c,d,e,f,g,m,n,p)=>(h.dynCall_viiiiiiiii=X.qe)(a,b,c,d,e,f,g,m,n,p);h.dynCall_vff=(a,b,c)=>(h.dynCall_vff=X.re)(a,b,c);h.dynCall_viiiiiii=(a,b,c,d,e,f,g,m)=>(h.dynCall_viiiiiii=X.se)(a,b,c,d,e,f,g,m);h.dynCall_vfi=(a,b,c)=>(h.dynCall_vfi=X.te)(a,b,c);h.dynCall_viif=(a,b,c,d)=>(h.dynCall_viif=X.ue)(a,b,c,d);h.dynCall_vif=(a,b,c)=>(h.dynCall_vif=X.ve)(a,b,c);h.dynCall_viff=(a,b,c,d)=>(h.dynCall_viff=X.we)(a,b,c,d);
h.dynCall_vifff=(a,b,c,d,e)=>(h.dynCall_vifff=X.xe)(a,b,c,d,e);h.dynCall_viffff=(a,b,c,d,e,f)=>(h.dynCall_viffff=X.ye)(a,b,c,d,e,f);h.dynCall_iiiiiiii=(a,b,c,d,e,f,g,m)=>(h.dynCall_iiiiiiii=X.ze)(a,b,c,d,e,f,g,m);h.dynCall_iiiiiii=(a,b,c,d,e,f,g)=>(h.dynCall_iiiiiii=X.Ae)(a,b,c,d,e,f,g);h.dynCall_iiiiiiiii=(a,b,c,d,e,f,g,m,n)=>(h.dynCall_iiiiiiiii=X.Be)(a,b,c,d,e,f,g,m,n);h.dynCall_iid=(a,b,c)=>(h.dynCall_iid=X.Ce)(a,b,c);h.dynCall_di=(a,b)=>(h.dynCall_di=X.De)(a,b);
var zf=a=>(zf=X.Ee)(a),mf=()=>(mf=X.Fe)(),yf=a=>(yf=X.Ge)(a),Af=()=>(Af=X.He)();h.addRunDependency=wa;h.removeRunDependency=xa;h.FS_createPreloadedFile=mb;h.FS_unlink=a=>Lb(a);h.FS_createPath=Ub;h.FS_createDevice=Wb;h.FS_createDataFile=(a,b,c,d,e,f)=>{lb(a,b,c,d,e,f)};h.FS_createLazyFile=Yb;h.allocate=(a,b)=>{b=1==b?pe(a.length):G(a.length);a.subarray||a.slice||(a=new Uint8Array(a));q.set(a,b);return b};var If;va=function Jf(){If||Kf();If||(va=Jf)};
function Lf(a=[]){var b=Hf;a.unshift(ca);var c=a.length,d=pe(4*(c+1)),e=d;a.forEach(g=>{w[e>>2]=qe(g);e+=4});w[e>>2]=0;try{var f=b(c,d);yc(f,!0)}catch(g){vc(g)}}
function Kf(){var a=ba;function b(){if(!If&&(If=!0,h.calledRun=!0,!ka)){cc.root=Gb(cc,null);if(!h.noFSInit&&!tb){var c,d;tb=!0;e??=h.stdin;c??=h.stdout;d??=h.stderr;e?Wb("/dev","stdin",e):Kb("/dev/tty","/dev/stdin");c?Wb("/dev","stdout",null,c):Kb("/dev/tty","/dev/stdout");d?Wb("/dev","stderr",null,d):Kb("/dev/tty1","/dev/stderr");Pb("/dev/stdin",0);Pb("/dev/stdout",1);Pb("/dev/stderr",1)}ub=!1;Ja(pa);Ja(qa);h.onRuntimeInitialized?.();Mf&&Lf(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=
[h.postRun]);h.postRun.length;){var e=h.postRun.shift();ra.unshift(e)}Ja(ra)}}if(!(0<ta)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)sa();Ja(oa);0<ta||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Mf=!0;h.noInitialRun&&(Mf=!1);Kf();
